DkRPG: UDkHeroGameplayAbility_TargetLock Class Reference
UDkHeroGameplayAbility_TargetLock Class Reference
Enables the Hero to lock onto a target.
#include <DkHeroGameplayAbility_TargetLock.h>
Protected Member Functions
void OnTargetLockTick (float DeltaTime)
Called every tick while the ability is active.
void SwitchTarget (const FGameplayTag &InSwitchDirectionTag)
Switches the locked-on target based on the given direction tag.
UGameplayAbility interface
virtual void ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData *TriggerEventData) override
Actually activates the ability.
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
Called when an ability ends normally or abnormally.
Protected Member Functions inherited from UDkGameplayAbility
UDkPawnCombatComponent * GetPawnCombatComponentFromActorInfo () const
Retrieves the pawn's combat component from the actor info.
UDkAbilitySystemComponent * GetDkAbilitySystemComponentFromActorInfo () const
Retrieves the ASC from the actor info.
FActiveGameplayEffectHandle NativeApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle) const
Applies a gameplay effect spec handle to a target actor.
FActiveGameplayEffectHandle BP_ApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle, EDkSuccessType &SuccessType)
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
void ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle &InSpecHandle, const TArray< FHitResult > &InHitResults)
Applies a gameplay effect spec handle to multiple hit results.
void OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount)
Callback when a gameplay tag changes that may cancel this ability.
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
Called right after an ability is given to the ASC.
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData=nullptr) override
Called right before the ability is activated.
Private Member Functions
void TryLockOnTarget ()
Attempts to lock onto a target.
void GetAvailableTargetsToLockOn ()
Finds all available targets to lock on within a box trace in front of the hero.
void DrawTargetLockWidget ()
Draws the target lock widget on the HUD.
void SetTargetLockWidgetPosition ()
Adjusts the target lock widget's position based on the current locked-on actor.
void InitTargetLockMovement ()
Initializes movement settings for the hero while target locking.
void InitTargetLockMappingContext ()
Adds the target lock input mapping context to the hero's input subsystem.
AActor * GetNearestTargetFromAvailableActors (const TArray< AActor * > &InAvailableTargets)
From the given list of available targets, finds and returns the nearest one to the hero.
void GetAvailableActorsAroundTarget (TArray< AActor * > &OutActorsOnLeft, TArray< AActor * > &OutActorsOnRight)
Divides available actors into those on the left and right of the current locked-on target.
void CancelTargetLockAbility ()
Calls the parent ability's CancelAbility function to end this ability.
void CleanUp ()
Cleans up any movement and UI state related to target locking.
void ResetTargetLockMovement ()
Resets movement settings for the hero after target locking ends.
void ResetTargetLockMappingContext ()
Removes the target lock input mapping context from the hero's input subsystem.
Private Attributes
float BoxTraceDistance { 5000.f }
The distance the box trace extends from the hero to find targets to lock on.
FVector TraceBoxSize { 2000.f, 2000.f, 300.f }
The size of the box trace used to find targets to lock on.
TArray< TEnumAsByte< EObjectTypeQuery > > BoxTraceChannel { EObjectTypeQuery::ObjectTypeQuery3 }
The channels used for box tracing to find targets.
bool bBoxTraceShowPersistentDebugShape { false }
Shows a persistent debug shape for the box trace if enabled.
TSubclassOf< UDkWidgetBase > TargetLockWidgetClass
The widget class used to display the target lock UI.
float TargetLockRotationInterpSpeed { 5.f }
The speed at which the hero rotates to face the locked-on target.
float TargetLockMaxWalkSpeed { 300.f }
The maximum walk speed of the hero while a target is locked on.
float TargetLockCameraOffset { 20.f }
The camera pitch offset applied when looking at the locked-on target.
TObjectPtr< UInputMappingContext > TargetLockMappingContext {}
The input mapping context to add when the ability is activated.
TArray< AActor * > AvailableTargetsToLockOn
The list of available targets found to lock on.
TObjectPtr< AActor > CurrentLockedOnActor {}
The currently locked-on target actor.
TObjectPtr< UDkWidgetBase > DrawnTargetLockWidget { }
The instance of the drawn target lock widget.
FVector2D TargetLockWidgetSize { FVector2D::ZeroVector }
The size of the target lock widget, used to offset its position correctly when added to viewport.
float CachedDefaultMaxWalkSpeed { }
Cached default max walk speed of the hero before target locking.
Additional Inherited Members
Public Member Functions inherited from UDkHeroGameplayAbility
ADkHero * GetHeroCharacterFromActorInfo ()
Retrieves the hero character from the actor info.
ADkHeroController * GetHeroControllerFromActorInfo ()
Retrieves the hero controller from the actor info.
UDkHeroCombatComponent * GetHeroCombatComponentFromActorInfo ()
Retrieves the hero combat component from the actor info.
UDkHeroUIComponent * GetHeroUIComponentFromActorInfo ()
Retrieves the hero UI component from the actor info.
FGameplayEffectSpecHandle MakeHeroDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, float InBaseDamage, FGameplayTag InAttackTag, int32 CurrentComboCount)
Creates a gameplay effect spec handle for hero damage effects.
FGameplayEffectSpecHandle MakeHeroWeaponAttackStaminaCostEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, FGameplayTag InCurrentAttackTag, float InStaminaCost)
Creates a gameplay effect spec handle for hero weapon attack stamina cost effects.
bool GetAbilityRemainingCooldownByTag (FGameplayTag InCooldownTag, float &TotalCooldownTime, float &RemainingCooldownTime)
Gets the remaining and total cooldown time for an ability by its cooldown tag. Returns true if the ability is still on cooldown.
Protected Attributes inherited from UDkGameplayAbility
EDkAbilityActivationPolicy AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered }
Defines the activation policy for this ability.
TMap< FGameplayTag, EDkAbilityCancelTrigger > CancelAbilityTriggers
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Detailed Description
Enables the Hero to lock onto a target.
As the logic of target locking can be quite complex, this ability is implemented in C++ instead of Blueprints.
Note
Decrease the sensitivity of mouse input by decreasing the IMC lower threshold: IMC_TargetLock -> IA_SwitchTarget -> Add Modifier -> Dead Zone -> Set Lower Threshold up to 0.95.
Todo
[RECONSIDER] Using Mouse Button Up/Down or Mouse Wheel input instead of the same Mouse Axis 2D?
Member Function Documentation
ActivateAbility()
void UDkHeroGameplayAbility_TargetLock::ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData * TriggerEventData) override protected virtual
Actually activates the ability.
{
    TryLockOnTarget();
    Super::ActivateAbility(Handle, ActorInfo, ActivationInfo, TriggerEventData);
}
References TryLockOnTarget().
CancelTargetLockAbility()
void UDkHeroGameplayAbility_TargetLock::CancelTargetLockAbility () private
Calls the parent ability's CancelAbility function to end this ability.
{
    CancelAbility(
        GetCurrentAbilitySpecHandle(),
        GetCurrentActorInfo(),
        GetCurrentActivationInfo(),
        true /* bReplicateCancelAbility */
    );
}
Referenced by GetAvailableActorsAroundTarget(), OnTargetLockTick(), SetTargetLockWidgetPosition(), and TryLockOnTarget().
CleanUp()
void UDkHeroGameplayAbility_TargetLock::CleanUp () private
Cleans up any movement and UI state related to target locking.
{
    AvailableTargetsToLockOn.Empty();
    CurrentLockedOnActor = nullptr;
    if (DrawnTargetLockWidget)
    {
        DrawnTargetLockWidget->RemoveFromParent();
    }
    DrawnTargetLockWidget = nullptr;
    TargetLockWidgetSize = FVector2D::ZeroVector;
    CachedDefaultMaxWalkSpeed = 0.f;
}
References AvailableTargetsToLockOn, CachedDefaultMaxWalkSpeed, CurrentLockedOnActor, DrawnTargetLockWidget, and TargetLockWidgetSize.
Referenced by EndAbility().
DrawTargetLockWidget()
void UDkHeroGameplayAbility_TargetLock::DrawTargetLockWidget () private
Draws the target lock widget on the HUD.
{
    if (DrawnTargetLockWidget)
    {
        // The ability is currently active, and the widget is already drawn
        return;
    }
    checkf(TargetLockWidgetClass, TEXT("Forgot to assign a valid TargetLockWidgetClass in %s 's Blueprint"), *GetName());
    DrawnTargetLockWidget = CreateWidget<UDkWidgetBase>(
        GetHeroControllerFromActorInfo(), // `ACharacter` cannot be the owning player
        TargetLockWidgetClass
    );
    checkf(DrawnTargetLockWidget, TEXT("Failed to create Target Lock Widget in %s 's Blueprint"), *GetName());
    DrawnTargetLockWidget->AddToViewport();
}
References DrawnTargetLockWidget, UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), and TargetLockWidgetClass.
Referenced by TryLockOnTarget().
EndAbility()
void UDkHeroGameplayAbility_TargetLock::EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override protected virtual
Called when an ability ends normally or abnormally.
Reimplemented from UDkGameplayAbility.
{
    ResetTargetLockMovement();
    ResetTargetLockMappingContext();
    CleanUp();
    Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
}
References CleanUp(), ResetTargetLockMappingContext(), and ResetTargetLockMovement().
GetAvailableActorsAroundTarget()
void UDkHeroGameplayAbility_TargetLock::GetAvailableActorsAroundTarget (TArray< AActor * > & OutActorsOnLeft, TArray< AActor * > & OutActorsOnRight) private
Divides available actors into those on the left and right of the current locked-on target.
Parameters
OutActorsOnLeft Array to be filled with actors on the left side.
OutActorsOnRight Array to be filled with actors on the right side.
{
    if (!CurrentLockedOnActor || AvailableTargetsToLockOn.IsEmpty())
    {
        CancelTargetLockAbility();
        return;
    }
    const FVector PlayerLocation{ GetHeroCharacterFromActorInfo()->GetActorLocation() };
    const FVector PlayerToCurrentTargetNormalized{ (CurrentLockedOnActor->GetActorLocation() - PlayerLocation).GetSafeNormal() };
    for (AActor* AvailableTarget : AvailableTargetsToLockOn)
    {
        if (!AvailableTarget || AvailableTarget == CurrentLockedOnActor)
        {
            continue; // Skip the current locked-on target
        }
        const FVector PlayerToAvailableTargetNormalized{ (AvailableTarget->GetActorLocation() - PlayerLocation).GetSafeNormal() };
        // Use the cross product to determine which side the target is on
        const FVector CrossProductResult{ FVector::CrossProduct(
            PlayerToCurrentTargetNormalized,
            PlayerToAvailableTargetNormalized
            ) };
        if (CrossProductResult.Z < 0.f)
        {
            // Target is on the left side
            OutActorsOnLeft.AddUnique(AvailableTarget);
        }
        else
        {
            // Target is on the right side
            OutActorsOnRight.AddUnique(AvailableTarget);
        }
    }
}
References AvailableTargetsToLockOn, CancelTargetLockAbility(), CurrentLockedOnActor, and UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo().
Referenced by SwitchTarget().
GetAvailableTargetsToLockOn()
void UDkHeroGameplayAbility_TargetLock::GetAvailableTargetsToLockOn () private
Finds all available targets to lock on within a box trace in front of the hero.
{
    AvailableTargetsToLockOn.Empty();
    TArray<FHitResult> BoxTraceHits;
    UKismetSystemLibrary::BoxTraceMultiForObjects(
        GetHeroCharacterFromActorInfo(),                                                            // World Context Object
        GetHeroCharacterFromActorInfo()->GetActorLocation(),                                        // Trace Start
        GetHeroCharacterFromActorInfo()->GetActorLocation() + GetHeroCharacterFromActorInfo()->GetActorForwardVector() * BoxTraceDistance, // Trace End
        TraceBoxSize / 2.f,                                                                         // Half Size
        GetHeroCharacterFromActorInfo()->GetActorForwardVector().ToOrientationRotator(),            // Orientation
        BoxTraceChannel,                                                                            // Object Types
        false,                                                                                      // bTraceComplex
        TArray<AActor*>(),                                                                          // Actors to Ignore
        bBoxTraceShowPersistentDebugShape ? EDrawDebugTrace::Persistent : EDrawDebugTrace::None,    // Draw Debug Type
        BoxTraceHits,                                                                               // Out Hit Results
        true                                                                                        // bIgnore Self
    );
    for (const FHitResult& TraceHit : BoxTraceHits)
    {
        if (AActor * HitActor{ TraceHit.GetActor() })
        {
            if (HitActor != GetHeroCharacterFromActorInfo())
            {
                AvailableTargetsToLockOn.AddUnique(HitActor);
            }
        }
    }
}
References AvailableTargetsToLockOn, bBoxTraceShowPersistentDebugShape, BoxTraceChannel, BoxTraceDistance, UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo(), and TraceBoxSize.
Referenced by SwitchTarget(), and TryLockOnTarget().
GetNearestTargetFromAvailableActors()
AActor * UDkHeroGameplayAbility_TargetLock::GetNearestTargetFromAvailableActors (const TArray< AActor * > & InAvailableTargets) private
From the given list of available targets, finds and returns the nearest one to the hero.
Parameters
InAvailableTargets The list of available targets to consider.
Returns
The nearest target actor, or nullptr if none found.
{
    float ClosestDistance{}; // Placeholder for out param
    return UGameplayStatics::FindNearestActor(
        GetHeroCharacterFromActorInfo()->GetActorLocation(),    // Origin
        InAvailableTargets,                                     // Target Actors
        ClosestDistance                                         // Out Distance
    );
}
References UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo().
Referenced by SwitchTarget(), and TryLockOnTarget().
InitTargetLockMappingContext()
void UDkHeroGameplayAbility_TargetLock::InitTargetLockMappingContext () private
Adds the target lock input mapping context to the hero's input subsystem.
{
    const ULocalPlayer* LocalPlayer{ GetHeroControllerFromActorInfo()->GetLocalPlayer() };
    UEnhancedInputLocalPlayerSubsystem* Subsystem{ ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(LocalPlayer) };
    checkf(Subsystem, TEXT("Enhanced Input Subsystem is missing from Local Player!"));
    // Add the target lock mapping context with higher priority than the default
    Subsystem->AddMappingContext(TargetLockMappingContext, UDkRPGFunctionLibrary::GetHeroDefaultInputMappingContextPriority() + 1);
}
References UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), UDkRPGFunctionLibrary::GetHeroDefaultInputMappingContextPriority(), and TargetLockMappingContext.
Referenced by TryLockOnTarget().
InitTargetLockMovement()
void UDkHeroGameplayAbility_TargetLock::InitTargetLockMovement () private
Initializes movement settings for the hero while target locking.
{
    CachedDefaultMaxWalkSpeed = GetHeroCharacterFromActorInfo()->GetCharacterMovement()->MaxWalkSpeed;
    GetHeroCharacterFromActorInfo()->GetCharacterMovement()->MaxWalkSpeed = TargetLockMaxWalkSpeed;
}
References CachedDefaultMaxWalkSpeed, UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo(), and TargetLockMaxWalkSpeed.
Referenced by TryLockOnTarget().
OnTargetLockTick()
void UDkHeroGameplayAbility_TargetLock::OnTargetLockTick (float DeltaTime) protected
Called every tick while the ability is active.
Most of the heavy lifting for target locking is done here.
{
    if (
        !CurrentLockedOnActor
        || UDkRPGFunctionLibrary::NativeDoesActorHaveTag(CurrentLockedOnActor, DkGameplayTags::Shared_Status_Death)
        || UDkRPGFunctionLibrary::NativeDoesActorHaveTag(GetHeroCharacterFromActorInfo(), DkGameplayTags::Shared_Status_Death)
        )
    {
        CancelTargetLockAbility();
        return;
    }
    SetTargetLockWidgetPosition();
    const bool bShouldOverrideRotation{
        !UDkRPGFunctionLibrary::NativeDoesActorHaveTag(GetHeroCharacterFromActorInfo(), DkGameplayTags::Player_Status_Rolling)
    };
    if (bShouldOverrideRotation)
    {
        FRotator LookAtRot{ UKismetMathLibrary::FindLookAtRotation(
            GetHeroCharacterFromActorInfo()->GetActorLocation(),        // Start
            CurrentLockedOnActor->GetActorLocation()                    // Target
            ) };
        LookAtRot -= FRotator{ TargetLockCameraOffset ,0.f,0.f }; // Move camera up a bit
        const FRotator CurrentControlRot{ GetHeroControllerFromActorInfo()->GetControlRotation() };
        const FRotator TargetRot{ FMath::RInterpTo(
            CurrentControlRot,              // Current
            LookAtRot,                      // Target
            DeltaTime,                      // Delta Time
            TargetLockRotationInterpSpeed   // Interp Speed
            ) };
        // Change camera's rotation via the controller's control rotation
        GetHeroControllerFromActorInfo()->SetControlRotation(FRotator{ TargetRot.Pitch, TargetRot.Yaw, 0.f });  // Lock Z rotation to 0
        // Change character's rotation directly
        GetHeroCharacterFromActorInfo()->SetActorRotation(FRotator{ 0.f, TargetRot.Yaw, 0.f });                 // Lock Pitch and Roll to 0
    }
}
References CancelTargetLockAbility(), CurrentLockedOnActor, UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo(), UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), UDkRPGFunctionLibrary::NativeDoesActorHaveTag(), SetTargetLockWidgetPosition(), TargetLockCameraOffset, and TargetLockRotationInterpSpeed.
ResetTargetLockMappingContext()
void UDkHeroGameplayAbility_TargetLock::ResetTargetLockMappingContext () private
Removes the target lock input mapping context from the hero's input subsystem.
{
    if (!GetHeroControllerFromActorInfo())
    {
        return;
    }
    const ULocalPlayer* LocalPlayer{ GetHeroControllerFromActorInfo()->GetLocalPlayer() };
    UEnhancedInputLocalPlayerSubsystem* Subsystem{ ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(LocalPlayer) };
    checkf(Subsystem, TEXT("Enhanced Input Subsystem is missing from Local Player!"));
    Subsystem->RemoveMappingContext(TargetLockMappingContext);
}
References UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), and TargetLockMappingContext.
Referenced by EndAbility().
ResetTargetLockMovement()
void UDkHeroGameplayAbility_TargetLock::ResetTargetLockMovement () private
Resets movement settings for the hero after target locking ends.
{
    if (CachedDefaultMaxWalkSpeed > 0.f)
    {
        GetHeroCharacterFromActorInfo()->GetCharacterMovement()->MaxWalkSpeed = CachedDefaultMaxWalkSpeed;
    }
}
References CachedDefaultMaxWalkSpeed, and UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo().
Referenced by EndAbility().
SetTargetLockWidgetPosition()
void UDkHeroGameplayAbility_TargetLock::SetTargetLockWidgetPosition () private
Adjusts the target lock widget's position based on the current locked-on actor.
Warning
This assumes that the root widget is a USizeBox
{
    if (!DrawnTargetLockWidget || !CurrentLockedOnActor)
    {
        CancelTargetLockAbility();
        return;
    }
    FVector2D ScreenPosition{};
    UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(
        GetHeroControllerFromActorInfo(),           // Player Controller
        CurrentLockedOnActor->GetActorLocation(),   // World Location
        ScreenPosition,                             // Out Screen Position
        true                                        // bPlayerViewportRelative
    );
    if (TargetLockWidgetSize == FVector2D::ZeroVector) // Only need to do this once
    {
        DrawnTargetLockWidget->WidgetTree->ForEachWidget(
            [this](UWidget* InWidget)
            {
                if (USizeBox * FoundSizeBox{ Cast<USizeBox>(InWidget) })
                {
                    TargetLockWidgetSize.X = FoundSizeBox->GetWidthOverride();
                    TargetLockWidgetSize.Y = FoundSizeBox->GetHeightOverride();
                }
            }
        );
    }
    ScreenPosition -= (TargetLockWidgetSize / 2.f); // Center the widget on the target
    DrawnTargetLockWidget->SetPositionInViewport(
        ScreenPosition,
        false // already taken as viewport relative when passing `true` to `ProjectWorldLocationToWidgetPosition` above
    );
}
References CancelTargetLockAbility(), CurrentLockedOnActor, DrawnTargetLockWidget, UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), and TargetLockWidgetSize.
Referenced by OnTargetLockTick(), and TryLockOnTarget().
SwitchTarget()
void UDkHeroGameplayAbility_TargetLock::SwitchTarget (const FGameplayTag & InSwitchDirectionTag) protected
Switches the locked-on target based on the given direction tag.
{
    GetAvailableTargetsToLockOn(); // refresh available targets
    TArray<AActor*> ActorsOnLeft, ActorsOnRight;
    AActor* NewTargetToLockOn{ };
    GetAvailableActorsAroundTarget(ActorsOnLeft, ActorsOnRight);
    if (InSwitchDirectionTag == DkGameplayTags::Player_Event_SwitchTarget_Left)
    {
        NewTargetToLockOn = GetNearestTargetFromAvailableActors(ActorsOnLeft);
    }
    else if (InSwitchDirectionTag == DkGameplayTags::Player_Event_SwitchTarget_Right)
    {
        NewTargetToLockOn = GetNearestTargetFromAvailableActors(ActorsOnRight);
    }
    if (NewTargetToLockOn)
    {
        CurrentLockedOnActor = NewTargetToLockOn;
    }
}
References CurrentLockedOnActor, GetAvailableActorsAroundTarget(), GetAvailableTargetsToLockOn(), and GetNearestTargetFromAvailableActors().
TryLockOnTarget()
void UDkHeroGameplayAbility_TargetLock::TryLockOnTarget () private
Attempts to lock onto a target.
{
    GetAvailableTargetsToLockOn();
    if (AvailableTargetsToLockOn.IsEmpty())
    {
        CancelTargetLockAbility();
        return;
    }
    CurrentLockedOnActor = GetNearestTargetFromAvailableActors(AvailableTargetsToLockOn);
    if (CurrentLockedOnActor)
    {
        DrawTargetLockWidget();
        SetTargetLockWidgetPosition();
        InitTargetLockMovement();
        InitTargetLockMappingContext();
    }
    else
    {
        CancelTargetLockAbility();
    }
}
References AvailableTargetsToLockOn, CancelTargetLockAbility(), CurrentLockedOnActor, DrawTargetLockWidget(), GetAvailableTargetsToLockOn(), GetNearestTargetFromAvailableActors(), InitTargetLockMappingContext(), InitTargetLockMovement(), and SetTargetLockWidgetPosition().
Referenced by ActivateAbility().
Member Data Documentation
AvailableTargetsToLockOn
TArray<AActor*> UDkHeroGameplayAbility_TargetLock::AvailableTargetsToLockOn private
The list of available targets found to lock on.
Referenced by CleanUp(), GetAvailableActorsAroundTarget(), GetAvailableTargetsToLockOn(), and TryLockOnTarget().
bBoxTraceShowPersistentDebugShape
bool UDkHeroGameplayAbility_TargetLock::bBoxTraceShowPersistentDebugShape { false } private
Shows a persistent debug shape for the box trace if enabled.
{ false };
Referenced by GetAvailableTargetsToLockOn().
BoxTraceChannel
TArray<TEnumAsByte<EObjectTypeQuery> > UDkHeroGameplayAbility_TargetLock::BoxTraceChannel { EObjectTypeQuery::ObjectTypeQuery3 } private
The channels used for box tracing to find targets.
{ EObjectTypeQuery::ObjectTypeQuery3 /* Pawn */ };
Referenced by GetAvailableTargetsToLockOn().
BoxTraceDistance
float UDkHeroGameplayAbility_TargetLock::BoxTraceDistance { 5000.f } private
The distance the box trace extends from the hero to find targets to lock on.
{ 5000.f };
Referenced by GetAvailableTargetsToLockOn().
CachedDefaultMaxWalkSpeed
float UDkHeroGameplayAbility_TargetLock::CachedDefaultMaxWalkSpeed { } private
Cached default max walk speed of the hero before target locking.
{ };
Referenced by CleanUp(), InitTargetLockMovement(), and ResetTargetLockMovement().
CurrentLockedOnActor
TObjectPtr<AActor> UDkHeroGameplayAbility_TargetLock::CurrentLockedOnActor {} private
The currently locked-on target actor.
{};
Referenced by CleanUp(), GetAvailableActorsAroundTarget(), OnTargetLockTick(), SetTargetLockWidgetPosition(), SwitchTarget(), and TryLockOnTarget().
DrawnTargetLockWidget
TObjectPtr<UDkWidgetBase> UDkHeroGameplayAbility_TargetLock::DrawnTargetLockWidget { } private
The instance of the drawn target lock widget.
{ };
Referenced by CleanUp(), DrawTargetLockWidget(), and SetTargetLockWidgetPosition().
TargetLockCameraOffset
float UDkHeroGameplayAbility_TargetLock::TargetLockCameraOffset { 20.f } private
The camera pitch offset applied when looking at the locked-on target.
{ 20.f };
Referenced by OnTargetLockTick().
TargetLockMappingContext
TObjectPtr<UInputMappingContext> UDkHeroGameplayAbility_TargetLock::TargetLockMappingContext {} private
The input mapping context to add when the ability is activated.
{};
Referenced by InitTargetLockMappingContext(), and ResetTargetLockMappingContext().
TargetLockMaxWalkSpeed
float UDkHeroGameplayAbility_TargetLock::TargetLockMaxWalkSpeed { 300.f } private
The maximum walk speed of the hero while a target is locked on.
{ 300.f };
Referenced by InitTargetLockMovement().
TargetLockRotationInterpSpeed
float UDkHeroGameplayAbility_TargetLock::TargetLockRotationInterpSpeed { 5.f } private
The speed at which the hero rotates to face the locked-on target.
{ 5.f };
Referenced by OnTargetLockTick().
TargetLockWidgetClass
TSubclassOf<UDkWidgetBase> UDkHeroGameplayAbility_TargetLock::TargetLockWidgetClass private
The widget class used to display the target lock UI.
Referenced by DrawTargetLockWidget().
TargetLockWidgetSize
FVector2D UDkHeroGameplayAbility_TargetLock::TargetLockWidgetSize { FVector2D::ZeroVector } private
The size of the target lock widget, used to offset its position correctly when added to viewport.
{ FVector2D::ZeroVector };
Referenced by CleanUp(), and SetTargetLockWidgetPosition().
TraceBoxSize
FVector UDkHeroGameplayAbility_TargetLock::TraceBoxSize { 2000.f, 2000.f, 300.f } private
The size of the box trace used to find targets to lock on.
{ 2000.f, 2000.f, 300.f };
Referenced by GetAvailableTargetsToLockOn().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility_TargetLock.h
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility_TargetLock.cpp