DkRPG: UDkInputComponent Class Reference
UDkInputComponent Class Reference
Custom input component built on top of the Enhanced Input system.
#include <DkInputComponent.h>
Public Member Functions
template<class UserObject, typename CallbackFunc>
void BindNativeInputAction (const UDkDataAsset_InputConfig *InInputConfig, const FGameplayTag &InInputTag, ETriggerEvent InTriggerEvent, UserObject *InCtxObject, CallbackFunc &&InFunc)
Binds a native input action defined in the input config using a Gameplay Tag.
template<class UserObject, typename CallbackFunc>
void BindAbilityInputAction (const UDkDataAsset_InputConfig *InInputConfig, UserObject *InCtxObject, CallbackFunc &&InPressedFunc, CallbackFunc &&InReleasedFunc)
Binds an ability input action defined in the input config using a Gameplay Tag.
Detailed Description
Custom input component built on top of the Enhanced Input system.
Note
Project Setup:
Set this class as the Default Input Component:
Project Settings -> Default Input Component Class -> this
Member Function Documentation
BindAbilityInputAction()
template<class UserObject, typename CallbackFunc> void UDkInputComponent::BindAbilityInputAction (const UDkDataAsset_InputConfig * InInputConfig, UserObject * InCtxObject, CallbackFunc && InPressedFunc, CallbackFunc && InReleasedFunc) inline
Binds an ability input action defined in the input config using a Gameplay Tag.
Note
Steps to bind ability inputs
Input Component –(pass input tags to callback)--> Hero character –(pass them to ASC)--> ASC –(activate abilities accordingly)--> Abilities triggered
Hero StartUp Data –(grant input tags to abilities)--> Hero character: receives abilities with corresponding tags
{
    checkf(InInputConfig, TEXT("InputConfig is nullptr in UDkInputComponent::BindNativeInputAction"));
    for (const FDkInputActionConfig& AbilityInputActionConfig : InInputConfig->AbilityInputActions)
    {
        if (!AbilityInputActionConfig.IsValid())
        {
            continue;
        }
        BindAction(AbilityInputActionConfig.InputAction, ETriggerEvent::Started, InCtxObject, InPressedFunc, AbilityInputActionConfig.InputTag);
        BindAction(AbilityInputActionConfig.InputAction, ETriggerEvent::Completed, InCtxObject, InReleasedFunc, AbilityInputActionConfig.InputTag);
    }
}
References UDkDataAsset_InputConfig::AbilityInputActions, FDkInputActionConfig::InputAction, FDkInputActionConfig::InputTag, and FDkInputActionConfig::IsValid().
Referenced by ADkHero::SetupPlayerInputComponent().
BindNativeInputAction()
template<class UserObject, typename CallbackFunc> void UDkInputComponent::BindNativeInputAction (const UDkDataAsset_InputConfig * InInputConfig, const FGameplayTag & InInputTag, ETriggerEvent InTriggerEvent, UserObject * InCtxObject, CallbackFunc && InFunc) inline
Binds a native input action defined in the input config using a Gameplay Tag.
Template Parameters
UserObject Type of the object that owns the callback
CallbackFunc Type of the callback function
Parameters
InInputConfig Input configuration data asset
InInputTag Gameplay Tag identifying the input action
InTriggerEvent Trigger event type (Pressed, Released, Triggered, etc.)
InCtxObject Object instance on which the callback will be invoked
InFunc Callback function to bind
{
    checkf(InInputConfig, TEXT("InputConfig is nullptr in UDkInputComponent::BindNativeInputAction"));
    if (UInputAction * FoundInputAction{ InInputConfig->FindInputActionByTag(InInputTag) })
    {
        BindAction(FoundInputAction, InTriggerEvent, InCtxObject, InFunc);
    }
}
References UDkDataAsset_InputConfig::FindInputActionByTag().
Referenced by ADkHero::SetupPlayerInputComponent().
The documentation for this class was generated from the following file:
D:/DkRPG/Source/DkRPG/Components/Input/DkInputComponent.h