DkRPG: ADkAIController Class Reference
ADkAIController Class Reference
AI controller that uses Detour Crowd for navigation and avoidance behavior.
#include <DkAIController.h>
Public Member Functions
ADkAIController (const FObjectInitializer &)
Sets up the path following algorithm to be Detour crowd avoidance.
IGenericTeamAgentInterface interface
virtual ETeamAttitude::Type GetTeamAttitudeTowards (const AActor &Other) const override
Returns the attitude of this AI controller towards another actor, either Hostile or Friendly.
Protected Member Functions
virtual void BeginPlay () override
Called when the game starts or when spawned.
virtual void OnEnemyPerceptionUpdated (AActor *Actor, FAIStimulus Stimulus)
Called when an enemy detects a hostile pawn.
Protected Attributes
TObjectPtr< UAIPerceptionComponent > EnemyPerceptionComponent
Perception component to detect enemies.
TObjectPtr< UAISenseConfig_Sight > AISenseConfig_Sight
Sight configuration for the perception component.
Private Attributes
bool bEnableDetourCrowdAvoidance { true }
Whether to use Detour crowd avoidance.
int32 DetourCrowdAvoidanceQuality { 4 }
The quality of Detour crowd avoidance.
float DetourCrowdCollisionQueryRange { 600.0f }
The collision query range for Detour crowd avoidance.
Detailed Description
AI controller that uses Detour Crowd for navigation and avoidance behavior.
Note
In order for the algorithm to function properly, some configuration is required.
From C++, some parameters are in the category Detour Crowd Avoidance Config of this class.
Other parameters are set in the project settings under Project Settings > Engine > Crowd Manager, described below.
Avoidance Config (Index 0..3)
Array of avoidance quality presets corresponding to quality levels Low, Medium, Good, and High.
Velocity bias:
0: Fully used velocity computed by graph following algorithm
No crowd avoidance applied
Results in agents sliding as they are trying to reach their targets
1: Fully used velocity computed by Detour crowd avoidance
No sliding, but agents may not reach their targets
Set to: 0
Sampling Patterns
Defines velocity sampling distributions used for avoidance.
More patterns improve accuracy but increase CPU cost.
Leave empty as default.
Max Agents
Maximum number of agents managed by the Detour Crowd system.
Agents exceeding this limit will not receive crowd avoidance.
Set to: 50
Max Agent Radius
Maximum supported agent collision radius (Unreal units).
Must be greater than or equal to the largest agent capsule radius.
Set to: 300.0
Max Avoided Agents
Maximum number of neighboring agents considered for avoidance.
Higher values improve behavior in dense crowds at higher CPU cost.
Set to: 6
Max Avoided Walls
Maximum number of nearby navmesh walls considered for avoidance.
Improves navigation around corners and narrow passages.
Set to: 8
Navmesh Check Interval
Time interval (seconds) between navmesh validity checks.
Lower values improve robustness but increase CPU usage.
Set to: 1.0
Path Optimization Interval
Time interval (seconds) between path smoothing updates.
Lower values result in smoother movement and faster correction.
Set to: 0.5
Separation Dir Clamp
Limits the strength of lateral separation steering.
Prevents excessive side movement and jitter.
Values:
-1: No clamping (full separation force)
Set to: 0
Path Offset Radius Multiplier
Multiplier applied to path center offset.
Controls how far agents deviate from the navmesh centerline.
Recommended:
1.0 (default)
>1.0 to encourage spreading
<1.0 to keep agents centered
Set to: 0
Resolve Collisions
Enabled: Collision handled by CharacterMovementComponent.
Disabled: Collision handled by GraphFollowingComponent.
Set to: Enabled
Constructor & Destructor Documentation
ADkAIController()
ADkAIController::ADkAIController (const FObjectInitializer & ObjectInitializer)
Sets up the path following algorithm to be Detour crowd avoidance.
In the parent class, the PathFollowingComponent is of type UPathFollowingComponent.
UPROPERTY(VisibleDefaultsOnly, Category = AI)
TObjectPtr<UPathFollowingComponent> PathFollowingComponent;
We need to override it to use UCrowdFollowingComponent instead, which is a subclass of UPathFollowingComponent
    : Super(ObjectInitializer.SetDefaultSubobjectClass<UCrowdFollowingComponent>("PathFollowingComponent"))
{
    AISenseConfig_Sight = CreateDefaultSubobject<UAISenseConfig_Sight>(TEXT("EnemnySenseConfig_Sight"));
    AISenseConfig_Sight->DetectionByAffiliation.bDetectEnemies = true;      // Can see hostile pawn, which is the Hero character
    AISenseConfig_Sight->DetectionByAffiliation.bDetectFriendlies = false;  // Cannot see friendly pawns, which are other AI characters
    AISenseConfig_Sight->DetectionByAffiliation.bDetectNeutrals = false;    // Cannot see neutral pawns
    AISenseConfig_Sight->SightRadius = 5000.0f;
    AISenseConfig_Sight->LoseSightRadius = 0.f;                 // Never lose sight
    AISenseConfig_Sight->PeripheralVisionAngleDegrees = 360.0f; // 360 degrees vision
    EnemyPerceptionComponent = CreateDefaultSubobject<UAIPerceptionComponent>(TEXT("EnemyPerceptionComponent"));
    EnemyPerceptionComponent->ConfigureSense(*AISenseConfig_Sight); // Tell the perception component to use sight
    EnemyPerceptionComponent->SetDominantSense(UAISense_Sight::StaticClass());
    EnemyPerceptionComponent->OnTargetPerceptionUpdated.AddUniqueDynamic(this, &ADkAIController::OnEnemyPerceptionUpdated);
    SetGenericTeamId(FGenericTeamId(1)); // Hero character: 0, Enemy AI characters: 1
}
References AISenseConfig_Sight, EnemyPerceptionComponent, and OnEnemyPerceptionUpdated().
Member Function Documentation
BeginPlay()
void ADkAIController::BeginPlay () override protected virtual
Called when the game starts or when spawned.
{
    Super::BeginPlay();
    // Configure Detour crowd avoidance
    if (UCrowdFollowingComponent * CrowdPFComp{ Cast<UCrowdFollowingComponent>(GetPathFollowingComponent()) })
    {
        CrowdPFComp->SetCrowdSimulationState(bEnableDetourCrowdAvoidance ? ECrowdSimulationState::Enabled : ECrowdSimulationState::Disabled);
        switch (DetourCrowdAvoidanceQuality)
        {
        case 1: CrowdPFComp->SetCrowdAvoidanceQuality(ECrowdAvoidanceQuality::Low);     break;
        case 2: CrowdPFComp->SetCrowdAvoidanceQuality(ECrowdAvoidanceQuality::Medium);  break;
        case 3: CrowdPFComp->SetCrowdAvoidanceQuality(ECrowdAvoidanceQuality::Good);    break;
        case 4: CrowdPFComp->SetCrowdAvoidanceQuality(ECrowdAvoidanceQuality::High);    break;
        default:
            Debug::Print(TEXT("ADkAIController::BeginPlay: Invalid DetourCrowdAvoidanceQuality value: %d"), DetourCrowdAvoidanceQuality);
            break;
        }
        CrowdPFComp->SetAvoidanceGroup(1);
        CrowdPFComp->SetGroupsToAvoid(1);
        CrowdPFComp->SetCrowdCollisionQueryRange(DetourCrowdCollisionQueryRange);
    }
}
References bEnableDetourCrowdAvoidance, DetourCrowdAvoidanceQuality, DetourCrowdCollisionQueryRange, and Debug::Print().
GetTeamAttitudeTowards()
ETeamAttitude::Type ADkAIController::GetTeamAttitudeTowards (const AActor & Other) const override virtual
Returns the attitude of this AI controller towards another actor, either Hostile or Friendly.
{
    const APawn* PawnToCheck{ Cast<const APawn>(&Other) };
    IGenericTeamAgentInterface* OtherTeamAgent = Cast<IGenericTeamAgentInterface>(PawnToCheck->GetController());
    if (OtherTeamAgent && OtherTeamAgent->GetGenericTeamId() < GetGenericTeamId())
    {
        // Only consider Hero character (team ID 0) as hostile,
        // as we also use other characters for testing (e.g. EQS pawns) and assign them higher team IDs
        return ETeamAttitude::Hostile;
    }
    return ETeamAttitude::Friendly;
}
OnEnemyPerceptionUpdated()
void ADkAIController::OnEnemyPerceptionUpdated (AActor * Actor, FAIStimulus Stimulus) protected virtual
Called when an enemy detects a hostile pawn.
{
    if (UBlackboardComponent * BlackboardComp{ GetBlackboardComponent() })
    {
        if (!BlackboardComp->GetValueAsObject(FName("TargetActor") /* Must match that inside the BB asset */))
        {
            // Only set if not already set
            if (Stimulus.WasSuccessfullySensed() && Actor)
            {
                BlackboardComp->SetValueAsObject(FName("TargetActor") /* Must match that inside the BB asset */, Actor);
            }
        }
    }
}
Referenced by ADkAIController().
Member Data Documentation
AISenseConfig_Sight
TObjectPtr<UAISenseConfig_Sight> ADkAIController::AISenseConfig_Sight protected
Sight configuration for the perception component.
Referenced by ADkAIController().
bEnableDetourCrowdAvoidance
bool ADkAIController::bEnableDetourCrowdAvoidance { true } private
Whether to use Detour crowd avoidance.
{ true };
Referenced by BeginPlay().
DetourCrowdAvoidanceQuality
int32 ADkAIController::DetourCrowdAvoidanceQuality { 4 } private
The quality of Detour crowd avoidance.
{ 4 };
Referenced by BeginPlay().
DetourCrowdCollisionQueryRange
float ADkAIController::DetourCrowdCollisionQueryRange { 600.0f } private
The collision query range for Detour crowd avoidance.
{ 600.0f };
Referenced by BeginPlay().
EnemyPerceptionComponent
TObjectPtr<UAIPerceptionComponent> ADkAIController::EnemyPerceptionComponent protected
Perception component to detect enemies.
Referenced by ADkAIController().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Controllers/DkAIController.h
D:/DkRPG/Source/DkRPG/Controllers/DkAIController.cpp