DkRPG: ADkEnemy Class Reference
ADkEnemy Class Reference
Base class for enemy characters. Blueprint subclasses represent specific enemy types.
#include <DkEnemy.h>
Public Member Functions
ADkEnemy ()
Initializes default values for enemies' properties.
FORCEINLINE UDkEnemyCombatComponent * GetEnemyCombatComponent () const
Getter for the enemy combat component.
FORCEINLINE UBoxComponent * GetLeftHandCollisionBox () const
Getter for the left hand collision box.
FORCEINLINE UBoxComponent * GetRightHandCollisionBox () const
Getter for the right hand collision box.
IDkPawnCombatInterface interface
virtual UDkPawnCombatComponent * GetPawnCombatComponent () const override
Getter for the Pawn Combat Component.
IDkPawnUIInterface interface
virtual UDkPawnUIComponent * GetPawnUIComponent () const override
Getter for the Pawn UI Component.
virtual UDkEnemyUIComponent * GetEnemyUIComponent () const override
Override to return the Enemy UI Component.
Public Member Functions inherited from ADkCharacterBase
ADkCharacterBase ()
FORCEINLINE UDkAbilitySystemComponent * GetDkAbilitySystemComponent () const
Getter for the Ability System Component.
FORCEINLINE UDkAttributeSet * GetDkAttributeSet () const
Getter for the Attribute Set.
virtual UAbilitySystemComponent * GetAbilitySystemComponent () const override
Pure virtual function that must be overridden.
Public Member Functions inherited from IDkPawnUIInterface
virtual UDkHeroUIComponent * GetHeroUIComponent () const
Getter for the Hero UI Component. Returns null if the pawn is not a Hero.
Protected Member Functions
virtual void BeginPlay () override
Called when the game starts or when spawned.
virtual void OnBodyCollisionBeginOverlap (UPrimitiveComponent *OverlappedComp, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
APawn interface
virtual void PossessedBy (AController *NewController) override
Virtual function from ACharacter that must be overridden.
Protected Member Functions inherited from ADkCharacterBase
Protected Attributes
TObjectPtr< UDkEnemyCombatComponent > EnemyCombatComponent
Enemy-specific combat component.
TObjectPtr< UBoxComponent > LeftHandCollisionBox
Collision box for the enemy's right hand.
TObjectPtr< UBoxComponent > RightHandCollisionBox
Collision box for the enemy's left hand.
FName LeftHandCollisionBoxAttachBoneName
Name of the bone/socket to which the left hand collision box is attached.
FName RightHandCollisionBoxAttachBoneName
Name of the bone/socket to which the right hand collision box is attached.
TObjectPtr< UDkEnemyUIComponent > EnemyUIComponent
UI component for handling enemy-specific user interface interactions.
TObjectPtr< UWidgetComponent > EnemyHealthWidgetComponent
Widget component for displaying the enemy's health bar.
Protected Attributes inherited from ADkCharacterBase
TObjectPtr< UDkAbilitySystemComponent > DkAbilitySystemComponent
Ability System Component.
TObjectPtr< UDkAttributeSet > DkAttributeSet
Attribute Set.
TSoftObjectPtr< UDkDataAsset_StartUpDataBase > CharacterStartUpData
Startup data asset for both hero and enemies.
TObjectPtr< UMotionWarpingComponent > MotionWarpingComponent
Motion Warping Component.
Private Member Functions
void InitEnemyStartUpData ()
Helper function to load enemies' data asynchronously.
Detailed Description
Base class for enemy characters. Blueprint subclasses represent specific enemy types.
Constructor & Destructor Documentation
ADkEnemy()
ADkEnemy::ADkEnemy ()
Initializes default values for enemies' properties.
Note
Some properties (MaxWalkSpeed, BrakingDecelerationWalking, etc.) are hard-coded.
{
    // Ensure functional AI upon spawning
    AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;
    // Don't rotate when the controller rotates. Let that just affect the AI logic.
    bUseControllerRotationPitch = false;
    bUseControllerRotationRoll = false;
    bUseControllerRotationYaw = false;
    // Configure character movement
    GetCharacterMovement()->bUseControllerDesiredRotation = false;
    GetCharacterMovement()->bOrientRotationToMovement = true; // Character faces movement direction
    GetCharacterMovement()->RotationRate = FRotator{ 0.f, 180.f, 0.f };
    GetCharacterMovement()->MaxWalkSpeed = 300.f;
    GetCharacterMovement()->BrakingDecelerationWalking = 1000.f;
    EnemyCombatComponent = CreateDefaultSubobject<UDkEnemyCombatComponent>(TEXT("EnemyCombatComponent"));
    EnemyUIComponent = CreateDefaultSubobject<UDkEnemyUIComponent>(TEXT("EnemyUIComponent"));
    EnemyHealthWidgetComponent = CreateDefaultSubobject<UWidgetComponent>(TEXT("EnemyHealthWidgetComponent"));
    EnemyHealthWidgetComponent->SetupAttachment(GetMesh()); // Attach the widget to the enemy's skeletal mesh
    EnemyHealthWidgetComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    // Setup collision boxes for enemy attacks
    LeftHandCollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("LeftHandCollisionBox"));
    LeftHandCollisionBox->SetupAttachment(GetMesh()); // Don't attach to any specific socket by default, as it may vary per enemy type
    LeftHandCollisionBox->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    LeftHandCollisionBox->OnComponentBeginOverlap.AddUniqueDynamic(this, &ADkEnemy::OnBodyCollisionBeginOverlap);
    RightHandCollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("RightHandCollisionBox"));
    RightHandCollisionBox->SetupAttachment(GetMesh()); // Don't attach to any specific socket by default, as it may vary per enemy type
    RightHandCollisionBox->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    RightHandCollisionBox->OnComponentBeginOverlap.AddUniqueDynamic(this, &ADkEnemy::OnBodyCollisionBeginOverlap);
}
References EnemyCombatComponent, EnemyHealthWidgetComponent, EnemyUIComponent, LeftHandCollisionBox, OnBodyCollisionBeginOverlap(), and RightHandCollisionBox.
Member Function Documentation
BeginPlay()
void ADkEnemy::BeginPlay () override protected virtual
Called when the game starts or when spawned.
{
    Super::BeginPlay();
    if (UDkWidgetBase * EnemyHealthWidget{ Cast<UDkWidgetBase>(EnemyHealthWidgetComponent->GetUserWidgetObject()) })
    {
        EnemyHealthWidget->InitEnemyCreateWidget(this);
    }
}
References EnemyHealthWidgetComponent.
GetEnemyCombatComponent()
FORCEINLINE UDkEnemyCombatComponent * ADkEnemy::GetEnemyCombatComponent () const inline
Getter for the enemy combat component.
{ return EnemyCombatComponent; }
References EnemyCombatComponent, and GetEnemyCombatComponent().
Referenced by GetEnemyCombatComponent(), and UDkEnemyGameplayAbility::GetEnemyCombatComponentFromActorInfo().
GetEnemyUIComponent()
UDkEnemyUIComponent * ADkEnemy::GetEnemyUIComponent () const override virtual
Override to return the Enemy UI Component.
Reimplemented from IDkPawnUIInterface.
{
    return EnemyUIComponent;
}
References EnemyUIComponent.
GetLeftHandCollisionBox()
FORCEINLINE UBoxComponent * ADkEnemy::GetLeftHandCollisionBox () const inline
Getter for the left hand collision box.
{ return LeftHandCollisionBox; }
References LeftHandCollisionBox.
Referenced by UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision().
GetPawnCombatComponent()
UDkPawnCombatComponent * ADkEnemy::GetPawnCombatComponent () const override virtual
Getter for the Pawn Combat Component.
Reimplemented from ADkCharacterBase.
{
    return EnemyCombatComponent;
}
References EnemyCombatComponent.
GetPawnUIComponent()
UDkPawnUIComponent * ADkEnemy::GetPawnUIComponent () const override virtual
Getter for the Pawn UI Component.
Reimplemented from ADkCharacterBase.
{
    return EnemyUIComponent;
}
References EnemyUIComponent.
GetRightHandCollisionBox()
FORCEINLINE UBoxComponent * ADkEnemy::GetRightHandCollisionBox () const inline
Getter for the right hand collision box.
{ return RightHandCollisionBox; }
References RightHandCollisionBox.
Referenced by UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision().
InitEnemyStartUpData()
void ADkEnemy::InitEnemyStartUpData () private
Helper function to load enemies' data asynchronously.
{
    if (CharacterStartUpData.IsNull())
    {
        return;
    }
    int32 EnemyApplyLevel{ 1 };
    if (ADkGameModeBase * BaseGameMode{ GetWorld()->GetAuthGameMode<ADkGameModeBase>() })
    {
        switch (BaseGameMode->GetGameDifficultyLevel())
        {
            // The higher the difficulty, the higher the enemy apply level (enemies will be stronger)
            case EDkGameDifficultyLevel::Easy:      EnemyApplyLevel = 1; break;
            case EDkGameDifficultyLevel::Normal:    EnemyApplyLevel = 2; break;
            case EDkGameDifficultyLevel::Hard:      EnemyApplyLevel = 3; break;
            case EDkGameDifficultyLevel::Extreme:   EnemyApplyLevel = 4; break;
            default: break;
        }
    }
    UAssetManager::GetStreamableManager().RequestAsyncLoad(
        CharacterStartUpData.ToSoftObjectPath(),
        FStreamableDelegate::CreateLambda( // When loading is complete, this lambda will be executed
            [this, EnemyApplyLevel]()
            {
                if (UDkDataAsset_StartUpDataBase * LoadedData{ CharacterStartUpData.Get() })
                {
                    LoadedData->GiveToAbilitySystemComponent(DkAbilitySystemComponent, EnemyApplyLevel);
                }
            }));
}
References ADkCharacterBase::CharacterStartUpData, Easy, Extreme, Hard, and Normal.
Referenced by PossessedBy().
OnBodyCollisionBeginOverlap()
void ADkEnemy::OnBodyCollisionBeginOverlap (UPrimitiveComponent * OverlappedComp, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) protected virtual
{
    if (APawn* HitPawn{ Cast<APawn>(OtherActor) })
    {
        if (UDkRPGFunctionLibrary::IsTargetPawnHostile(this, HitPawn))
        {
            EnemyCombatComponent->OnHitTargetActor(HitPawn, SweepResult.ImpactPoint);
        }
    }
}
References EnemyCombatComponent, and UDkRPGFunctionLibrary::IsTargetPawnHostile().
Referenced by ADkEnemy().
PossessedBy()
void ADkEnemy::PossessedBy (AController * NewController) override protected virtual
Virtual function from ACharacter that must be overridden.
Reimplemented from ADkCharacterBase.
{
    Super::PossessedBy(NewController);
    InitEnemyStartUpData();
}
References InitEnemyStartUpData().
Member Data Documentation
EnemyCombatComponent
TObjectPtr<UDkEnemyCombatComponent> ADkEnemy::EnemyCombatComponent protected
Enemy-specific combat component.
Referenced by ADkEnemy(), GetEnemyCombatComponent(), GetPawnCombatComponent(), and OnBodyCollisionBeginOverlap().
EnemyHealthWidgetComponent
TObjectPtr<UWidgetComponent> ADkEnemy::EnemyHealthWidgetComponent protected
Widget component for displaying the enemy's health bar.
Referenced by ADkEnemy(), and BeginPlay().
EnemyUIComponent
TObjectPtr<UDkEnemyUIComponent> ADkEnemy::EnemyUIComponent protected
UI component for handling enemy-specific user interface interactions.
Referenced by ADkEnemy(), GetEnemyUIComponent(), and GetPawnUIComponent().
LeftHandCollisionBox
TObjectPtr<UBoxComponent> ADkEnemy::LeftHandCollisionBox protected
Collision box for the enemy's right hand.
Used for detecting hits during melee attacks, for enemies that don't use weapons.
Referenced by ADkEnemy(), and GetLeftHandCollisionBox().
LeftHandCollisionBoxAttachBoneName
FName ADkEnemy::LeftHandCollisionBoxAttachBoneName protected
Name of the bone/socket to which the left hand collision box is attached.
RightHandCollisionBox
TObjectPtr<UBoxComponent> ADkEnemy::RightHandCollisionBox protected
Collision box for the enemy's left hand.
Used for detecting hits during melee attacks, for enemies that don't use weapons.
Referenced by ADkEnemy(), and GetRightHandCollisionBox().
RightHandCollisionBoxAttachBoneName
FName ADkEnemy::RightHandCollisionBoxAttachBoneName protected
Name of the bone/socket to which the right hand collision box is attached.
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Characters/DkEnemy.h
D:/DkRPG/Source/DkRPG/Characters/DkEnemy.cpp