DkRPG: UDkPawnCombatComponent Class Reference
UDkPawnCombatComponent Class Reference
Base combat component providing shared combat functionality for Hero and enemy characters.
#include <DkPawnCombatComponent.h>
Public Member Functions
void RegisterSpawnedWeapon (FGameplayTag WeaponTag, ADkWeaponBase *SpawnedWeapon, bool bRegisterAsEquippedWeapon=false)
Registers a spawned weapon to the character's carried weapon map and binds hit delegates.
ADkWeaponBase * GetCharacterCarriedWeaponByTag (FGameplayTag WeaponTag) const
Retrieves the weapon currently carried by the character associated with the provided gameplay tag.
ADkWeaponBase * GetCharacterCurrentEquippedWeapon () const
Retrieves the character's currently equipped weapon.
void ToggleWeaponCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType=EDkToggleDamageType::CurrentEquippedWeapon)
Enables or disables weapon collision. Clears OverlappedActors when disabling collision.
virtual void OnHitTargetActor (AActor *HitActor, FVector HitLocation)
Callback when the weapon hits a target actor, actual logic implemented in overriden version.
virtual void OnWeaponPulledFromTargetActor (AActor *InteractedActor)
Callback when the weapon is pulled from a target actor (end hitting), actual logic implemented in overriden version.
Public Attributes
FGameplayTag CurrentEquippedWeaponTag
Automatically set for enemies, but must be set manually for the Hero in blueprint upon equipping/unequipping weapons.
Protected Member Functions
virtual void ToggleCurrentEquippedWeaponCollision (bool bShouldEnableCollision)
Enables or disables collision for the character's currently equipped weapon.
virtual void ToggleBodyCollisionBoxCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType)
Enables or disables collision for the character's body collision boxes (e.g., hands).
Protected Member Functions inherited from UDkPawnExtensionComponentBase
template<class T>
T * GetOwningPawn () const
Gets the owning Pawn cast to the specified type T.
APawn * GetOwningPawn () const
Gets the owning Pawn as an APawn.
template<class T>
T * GetOwningController () const
Gets the controller of the owning Pawn cast to the specified type T.
Protected Attributes
TArray< AActor * > OverlappedActors
Array of actors currently being hit by the character's weapon, to make sure damage is only applied once per attack.
Private Attributes
TMap< FGameplayTag, ADkWeaponBase * > CharacterCarriedWeaponMap
Map of gameplay tags to the weapons currently carried by the character.
Detailed Description
Base combat component providing shared combat functionality for Hero and enemy characters.
Member Function Documentation
GetCharacterCarriedWeaponByTag()
ADkWeaponBase * UDkPawnCombatComponent::GetCharacterCarriedWeaponByTag (FGameplayTag WeaponTag) const
Retrieves the weapon currently carried by the character associated with the provided gameplay tag.
{
    if (CharacterCarriedWeaponMap.Contains(WeaponTag))
    {
        if (ADkWeaponBase* const* FoundWeapon{ CharacterCarriedWeaponMap.Find(WeaponTag) })
        {
            return *FoundWeapon;
        }
    }
    return nullptr;
}
References CharacterCarriedWeaponMap.
Referenced by GetCharacterCurrentEquippedWeapon(), and UDkHeroCombatComponent::GetHeroCarriedWeaponByTag().
GetCharacterCurrentEquippedWeapon()
ADkWeaponBase * UDkPawnCombatComponent::GetCharacterCurrentEquippedWeapon () const
Retrieves the character's currently equipped weapon.
{
    if (!CurrentEquippedWeaponTag.IsValid())
    {
        return nullptr;
    }
    return GetCharacterCarriedWeaponByTag(CurrentEquippedWeaponTag);
}
References CurrentEquippedWeaponTag, and GetCharacterCarriedWeaponByTag().
Referenced by UDkHeroCombatComponent::GetHeroCurrentEquippedWeapon(), and ToggleCurrentEquippedWeaponCollision().
OnHitTargetActor()
void UDkPawnCombatComponent::OnHitTargetActor (AActor * HitActor, FVector HitLocation) virtual
Callback when the weapon hits a target actor, actual logic implemented in overriden version.
Reimplemented in UDkEnemyCombatComponent, and UDkHeroCombatComponent.
{
}
Referenced by RegisterSpawnedWeapon().
OnWeaponPulledFromTargetActor()
void UDkPawnCombatComponent::OnWeaponPulledFromTargetActor (AActor * InteractedActor) virtual
Callback when the weapon is pulled from a target actor (end hitting), actual logic implemented in overriden version.
Reimplemented in UDkEnemyCombatComponent, and UDkHeroCombatComponent.
{
}
Referenced by RegisterSpawnedWeapon().
RegisterSpawnedWeapon()
void UDkPawnCombatComponent::RegisterSpawnedWeapon (FGameplayTag WeaponTag, ADkWeaponBase * SpawnedWeapon, bool bRegisterAsEquippedWeapon = false)
Registers a spawned weapon to the character's carried weapon map and binds hit delegates.
Parameters
WeaponTag The gameplay tag associated with the weapon.
SpawnedWeapon The weapon instance to register.
bRegisterAsEquippedWeapon false when the Hero registers a weapon, true when enemies do as they equip their weapon immediately upon spawning.
{
    checkf(!CharacterCarriedWeaponMap.Contains(WeaponTag), TEXT("Weapon with tag %s is already registered to the character's carried weapon map."), *WeaponTag.ToString());
    checkf(SpawnedWeapon, TEXT("SpawnedWeapon is null. Cannot register a null weapon to the character's carried weapon map."));
    CharacterCarriedWeaponMap.Emplace(WeaponTag, SpawnedWeapon);
    SpawnedWeapon->OnWeaponHitTarget.BindUObject(this, &UDkPawnCombatComponent::OnHitTargetActor);
    SpawnedWeapon->OnWeaponPulledFromTarget.BindUObject(this, &UDkPawnCombatComponent::OnWeaponPulledFromTargetActor);
    if (bRegisterAsEquippedWeapon)
    {
        CurrentEquippedWeaponTag = WeaponTag;
    }
}
References CharacterCarriedWeaponMap, CurrentEquippedWeaponTag, OnHitTargetActor(), ADkWeaponBase::OnWeaponHitTarget, ADkWeaponBase::OnWeaponPulledFromTarget, and OnWeaponPulledFromTargetActor().
ToggleBodyCollisionBoxCollision()
void UDkPawnCombatComponent::ToggleBodyCollisionBoxCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType) protected virtual
Enables or disables collision for the character's body collision boxes (e.g., hands).
Reimplemented in UDkEnemyCombatComponent.
{
}
Referenced by ToggleWeaponCollision().
ToggleCurrentEquippedWeaponCollision()
void UDkPawnCombatComponent::ToggleCurrentEquippedWeaponCollision (bool bShouldEnableCollision) protected virtual
Enables or disables collision for the character's currently equipped weapon.
{
    ADkWeaponBase* CurrentWeapon{ GetCharacterCurrentEquippedWeapon() };
    checkf(CurrentWeapon, TEXT("Current equipped weapon is null. Cannot toggle collision."));
    if (bShouldEnableCollision)
    {
        CurrentWeapon->GetWeaponCollisionBox()->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    }
    else
    {
        CurrentWeapon->GetWeaponCollisionBox()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        OverlappedActors.Empty();
    }
}
References GetCharacterCurrentEquippedWeapon(), ADkWeaponBase::GetWeaponCollisionBox(), and OverlappedActors.
Referenced by ToggleWeaponCollision().
ToggleWeaponCollision()
void UDkPawnCombatComponent::ToggleWeaponCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType = EDkToggleDamageType::CurrentEquippedWeapon)
Enables or disables weapon collision. Clears OverlappedActors when disabling collision.
By default, every weapon's collision is disabled. For only a specific window during an attack animation montage will it be enabled.
{
    if (ToggleDamageType == EDkToggleDamageType::CurrentEquippedWeapon)
    {
        ToggleCurrentEquippedWeaponCollision(bShouldEnableCollision);
    }
    else
    {
        ToggleBodyCollisionBoxCollision(bShouldEnableCollision, ToggleDamageType);
    }
}
References CurrentEquippedWeapon, ToggleBodyCollisionBoxCollision(), and ToggleCurrentEquippedWeaponCollision().
Member Data Documentation
CharacterCarriedWeaponMap
TMap<FGameplayTag, ADkWeaponBase*> UDkPawnCombatComponent::CharacterCarriedWeaponMap private
Map of gameplay tags to the weapons currently carried by the character.
Referenced by GetCharacterCarriedWeaponByTag(), and RegisterSpawnedWeapon().
CurrentEquippedWeaponTag
FGameplayTag UDkPawnCombatComponent::CurrentEquippedWeaponTag
Automatically set for enemies, but must be set manually for the Hero in blueprint upon equipping/unequipping weapons.
Referenced by GetCharacterCurrentEquippedWeapon(), and RegisterSpawnedWeapon().
OverlappedActors
TArray<AActor*> UDkPawnCombatComponent::OverlappedActors protected
Array of actors currently being hit by the character's weapon, to make sure damage is only applied once per attack.
Referenced by UDkEnemyCombatComponent::OnHitTargetActor(), UDkHeroCombatComponent::OnHitTargetActor(), UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision(), and ToggleCurrentEquippedWeaponCollision().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Components/Combat/DkPawnCombatComponent.h
D:/DkRPG/Source/DkRPG/Components/Combat/DkPawnCombatComponent.cpp