DkRPG: UDkRPGFunctionLibrary Class Reference
UDkRPGFunctionLibrary Class Reference
Static helper function library accessible from (1) Blueprints, (2) C++ and (3) both.
#include <DkRPGFunctionLibrary.h>
Static Public Member Functions
static UDkAbilitySystemComponent * NativeGetDkASCFromActor (AActor *Actor)
Retrieves the DkASC from the given Actor.
static bool NativeDoesActorHaveTag (AActor *Actor, FGameplayTag TagToCheck)
Checks whether the given Actor has the specified Gameplay Tag in its DkASC.
static void BP_DoesActorHaveTag (AActor *Actor, FGameplayTag TagToCheck, EDkConfirmType &ConfirmType)
Blueprint wrapper for NativeDoesActorHaveTag.
static void AddGameplayTagToActorIfNone (AActor *InActor, FGameplayTag TagToAdd)
Adds the given Gameplay Tag to the Actor's ASC if it doesn't already have it.
static void RemoveGameplayTagFromActorIfFound (AActor *InActor, FGameplayTag TagToRemove)
Removes the given Gameplay Tag from the Actor's ASC if it has it.
static UDkPawnCombatComponent * NativeGetPawnCombatComponentFromActor (AActor *InActor)
Retrieves the Pawn Combat Component from the given Actor.
static UDkPawnCombatComponent * BP_GetPawnCombatComponentFromActor (AActor *InActor, EDkValidType &ValidType)
Blueprint wrapper for NativeGetPawnCombatComponentFromActor.
static bool IsTargetPawnHostile (APawn *QueryPawn, APawn *TargetPawn)
Checks whether the TargetPawn is hostile towards the QueryPawn.
static float GetScalableFloatValueAtLevel (const FScalableFloat &ScalableFloat, int32 Level=1)
Gets the value of a Scalable Float at the specified level.
static FGameplayTag ComputeHitReactDirectionTag (AActor *Attacker, AActor *Attackee, float &OutAngleDifference)
Computes the hit react direction tag based on the relative position of the Attacker to the Attackee.
static bool IsValidBlock (AActor *Attacker, AActor *Defender)
Determines whether an attack from Attacker to Defender is a valid block.
static bool ApplyGameplayEffectSpecHandleToTargetActor (AActor *InInstigator, AActor *InTargetActor, const FGameplayEffectSpecHandle &InSpecHandle)
Applies the given Gameplay Effect Spec Handle to the Target Actor.
static FText GetDisplayKeyNameFromInputAction (TArray< UInputMappingContext * > InputMappingContexts, UInputAction *InputAction)
Retrieves the display name of the key(s) mapped to the given IA within the specified IMC(s).
static void CountDown (const UObject *WorldContextObject, float TotalTime, float UpdateInterval, float &OutRemainingTime, EDkCountDownActionInput CountDownActionInput, EDkCountDownActionOutput &CountDownActionOutput, FLatentActionInfo LatentInfo)
Performs a countdown over a specified total time, updating at given intervals.
static UDkGameInstance * GetDkGameInstance (const UObject *WorldContextObject)
Retrieves the Game Instance from the given World Context Object.
static void ToggleInputMode (EDkInputMode InInputMode, const UObject *WorldContextObject)
Toggles the input mode.
static void SaveCurrentGameDifficultyLevel (EDkGameDifficultyLevel InDifficultyLevel)
Saves the current game difficulty level to the save game.
static bool TryLoadCurrentGameDifficultyLevel (EDkGameDifficultyLevel &OutDifficultyLevel)
Tries to load the current game difficulty level from the save game.
static int32 GetHeroDefaultInputMappingContextPriority ()
Retrieves the main hero character default IMC priority when applied to the Enhanced Input Subsystem.
Detailed Description
Static helper function library accessible from (1) Blueprints, (2) C++ and (3) both.
Those only used in C++ are prefixed with Native. Those only used in Blueprints are prefixed with BP_.
Member Function Documentation
AddGameplayTagToActorIfNone()
void UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone (AActor * InActor, FGameplayTag TagToAdd) static
Adds the given Gameplay Tag to the Actor's ASC if it doesn't already have it.
{
    UDkAbilitySystemComponent* DkASC = NativeGetDkASCFromActor(InActor);
    if (!DkASC->HasMatchingGameplayTag(TagToAdd))
    {
        DkASC->AddLooseGameplayTag(TagToAdd);
    }
}
References NativeGetDkASCFromActor().
Referenced by UDkAttributeSet::PostGameplayEffectExecute().
ApplyGameplayEffectSpecHandleToTargetActor()
bool UDkRPGFunctionLibrary::ApplyGameplayEffectSpecHandleToTargetActor (AActor * InInstigator, AActor * InTargetActor, const FGameplayEffectSpecHandle & InSpecHandle) static
Applies the given Gameplay Effect Spec Handle to the Target Actor.
Returns
true if the effect was successfully applied; otherwise, false.
{
    UDkAbilitySystemComponent* SourceASC{ NativeGetDkASCFromActor(InInstigator) };
    UDkAbilitySystemComponent* TargetASC{ NativeGetDkASCFromActor(InTargetActor) };
    FActiveGameplayEffectHandle ActiveGameplayEffectHandle{
        SourceASC->ApplyGameplayEffectSpecToTarget(*InSpecHandle.Data.Get(), TargetASC)
    };
    return ActiveGameplayEffectHandle.WasSuccessfullyApplied();
}
References NativeGetDkASCFromActor().
Referenced by ADkProjectile_Base::HandleApplyProjectileDamage().
BP_DoesActorHaveTag()
void UDkRPGFunctionLibrary::BP_DoesActorHaveTag (AActor * Actor, FGameplayTag TagToCheck, EDkConfirmType & ConfirmType) static
Blueprint wrapper for NativeDoesActorHaveTag.
{
    if (NativeDoesActorHaveTag(Actor, TagToCheck))
    {
        ConfirmType = EDkConfirmType::Yes;
    }
    else
    {
        ConfirmType = EDkConfirmType::No;
    }
}
References NativeDoesActorHaveTag(), No, and Yes.
BP_GetPawnCombatComponentFromActor()
UDkPawnCombatComponent * UDkRPGFunctionLibrary::BP_GetPawnCombatComponentFromActor (AActor * InActor, EDkValidType & ValidType) static
Blueprint wrapper for NativeGetPawnCombatComponentFromActor.
{
    UDkPawnCombatComponent* CombatComponent = NativeGetPawnCombatComponentFromActor(InActor);
    if (CombatComponent)
    {
        ValidType = EDkValidType::Valid;
    }
    else
    {
        ValidType = EDkValidType::Invalid;
    }
    return CombatComponent;
}
References Invalid, NativeGetPawnCombatComponentFromActor(), and Valid.
ComputeHitReactDirectionTag()
FGameplayTag UDkRPGFunctionLibrary::ComputeHitReactDirectionTag (AActor * Attacker, AActor * Attackee, float & OutAngleDifference) static
Computes the hit react direction tag based on the relative position of the Attacker to the Attackee.
Also outputs the angle difference in degrees between the Attackee's forward vector and the direction to the Attacker.
{
    checkf(Attacker && Attackee, TEXT("Attacker or Attackee passed to ComputeHitReactDirectionTag is null!"));
    const FVector AttackeeForward{ Attackee->GetActorForwardVector() };
    const FVector AttackeeToAttackerNormalized{ (Attacker->GetActorLocation() - Attackee->GetActorLocation()).GetSafeNormal() };
    const double DotProduct{ FVector::DotProduct(AttackeeForward, AttackeeToAttackerNormalized) };
    OutAngleDifference = UKismetMathLibrary::DegAcos(DotProduct); // always positive => cannot determine left/right
    const FVector CrossProduct{ FVector::CrossProduct(AttackeeForward, AttackeeToAttackerNormalized) }; // order matters
    if (CrossProduct.Z < 0)
    {
        OutAngleDifference = -OutAngleDifference;
    }
    // Determine direction tag based on angle difference
    if (OutAngleDifference >= -45.f && OutAngleDifference <= 45.f)
    {
        return DkGameplayTags::Shared_Status_HitReact_Front;
    }
    else if (OutAngleDifference > 45.f && OutAngleDifference < 135.f)
    {
        return DkGameplayTags::Shared_Status_HitReact_Right;
    }
    else if (OutAngleDifference < -45.f && OutAngleDifference > -135.f)
    {
        return DkGameplayTags::Shared_Status_HitReact_Left;
    }
    else if (OutAngleDifference >= 135.f || OutAngleDifference <= -135.f)
    {
        return DkGameplayTags::Shared_Status_HitReact_Back;
    }
    return FGameplayTag{};
}
CountDown()
void UDkRPGFunctionLibrary::CountDown (const UObject * WorldContextObject, float TotalTime, float UpdateInterval, float & OutRemainingTime, EDkCountDownActionInput CountDownActionInput, EDkCountDownActionOutput & CountDownActionOutput, FLatentActionInfo LatentInfo) static
Performs a countdown over a specified total time, updating at given intervals.
{
    UWorld* World{};
    if (GEngine)
    {
        World = GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::LogAndReturnNull);
    }
    if (!World)
    {
        return;
    }
    FLatentActionManager& LatentActionManager{ World->GetLatentActionManager() };
    FDkCountDownAction* FoundAction{
        LatentActionManager.FindExistingAction<FDkCountDownAction>(LatentInfo.CallbackTarget, LatentInfo.UUID)
    };
    if (CountDownActionInput == EDkCountDownActionInput::Start)
    {
        if (!FoundAction)
        {
            LatentActionManager.AddNewAction(
                LatentInfo.CallbackTarget,
                LatentInfo.UUID,
                new FDkCountDownAction(TotalTime, UpdateInterval, OutRemainingTime, CountDownActionOutput, LatentInfo)
            );
        }
    }
    if (CountDownActionInput == EDkCountDownActionInput::Cancel)
    {
        if (FoundAction)
        {
            FoundAction->CancelAction();
        }
    }
}
References Cancel, FDkCountDownAction::CancelAction(), and Start.
GetDisplayKeyNameFromInputAction()
FText UDkRPGFunctionLibrary::GetDisplayKeyNameFromInputAction (TArray< UInputMappingContext * > InputMappingContexts, UInputAction * InputAction) static
Retrieves the display name of the key(s) mapped to the given IA within the specified IMC(s).
Parameters
InputMappingContexts The list of IMCs to search for mappings to the given IA.
InputAction The IA for which to retrieve the display key name(s).
Returns
Display names for the key(s). Chorded key are placed before the main key, separated by a " + " sign. If no mappings are found, returns "N/A".
Note
If exist multiple mappings for the same main/chorded IA, returns the first one found for each.
{
    FText MainIAKeyName, ChordedIAKeyName;
    for (UInputMappingContext* IMC : InputMappingContexts)
    {
        for (const FEnhancedActionKeyMapping& Mapping : IMC->GetMappings())
        {
            if (Mapping.Action == InputAction) // Main IA found
            {
                // Retrieve key name from chorded action(s) (if any)
                if (Mapping.Triggers.Num() > 0)
                {
                    for (const UInputTrigger* Trigger : Mapping.Triggers)
                    {
                        if (const UInputTriggerChordAction * ChordTrigger{ Cast<UInputTriggerChordAction>(Trigger) }) // Chorded IA found
{
                            UInputAction* ChordAction{ ChordTrigger->ChordAction };
                            for (UInputMappingContext* InnerIMC : InputMappingContexts)
{
                                for (const FEnhancedActionKeyMapping& InnerMapping : InnerIMC->GetMappings())
{
                                    if (InnerMapping.Action == ChordAction)
{
                                        ChordedIAKeyName = InnerMapping.Key.GetDisplayName();
                                        break; // Only consider the first mapping found for the chord action
                                    }
                                }
                            }
                        }
                    }
                }
                // Retrieve key name from main action mapping
                MainIAKeyName = Mapping.Key.GetDisplayName();
                break; // Only consider the first mapping found for the main action
            }
        }
    }
    if (!ChordedIAKeyName.IsEmpty())
    {
        return FText::FromString(ChordedIAKeyName.ToString() + TEXT(" + ") + MainIAKeyName.ToString());
    }
    else if (!MainIAKeyName.IsEmpty())
    {
        return MainIAKeyName;
    }
    else
    {
        return FText::FromString(TEXT("N/A"));
    }
}
GetDkGameInstance()
UDkGameInstance * UDkRPGFunctionLibrary::GetDkGameInstance (const UObject * WorldContextObject) static
Retrieves the Game Instance from the given World Context Object.
{
    if (GEngine)
    {
        if (UWorld * World{ GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::LogAndReturnNull) })
        {
            return World->GetGameInstance<UDkGameInstance>();
        }
    }
    return nullptr;
}
GetHeroDefaultInputMappingContextPriority()
int32 UDkRPGFunctionLibrary::GetHeroDefaultInputMappingContextPriority () static
Retrieves the main hero character default IMC priority when applied to the Enhanced Input Subsystem.
{
    return 0;
}
Referenced by UDkHeroGameplayAbility_TargetLock::InitTargetLockMappingContext(), and ADkHero::SetupPlayerInputComponent().
GetScalableFloatValueAtLevel()
float UDkRPGFunctionLibrary::GetScalableFloatValueAtLevel (const FScalableFloat & ScalableFloat, int32 Level = 1) static
Gets the value of a Scalable Float at the specified level.
{
    return ScalableFloat.GetValueAtLevel(Level);
}
IsTargetPawnHostile()
bool UDkRPGFunctionLibrary::IsTargetPawnHostile (APawn * QueryPawn, APawn * TargetPawn) static
Checks whether the TargetPawn is hostile towards the QueryPawn.
{
    checkf(QueryPawn && TargetPawn, TEXT("QueryPawn or TargetPawn passed to IsTargetPawnHostile is null!"));
    IGenericTeamAgentInterface* QueryTeamAgent{ Cast<IGenericTeamAgentInterface>(QueryPawn->GetController()) };
    IGenericTeamAgentInterface* TargetTeamAgent{ Cast<IGenericTeamAgentInterface>(TargetPawn->GetController()) };
    if (QueryTeamAgent && TargetTeamAgent)
    {
        return QueryTeamAgent->GetGenericTeamId() != TargetTeamAgent->GetGenericTeamId();
    }
    return false;
}
Referenced by UDkGameplayAbility::ApplyGameplayEffectSpecHandleToHitResults(), ADkEnemy::OnBodyCollisionBeginOverlap(), ADkWeaponBase::OnCollisionBoxBeginOverlap(), ADkWeaponBase::OnCollisionBoxEndOverlap(), ADkProjectile_Base::OnProjectileBeginOverlap(), and ADkProjectile_Base::OnProjectileHit().
IsValidBlock()
bool UDkRPGFunctionLibrary::IsValidBlock (AActor * Attacker, AActor * Defender) static
Determines whether an attack from Attacker to Defender is a valid block.
Returns
true when the facing angle between the actors' forward vectors is within 30 degrees.
{
    checkf(Attacker && Defender, TEXT("Attacker or Defender passed to IsValidBlock is null!"));
    const double DotProduct{ FVector::DotProduct(Attacker->GetActorForwardVector(), Defender->GetActorForwardVector()) }; // [-1, 1]
    return DotProduct < -FMath::Cos(FMath::DegreesToRadians(30));
}
Referenced by UDkEnemyCombatComponent::OnHitTargetActor(), and ADkProjectile_Base::OnProjectileHit().
NativeDoesActorHaveTag()
bool UDkRPGFunctionLibrary::NativeDoesActorHaveTag (AActor * Actor, FGameplayTag TagToCheck) static
Checks whether the given Actor has the specified Gameplay Tag in its DkASC.
{
    UDkAbilitySystemComponent* DkASC = NativeGetDkASCFromActor(Actor);
    return DkASC->HasMatchingGameplayTag(TagToCheck);
}
References NativeGetDkASCFromActor().
Referenced by BP_DoesActorHaveTag(), UDkBaseAnimInstance::DoesOwnerHaveTag(), UDkEnemyCombatComponent::OnHitTargetActor(), ADkProjectile_Base::OnProjectileHit(), and UDkHeroGameplayAbility_TargetLock::OnTargetLockTick().
NativeGetDkASCFromActor()
UDkAbilitySystemComponent * UDkRPGFunctionLibrary::NativeGetDkASCFromActor (AActor * Actor) static
Retrieves the DkASC from the given Actor.
{
    checkf(Actor, TEXT("Actor passed to NativeGetDkASCFromActor is null!"));
    return CastChecked<UDkAbilitySystemComponent>(UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(Actor));
}
Referenced by AddGameplayTagToActorIfNone(), ApplyGameplayEffectSpecHandleToTargetActor(), NativeDoesActorHaveTag(), and RemoveGameplayTagFromActorIfFound().
NativeGetPawnCombatComponentFromActor()
UDkPawnCombatComponent * UDkRPGFunctionLibrary::NativeGetPawnCombatComponentFromActor (AActor * InActor) static
Retrieves the Pawn Combat Component from the given Actor.
{
    checkf(InActor, TEXT("Actor passed to NativeGetPawnCombatComponentFromActor is null!"));
    if (IDkPawnCombatInterface* CombatInterface = Cast<IDkPawnCombatInterface>(InActor))
    {
        return CombatInterface->GetPawnCombatComponent();
    }
    return nullptr;
}
Referenced by BP_GetPawnCombatComponentFromActor().
RemoveGameplayTagFromActorIfFound()
void UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound (AActor * InActor, FGameplayTag TagToRemove) static
Removes the given Gameplay Tag from the Actor's ASC if it has it.
{
    UDkAbilitySystemComponent* DkASC = NativeGetDkASCFromActor(InActor);
    if (DkASC->HasMatchingGameplayTag(TagToRemove))
    {
        DkASC->RemoveLooseGameplayTag(TagToRemove);
    }
}
References NativeGetDkASCFromActor().
Referenced by UDkAttributeSet::PostGameplayEffectExecute().
SaveCurrentGameDifficultyLevel()
void UDkRPGFunctionLibrary::SaveCurrentGameDifficultyLevel (EDkGameDifficultyLevel InDifficultyLevel) static
Saves the current game difficulty level to the save game.
{
    USaveGame* SaveGameObj{ UGameplayStatics::CreateSaveGameObject(UDkSaveGame::StaticClass()) };
    if (UDkSaveGame * DkSaveGameObj{ Cast<UDkSaveGame>(SaveGameObj) })
    {
        DkSaveGameObj->SavedCurrentGameDifficultyLevel = InDifficultyLevel;
        const bool bWasSaved{
            UGameplayStatics::SaveGameToSlot(DkSaveGameObj, DkGameplayTags::GameData_SaveGame_Slot_1.GetTag().ToString(), 0)
        };
    }
}
ToggleInputMode()
void UDkRPGFunctionLibrary::ToggleInputMode (EDkInputMode InInputMode, const UObject * WorldContextObject) static
Toggles the input mode.
{
    APlayerController* PC{};
    if (GEngine)
    {
        if (UWorld * World{ GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::LogAndReturnNull) })
        {
            PC = World->GetFirstPlayerController();
        }
    }
    if (!PC)
    {
        return;
    }
    FInputModeGameOnly GameOnlyInputMode;
    FInputModeUIOnly UIOnlyInputMode;
    switch (InInputMode)
    {
    case EDkInputMode::GameOnly:
        PC->SetInputMode(GameOnlyInputMode);
        PC->bShowMouseCursor = false;
        break;
    case EDkInputMode::UIOnly:
        PC->SetInputMode(UIOnlyInputMode);
        PC->bShowMouseCursor = true;
        break;
    default:
        break;
    }
}
References GameOnly, and UIOnly.
TryLoadCurrentGameDifficultyLevel()
bool UDkRPGFunctionLibrary::TryLoadCurrentGameDifficultyLevel (EDkGameDifficultyLevel & OutDifficultyLevel) static
Tries to load the current game difficulty level from the save game.
{
    if (UGameplayStatics::DoesSaveGameExist(DkGameplayTags::GameData_SaveGame_Slot_1.GetTag().ToString(), 0))
    {
        USaveGame* SaveGameObj{ UGameplayStatics::LoadGameFromSlot(DkGameplayTags::GameData_SaveGame_Slot_1.GetTag().ToString(), 0) };
        if (UDkSaveGame* DkSaveGameObj{ Cast<UDkSaveGame>(SaveGameObj) })
        {
            OutDifficultyLevel = DkSaveGameObj->SavedCurrentGameDifficultyLevel;
            return true;
        }
    }
    return false;
}
Referenced by ADkSurvivalGameMode::InitGame().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/DkRPGFunctionLibrary.h
D:/DkRPG/Source/DkRPG/DkRPGFunctionLibrary.cpp