DkRPG: UDkHeroGameplayAbility Class Reference
UDkHeroGameplayAbility Class Reference
Provides hero-specific utility functions. Most hero abilities are Blueprint subclasses of this class.
#include <DkHeroGameplayAbility.h>
Public Member Functions
ADkHero * GetHeroCharacterFromActorInfo ()
Retrieves the hero character from the actor info.
ADkHeroController * GetHeroControllerFromActorInfo ()
Retrieves the hero controller from the actor info.
UDkHeroCombatComponent * GetHeroCombatComponentFromActorInfo ()
Retrieves the hero combat component from the actor info.
UDkHeroUIComponent * GetHeroUIComponentFromActorInfo ()
Retrieves the hero UI component from the actor info.
FGameplayEffectSpecHandle MakeHeroDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, float InBaseDamage, FGameplayTag InAttackTag, int32 CurrentComboCount)
Creates a gameplay effect spec handle for hero damage effects.
FGameplayEffectSpecHandle MakeHeroWeaponAttackStaminaCostEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, FGameplayTag InCurrentAttackTag, float InStaminaCost)
Creates a gameplay effect spec handle for hero weapon attack stamina cost effects.
bool GetAbilityRemainingCooldownByTag (FGameplayTag InCooldownTag, float &TotalCooldownTime, float &RemainingCooldownTime)
Gets the remaining and total cooldown time for an ability by its cooldown tag. Returns true if the ability is still on cooldown.
Private Attributes
TWeakObjectPtr< ADkHero > HeroCharacter
Cached weak pointer to the hero character.
TWeakObjectPtr< ADkHeroController > HeroController
Cached weak pointer to the hero controller.
Additional Inherited Members
Protected Member Functions inherited from UDkGameplayAbility
UDkPawnCombatComponent * GetPawnCombatComponentFromActorInfo () const
Retrieves the pawn's combat component from the actor info.
UDkAbilitySystemComponent * GetDkAbilitySystemComponentFromActorInfo () const
Retrieves the ASC from the actor info.
FActiveGameplayEffectHandle NativeApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle) const
Applies a gameplay effect spec handle to a target actor.
FActiveGameplayEffectHandle BP_ApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle, EDkSuccessType &SuccessType)
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
void ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle &InSpecHandle, const TArray< FHitResult > &InHitResults)
Applies a gameplay effect spec handle to multiple hit results.
void OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount)
Callback when a gameplay tag changes that may cancel this ability.
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
Called right after an ability is given to the ASC.
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData=nullptr) override
Called right before the ability is activated.
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
Called when the ability ends normally or abnormally.
Protected Attributes inherited from UDkGameplayAbility
EDkAbilityActivationPolicy AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered }
Defines the activation policy for this ability.
TMap< FGameplayTag, EDkAbilityCancelTrigger > CancelAbilityTriggers
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Detailed Description
Provides hero-specific utility functions. Most hero abilities are Blueprint subclasses of this class.
Complicated abilities (e.g., target locking) can subclass this class and be implemented in C++.
Member Function Documentation
GetAbilityRemainingCooldownByTag()
bool UDkHeroGameplayAbility::GetAbilityRemainingCooldownByTag (FGameplayTag InCooldownTag, float & TotalCooldownTime, float & RemainingCooldownTime)
Gets the remaining and total cooldown time for an ability by its cooldown tag. Returns true if the ability is still on cooldown.
{
    checkf(InCooldownTag.IsValid(), TEXT("InCooldownTag is invalid in UDkHeroGameplayAbility::GetAbilityRemainingCooldownByTag"));
    TotalCooldownTime = RemainingCooldownTime = 0.f;
    FGameplayEffectQuery CooldownQuery{ FGameplayEffectQuery::MakeQuery_MatchAnyOwningTags(InCooldownTag.GetSingleTagContainer()) };
    TArray<TPair<float, float>> TimeRemainingAndTotalDuration{
        GetDkAbilitySystemComponentFromActorInfo()->GetActiveEffectsTimeRemainingAndDuration(CooldownQuery)
    };
    if (!TimeRemainingAndTotalDuration.IsEmpty())
    {
        RemainingCooldownTime = TimeRemainingAndTotalDuration[0].Key;
        TotalCooldownTime = TimeRemainingAndTotalDuration[0].Value;
    }
    return RemainingCooldownTime > 0.f; // Whether we should resume the cooldown or not
}
References UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo().
GetHeroCharacterFromActorInfo()
ADkHero * UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo ()
Retrieves the hero character from the actor info.
{
    if (!HeroCharacter.IsValid())
    {
        HeroCharacter = Cast<ADkHero>(CurrentActorInfo->AvatarActor);
    }
    return HeroCharacter.IsValid() ? HeroCharacter.Get() : nullptr;
}
References HeroCharacter.
Referenced by UDkHeroGameplayAbility_PickStones::CollectStones(), UDkHeroGameplayAbility_TargetLock::GetAvailableActorsAroundTarget(), UDkHeroGameplayAbility_TargetLock::GetAvailableTargetsToLockOn(), GetHeroCombatComponentFromActorInfo(), GetHeroUIComponentFromActorInfo(), UDkHeroGameplayAbility_TargetLock::GetNearestTargetFromAvailableActors(), UDkHeroGameplayAbility_TargetLock::InitTargetLockMovement(), UDkHeroGameplayAbility_TargetLock::OnTargetLockTick(), and UDkHeroGameplayAbility_TargetLock::ResetTargetLockMovement().
GetHeroCombatComponentFromActorInfo()
UDkHeroCombatComponent * UDkHeroGameplayAbility::GetHeroCombatComponentFromActorInfo ()
Retrieves the hero combat component from the actor info.
{
    return GetHeroCharacterFromActorInfo()->GetHeroCombatComponent();
}
References GetHeroCharacterFromActorInfo(), and ADkHero::GetHeroCombatComponent().
GetHeroControllerFromActorInfo()
ADkHeroController * UDkHeroGameplayAbility::GetHeroControllerFromActorInfo ()
Retrieves the hero controller from the actor info.
{
    if (!HeroController.IsValid())
    {
        HeroController = Cast<ADkHeroController>(CurrentActorInfo->PlayerController);
    }
    return HeroController.IsValid() ? HeroController.Get() : nullptr;
}
References HeroController.
Referenced by UDkHeroGameplayAbility_PickStones::DrawPickUpPromptWidget(), UDkHeroGameplayAbility_TargetLock::DrawTargetLockWidget(), UDkHeroGameplayAbility_TargetLock::InitTargetLockMappingContext(), UDkHeroGameplayAbility_TargetLock::OnTargetLockTick(), UDkHeroGameplayAbility_TargetLock::ResetTargetLockMappingContext(), UDkHeroGameplayAbility_PickStones::SetPickUpPromptWidgetPosition(), and UDkHeroGameplayAbility_TargetLock::SetTargetLockWidgetPosition().
GetHeroUIComponentFromActorInfo()
UDkHeroUIComponent * UDkHeroGameplayAbility::GetHeroUIComponentFromActorInfo ()
Retrieves the hero UI component from the actor info.
{
    return GetHeroCharacterFromActorInfo()->GetHeroUIComponent();
}
References GetHeroCharacterFromActorInfo(), and ADkHero::GetHeroUIComponent().
Referenced by UDkHeroGameplayAbility_PickStones::ActivateAbility(), and UDkHeroGameplayAbility_PickStones::EndAbility().
MakeHeroDamageEffectSpecHandle()
FGameplayEffectSpecHandle UDkHeroGameplayAbility::MakeHeroDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, float InBaseDamage, FGameplayTag InAttackTag, int32 CurrentComboCount)
Creates a gameplay effect spec handle for hero damage effects.
The returned spec handle can be either:
Applied on the enemy character to deal damage, or
Applied on the hero character to heal withered health (no need CurrentComboCount in this case)
Remarks
As for the latter case, as the params' names suggest, the use of this function is not quite semantically appropriate. It is kept this way for code reuse purposes (as both cases are involved in player character dealing damage to enemies), but should it be?
{
    checkf(EffectClass, TEXT("EffectClass is nullptr in UDkHeroGameplayAbility::MakeHeroDamageEffectSpecHandle"));
    FGameplayEffectContextHandle CtxHandle{ GetDkAbilitySystemComponentFromActorInfo()->MakeEffectContext() };
    CtxHandle.SetAbility(this);
    CtxHandle.AddSourceObject(GetAvatarActorFromActorInfo());
    CtxHandle.AddInstigator(GetAvatarActorFromActorInfo(), GetAvatarActorFromActorInfo());
    FGameplayEffectSpecHandle EffectSpecHandle{
        GetDkAbilitySystemComponentFromActorInfo()->MakeOutgoingSpec(EffectClass, GetAbilityLevel(), CtxHandle)
    };
    EffectSpecHandle.Data->SetSetByCallerMagnitude(DkGameplayTags::Shared_SetByCaller_BaseDamage, InBaseDamage);
    if (InAttackTag.IsValid())
    {
        EffectSpecHandle.Data->SetSetByCallerMagnitude(InAttackTag, CurrentComboCount);
    }
    return EffectSpecHandle;
}
References UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo().
MakeHeroWeaponAttackStaminaCostEffectSpecHandle()
FGameplayEffectSpecHandle UDkHeroGameplayAbility::MakeHeroWeaponAttackStaminaCostEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, FGameplayTag InCurrentAttackTag, float InStaminaCost)
Creates a gameplay effect spec handle for hero weapon attack stamina cost effects.
{
    checkf(EffectClass, TEXT("EffectClass is nullptr in UDkHeroGameplayAbility::MakeHeroDamageEffectSpecHandle"));
    FGameplayEffectContextHandle CtxHandle{ GetDkAbilitySystemComponentFromActorInfo()->MakeEffectContext() };
    CtxHandle.SetAbility(this);
    CtxHandle.AddSourceObject(GetAvatarActorFromActorInfo());
    CtxHandle.AddInstigator(GetAvatarActorFromActorInfo(), GetAvatarActorFromActorInfo());
    FGameplayEffectSpecHandle EffectSpecHandle{
        GetDkAbilitySystemComponentFromActorInfo()->MakeOutgoingSpec(EffectClass, GetAbilityLevel(), CtxHandle)
    };
    if (InCurrentAttackTag.IsValid())
    {
        EffectSpecHandle.Data->SetSetByCallerMagnitude(InCurrentAttackTag, InStaminaCost);
    }
    return EffectSpecHandle;
}
References UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo().
Member Data Documentation
HeroCharacter
TWeakObjectPtr<ADkHero> UDkHeroGameplayAbility::HeroCharacter private
Cached weak pointer to the hero character.
Referenced by GetHeroCharacterFromActorInfo().
HeroController
TWeakObjectPtr<ADkHeroController> UDkHeroGameplayAbility::HeroController private
Cached weak pointer to the hero controller.
Referenced by GetHeroControllerFromActorInfo().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility.h
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility.cpp