DkRPG: UDkGameInstance Class Reference
UDkGameInstance Class Reference
The Game Instance class for this game.
#include <DkGameInstance.h>
Public Member Functions
virtual void Init () override
Initializes the game instance.
TSoftObjectPtr< UWorld > GetGameLevelByTag (FGameplayTag LevelTag) const
Retrieves a game level by its associated gameplay tag.
void PushMusic (FGameplayTag MusicTag)
Pushes a music track onto the stack and plays it.
void PopMusic ()
Pops the currently active music track from the stack and returns to the previous one.
void PopAllMusic ()
Pops all music tracks from the stack and stops any currently playing music.
Protected Member Functions
virtual void OnPreLoadMap (const FString &MapName)
Callback for pre-loading a map.
virtual void OnDestinationWorldLoaded (UWorld *LoadedWorld)
Callback for post-loading a map with its world context.
Protected Attributes
TArray< FDkGameLevelSet > GameLevelSet
A collection of game levels available in the game.
TArray< FDkMusicSet > MusicSet
A collection of music assets to be played in the game.
Private Member Functions
void PlayMusicByTag (FGameplayTag MusicTag)
Plays music associated with the given gameplay tag.
void StopMusicByTag (FGameplayTag MusicTag)
Stops music associated with the given gameplay tag.
Private Attributes
TObjectPtr< UAudioComponent > MusicComponent
Cached audio component for the currently playing music track.
TArray< FGameplayTag > MusicStack
A stack of gameplay tags representing the currently active music tracks.
Detailed Description
The Game Instance class for this game.
Responsible for managing game-wide data and functionality, such as level references and music management.
Note
The project needs to be configured to use this class: Project Settings -> Game Instance -> Game Instance Class -> Assign the Blueprint subclass of this class.
Member Function Documentation
GetGameLevelByTag()
TSoftObjectPtr< UWorld > UDkGameInstance::GetGameLevelByTag (FGameplayTag LevelTag) const
Retrieves a game level by its associated gameplay tag.
{
    for (const FDkGameLevelSet& LevelSet : GameLevelSet)
    {
        if (!LevelSet.IsValid())
        {
            continue;
        }
        if (LevelSet.LevelTag == LevelTag)
        {
            return LevelSet.Level;
        }
    }
    return TSoftObjectPtr<UWorld>{};
}
References GameLevelSet.
Init()
void UDkGameInstance::Init () override virtual
Initializes the game instance.
{
    Super::Init();
    FCoreUObjectDelegates::PreLoadMap.AddUObject(this, &UDkGameInstance::OnPreLoadMap);
    FCoreUObjectDelegates::PostLoadMapWithWorld.AddUObject(this, &UDkGameInstance::OnDestinationWorldLoaded);
}
References OnDestinationWorldLoaded(), and OnPreLoadMap().
OnDestinationWorldLoaded()
void UDkGameInstance::OnDestinationWorldLoaded (UWorld * LoadedWorld) protected virtual
Callback for post-loading a map with its world context.
{
    GetMoviePlayer()->StopMovie(); // Close the loading screen
}
Referenced by Init().
OnPreLoadMap()
void UDkGameInstance::OnPreLoadMap (const FString & MapName) protected virtual
Callback for pre-loading a map.
{
    FLoadingScreenAttributes LoadingScreenAttributes;
    LoadingScreenAttributes.bAutoCompleteWhenLoadingCompletes = true;
    LoadingScreenAttributes.MinimumLoadingScreenDisplayTime = 2.f; // Minimum time to display the loading screen
    LoadingScreenAttributes.WidgetLoadingScreen = FLoadingScreenAttributes::NewTestLoadingScreenWidget(); // A simple built-in loading screen widget
    GetMoviePlayer()->SetupLoadingScreen(LoadingScreenAttributes); // Play the loading screen on a different thread
}
Referenced by Init().
PlayMusicByTag()
void UDkGameInstance::PlayMusicByTag (FGameplayTag MusicTag) private
Plays music associated with the given gameplay tag.
{
    if (!MusicTag.IsValid())
    {
        return;
    }
    for (const FDkMusicSet& Entry : MusicSet)
    {
        if (Entry.MusicTag == MusicTag && Entry.Music)
        {
            MusicComponent = UGameplayStatics::SpawnSound2D(this, Entry.Music);
            MusicComponent->bIsUISound = true;
            MusicComponent->FadeIn(Entry.FadeInDuration);
            return;
        }
    }
}
References MusicComponent, and MusicSet.
Referenced by PopMusic(), and PushMusic().
PopAllMusic()
void UDkGameInstance::PopAllMusic ()
Pops all music tracks from the stack and stops any currently playing music.
{
    while (MusicStack.Num() > 0)
    {
        StopMusicByTag(MusicStack.Top());
        MusicStack.Pop();
    }
}
References MusicStack, and StopMusicByTag().
PopMusic()
void UDkGameInstance::PopMusic ()
Pops the currently active music track from the stack and returns to the previous one.
{
    if (MusicStack.Num() > 0)
    {
        StopMusicByTag(MusicStack.Top());
        MusicStack.Pop();
    }
    if (MusicStack.Num() > 0)
    {
        PlayMusicByTag(MusicStack.Top());
    }
}
References MusicStack, PlayMusicByTag(), and StopMusicByTag().
PushMusic()
void UDkGameInstance::PushMusic (FGameplayTag MusicTag)
Pushes a music track onto the stack and plays it.
{
    if (!MusicTag.IsValid())
    {
        return;
    }
    if (MusicStack.Num() > 0)
    {
        StopMusicByTag(MusicStack.Top());
    }
    MusicStack.Push(MusicTag);
    PlayMusicByTag(MusicTag);
}
References MusicStack, PlayMusicByTag(), and StopMusicByTag().
StopMusicByTag()
void UDkGameInstance::StopMusicByTag (FGameplayTag MusicTag) private
Stops music associated with the given gameplay tag.
{
    if (!MusicTag.IsValid())
    {
        return;
    }
    for (const FDkMusicSet& Entry : MusicSet)
    {
        if (Entry.MusicTag == MusicTag && MusicComponent && MusicComponent->Sound == Entry.Music)
        {
            MusicComponent->FadeOut(Entry.FadeOutDuration, 0.f);
            MusicComponent = nullptr;
            return;
        }
    }
}
References MusicComponent, and MusicSet.
Referenced by PopAllMusic(), PopMusic(), and PushMusic().
Member Data Documentation
GameLevelSet
TArray<FDkGameLevelSet> UDkGameInstance::GameLevelSet protected
A collection of game levels available in the game.
Referenced by GetGameLevelByTag().
MusicComponent
TObjectPtr<UAudioComponent> UDkGameInstance::MusicComponent private
Cached audio component for the currently playing music track.
Referenced by PlayMusicByTag(), and StopMusicByTag().
MusicSet
TArray<FDkMusicSet> UDkGameInstance::MusicSet protected
A collection of music assets to be played in the game.
Referenced by PlayMusicByTag(), and StopMusicByTag().
MusicStack
TArray<FGameplayTag> UDkGameInstance::MusicStack private
A stack of gameplay tags representing the currently active music tracks.
This comes in handy when we want to play boss music on top of the regular level music, and then return to the previous track once the boss fight is over.
Referenced by PopAllMusic(), PopMusic(), and PushMusic().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/DkGameInstance.h
D:/DkRPG/Source/DkRPG/DkGameInstance.cpp