DkRPG: UDkHeroCombatComponent Class Reference
UDkHeroCombatComponent Class Reference
Component responsible for handling combat-related functionalities specific to the Hero character.
#include <DkHeroCombatComponent.h>
Public Member Functions
ADkHeroWeapon * GetHeroCarriedWeaponByTag (FGameplayTag InWeaponTag) const
Retrieves the hero's carried weapon that matches the specified gameplay tag.
ADkHeroWeapon * GetHeroCurrentEquippedWeapon () const
Retrieves the hero's currently equipped weapon.
float GetHeroCurrentEquippedWeaponBaseDamageAtLevel (float InLevel) const
Retrieves the base damage of the hero's currently equipped weapon at the specified level.
float GetHeroCurrentEquippedWeaponLightAttackStaminaCostAtLevel (float InLevel) const
Retrieves the attack stamina cost of the hero's currently equipped weapon at the specified level.
float GetHeroCurrentEquippedWeaponHeavyAttackStaminaCostAtLevel (float InLevel) const
Retrieves the heavy attack stamina cost of the hero's currently equipped weapon at the specified level.
virtual void OnHitTargetActor (AActor *HitActor, FVector HitLocation) override
Callback when the hero's weapon hits a target actor.
virtual void OnWeaponPulledFromTargetActor (AActor *InteractedActor) override
Callback when the hero's weapon is pulled from a target actor (end hitting).
Public Member Functions inherited from UDkPawnCombatComponent
void RegisterSpawnedWeapon (FGameplayTag WeaponTag, ADkWeaponBase *SpawnedWeapon, bool bRegisterAsEquippedWeapon=false)
Registers a spawned weapon to the character's carried weapon map and binds hit delegates.
ADkWeaponBase * GetCharacterCarriedWeaponByTag (FGameplayTag WeaponTag) const
Retrieves the weapon currently carried by the character associated with the provided gameplay tag.
ADkWeaponBase * GetCharacterCurrentEquippedWeapon () const
Retrieves the character's currently equipped weapon.
void ToggleWeaponCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType=EDkToggleDamageType::CurrentEquippedWeapon)
Enables or disables weapon collision. Clears OverlappedActors when disabling collision.
Additional Inherited Members
Public Attributes inherited from UDkPawnCombatComponent
FGameplayTag CurrentEquippedWeaponTag
Automatically set for enemies, but must be set manually for the Hero in blueprint upon equipping/unequipping weapons.
Protected Member Functions inherited from UDkPawnCombatComponent
virtual void ToggleCurrentEquippedWeaponCollision (bool bShouldEnableCollision)
Enables or disables collision for the character's currently equipped weapon.
virtual void ToggleBodyCollisionBoxCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType)
Enables or disables collision for the character's body collision boxes (e.g., hands).
Protected Member Functions inherited from UDkPawnExtensionComponentBase
template<class T>
T * GetOwningPawn () const
Gets the owning Pawn cast to the specified type T.
APawn * GetOwningPawn () const
Gets the owning Pawn as an APawn.
template<class T>
T * GetOwningController () const
Gets the controller of the owning Pawn cast to the specified type T.
Protected Attributes inherited from UDkPawnCombatComponent
TArray< AActor * > OverlappedActors
Array of actors currently being hit by the character's weapon, to make sure damage is only applied once per attack.
Detailed Description
Component responsible for handling combat-related functionalities specific to the Hero character.
Member Function Documentation
GetHeroCarriedWeaponByTag()
ADkHeroWeapon * UDkHeroCombatComponent::GetHeroCarriedWeaponByTag (FGameplayTag InWeaponTag) const
Retrieves the hero's carried weapon that matches the specified gameplay tag.
{
    return Cast<ADkHeroWeapon>(GetCharacterCarriedWeaponByTag(InWeaponTag));
}
References UDkPawnCombatComponent::GetCharacterCarriedWeaponByTag().
GetHeroCurrentEquippedWeapon()
ADkHeroWeapon * UDkHeroCombatComponent::GetHeroCurrentEquippedWeapon () const
Retrieves the hero's currently equipped weapon.
{
    return Cast<ADkHeroWeapon>(GetCharacterCurrentEquippedWeapon());
}
References UDkPawnCombatComponent::GetCharacterCurrentEquippedWeapon().
Referenced by GetHeroCurrentEquippedWeaponBaseDamageAtLevel(), GetHeroCurrentEquippedWeaponHeavyAttackStaminaCostAtLevel(), and GetHeroCurrentEquippedWeaponLightAttackStaminaCostAtLevel().
GetHeroCurrentEquippedWeaponBaseDamageAtLevel()
float UDkHeroCombatComponent::GetHeroCurrentEquippedWeaponBaseDamageAtLevel (float InLevel) const
Retrieves the base damage of the hero's currently equipped weapon at the specified level.
{
    return GetHeroCurrentEquippedWeapon()->HeroWeaponData.WeaponBaseDamage.GetValueAtLevel(InLevel);
}
References GetHeroCurrentEquippedWeapon(), ADkHeroWeapon::HeroWeaponData, and FDkHeroWeaponData::WeaponBaseDamage.
GetHeroCurrentEquippedWeaponHeavyAttackStaminaCostAtLevel()
float UDkHeroCombatComponent::GetHeroCurrentEquippedWeaponHeavyAttackStaminaCostAtLevel (float InLevel) const
Retrieves the heavy attack stamina cost of the hero's currently equipped weapon at the specified level.
{
    return GetHeroCurrentEquippedWeapon()->HeroWeaponData.HeavyAttackStaminaCost.GetValueAtLevel(InLevel);
}
References GetHeroCurrentEquippedWeapon(), FDkHeroWeaponData::HeavyAttackStaminaCost, and ADkHeroWeapon::HeroWeaponData.
GetHeroCurrentEquippedWeaponLightAttackStaminaCostAtLevel()
float UDkHeroCombatComponent::GetHeroCurrentEquippedWeaponLightAttackStaminaCostAtLevel (float InLevel) const
Retrieves the attack stamina cost of the hero's currently equipped weapon at the specified level.
{
    return GetHeroCurrentEquippedWeapon()->HeroWeaponData.LightAttackStaminaCost.GetValueAtLevel(InLevel);
}
References GetHeroCurrentEquippedWeapon(), ADkHeroWeapon::HeroWeaponData, and FDkHeroWeaponData::LightAttackStaminaCost.
OnHitTargetActor()
void UDkHeroCombatComponent::OnHitTargetActor (AActor * HitActor, FVector HitLocation) override virtual
Callback when the hero's weapon hits a target actor.
Todo
[RECONSIDER] Only trigger hit pause for heavy attacks (perhaps only upon JumpToFinisher?)
Reimplemented from UDkPawnCombatComponent.
{
    if (OverlappedActors.Contains(HitActor))
    {
        return;
    }
    OverlappedActors.AddUnique(HitActor);
    UDkWeaponHitAdditionalInfo* AdditionalHitInfo{ NewObject<UDkWeaponHitAdditionalInfo>() };
    AdditionalHitInfo->SetHitLocation(HitLocation);
    FGameplayEventData EventData;
    EventData.Instigator = GetOwningPawn();
    EventData.Target = HitActor;
    EventData.OptionalObject = AdditionalHitInfo;
    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
        GetOwningPawn(),
        DkGameplayTags::Shared_Event_MeleeHit,
        EventData
    );
    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
        GetOwningPawn(),
        DkGameplayTags::Player_Event_HitPause,
        FGameplayEventData{} // No data needed for hit pause
    );
}
References UDkPawnExtensionComponentBase::GetOwningPawn(), UDkPawnCombatComponent::OverlappedActors, and UDkWeaponHitAdditionalInfo::SetHitLocation().
OnWeaponPulledFromTargetActor()
void UDkHeroCombatComponent::OnWeaponPulledFromTargetActor (AActor * InteractedActor) override virtual
Callback when the hero's weapon is pulled from a target actor (end hitting).
Todo
[RECONSIDER] Only trigger hit pause for heavy attacks (perhaps only upon JumpToFinisher?)
Reimplemented from UDkPawnCombatComponent.
{
    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
        GetOwningPawn(),
        DkGameplayTags::Player_Event_HitPause,
        FGameplayEventData{} // No data needed for hit pause
    );
}
References UDkPawnExtensionComponentBase::GetOwningPawn().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Components/Combat/DkHeroCombatComponent.h
D:/DkRPG/Source/DkRPG/Components/Combat/DkHeroCombatComponent.cpp