DkRPG: UDkHeroGameplayAbility_PickStones Class Reference
UDkHeroGameplayAbility_PickStones Class Reference
Gameplay Ability that detects nearby stones and displays a pick-up prompt.
#include <DkHeroGameplayAbility_PickStones.h>
Public Member Functions
UDkHeroGameplayAbility_PickStones ()
Setup trigger source for this ability.
Public Member Functions inherited from UDkHeroGameplayAbility
ADkHero * GetHeroCharacterFromActorInfo ()
Retrieves the hero character from the actor info.
ADkHeroController * GetHeroControllerFromActorInfo ()
Retrieves the hero controller from the actor info.
UDkHeroCombatComponent * GetHeroCombatComponentFromActorInfo ()
Retrieves the hero combat component from the actor info.
UDkHeroUIComponent * GetHeroUIComponentFromActorInfo ()
Retrieves the hero UI component from the actor info.
FGameplayEffectSpecHandle MakeHeroDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, float InBaseDamage, FGameplayTag InAttackTag, int32 CurrentComboCount)
Creates a gameplay effect spec handle for hero damage effects.
FGameplayEffectSpecHandle MakeHeroWeaponAttackStaminaCostEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, FGameplayTag InCurrentAttackTag, float InStaminaCost)
Creates a gameplay effect spec handle for hero weapon attack stamina cost effects.
bool GetAbilityRemainingCooldownByTag (FGameplayTag InCooldownTag, float &TotalCooldownTime, float &RemainingCooldownTime)
Gets the remaining and total cooldown time for an ability by its cooldown tag. Returns true if the ability is still on cooldown.
Protected Member Functions
void OnPickUpStoneInteractedTick ()
Called every tick while the ability is active.
void CollectStones ()
Performs multi box trace to detect and store collectible stones. If there's none, cancels the ability.
void ConsumeStones ()
Called upon receiving the Player_Event_Consume_Stones tag.
UGameplayAbility interface
virtual void ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData *TriggerEventData) override
Actually activates the ability.
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
Called when an ability ends normally or abnormally.
Protected Member Functions inherited from UDkGameplayAbility
UDkPawnCombatComponent * GetPawnCombatComponentFromActorInfo () const
Retrieves the pawn's combat component from the actor info.
UDkAbilitySystemComponent * GetDkAbilitySystemComponentFromActorInfo () const
Retrieves the ASC from the actor info.
FActiveGameplayEffectHandle NativeApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle) const
Applies a gameplay effect spec handle to a target actor.
FActiveGameplayEffectHandle BP_ApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle, EDkSuccessType &SuccessType)
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
void ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle &InSpecHandle, const TArray< FHitResult > &InHitResults)
Applies a gameplay effect spec handle to multiple hit results.
void OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount)
Callback when a gameplay tag changes that may cancel this ability.
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
Called right after an ability is given to the ASC.
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData=nullptr) override
Called right before the ability is activated.
Private Member Functions
void DrawPickUpPromptWidget ()
Draws the pick-up prompt widget on the hero's HUD.
void SetPickUpPromptWidgetPosition ()
Adjusts the pick-up prompt widget's position based on the current pick-up stone location.
void CancelPickUpStonesAbility ()
Calls the parent ability's CancelAbility function to end this ability.
void CleanUp ()
Cleans up any movement and UI state related to this ability.
Private Attributes
float CollectTraceDistance { 50.f }
Distance for box trace when collecting.
FVector CollectTraceBoxSize { 100.f }
Size of the box for box trace when collecting.
TArray< TEnumAsByte< EObjectTypeQuery > > StoneTraceChannel
Trace channels to consider when collecting stones.
bool bDrawDebugTraces { }
Whether to draw persistent debug traces for collecting stones.
TArray< ADkPickUpStoneBase * > CollectedStones
Collected stones during ability activation.
TSubclassOf< UDkWidgetBase > PickUpPromptWidgetClass
The widget class used to display the pickup prompt UI.
TObjectPtr< UDkWidgetBase > DrawnPickUpPromptWidget { }
The instance of the drawn pick-up prompt widget.
FVector2D PickUpPromptWidgetSize { FVector2D::ZeroVector }
The size of the pick-up prompt widget, used to offset its position correctly when added to viewport.
FVector PickUpStoneLocation
Location of the pick-up stone interacted with.
Additional Inherited Members
Protected Attributes inherited from UDkGameplayAbility
EDkAbilityActivationPolicy AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered }
Defines the activation policy for this ability.
TMap< FGameplayTag, EDkAbilityCancelTrigger > CancelAbilityTriggers
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Detailed Description
Gameplay Ability that detects nearby stones and displays a pick-up prompt.
Constructor & Destructor Documentation
UDkHeroGameplayAbility_PickStones()
UDkHeroGameplayAbility_PickStones::UDkHeroGameplayAbility_PickStones ()
Setup trigger source for this ability.
Note
Other GAs do this in Blueprint. We only do this one differently to add a little taste of difference.
{
    FAbilityTriggerData PickUpStonesAbilityTrigger;
    PickUpStonesAbilityTrigger.TriggerTag = DkGameplayTags::Player_Ability_PickUp_Stones;
    PickUpStonesAbilityTrigger.TriggerSource = EGameplayAbilityTriggerSource::GameplayEvent;
    AbilityTriggers.Add(PickUpStonesAbilityTrigger);
}
Member Function Documentation
ActivateAbility()
void UDkHeroGameplayAbility_PickStones::ActivateAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, const FGameplayEventData * TriggerEventData) override protected virtual
Actually activates the ability.
{
    UObject* PickUpItemInfo{ TriggerEventData ? TriggerEventData->OptionalObject : nullptr };
    UDkPickUpItemInteractedAdditionalInfo* PickUpItemLocationInfo{ Cast<UDkPickUpItemInteractedAdditionalInfo>(PickUpItemInfo) };
    PickUpStoneLocation = PickUpItemLocationInfo ? PickUpItemLocationInfo->GetPickUpItemLocation() : FVector::ZeroVector;
    GetHeroUIComponentFromActorInfo()->OnPickUpStoneInteracted.Broadcast(
        true, // Show input key prompt accordingly
        PickUpItemLocationInfo ? PickUpItemLocationInfo->GetPickUpItemLocation() : FVector::ZeroVector
    );
    DrawPickUpPromptWidget();
    Super::ActivateAbility(Handle, ActorInfo, ActivationInfo, TriggerEventData);
}
References DrawPickUpPromptWidget(), UDkHeroGameplayAbility::GetHeroUIComponentFromActorInfo(), UDkPickUpItemInteractedAdditionalInfo::GetPickUpItemLocation(), UDkHeroUIComponent::OnPickUpStoneInteracted, and PickUpStoneLocation.
CancelPickUpStonesAbility()
void UDkHeroGameplayAbility_PickStones::CancelPickUpStonesAbility () private
Calls the parent ability's CancelAbility function to end this ability.
{
    CancelAbility(
        GetCurrentAbilitySpecHandle(),
        GetCurrentActorInfo(),
        GetCurrentActivationInfo(),
        true /* bReplicateCancelAbility */
    );
}
Referenced by SetPickUpPromptWidgetPosition().
CleanUp()
void UDkHeroGameplayAbility_PickStones::CleanUp () private
Cleans up any movement and UI state related to this ability.
{
    CollectedStones.Empty();
    if (DrawnPickUpPromptWidget)
    {
        DrawnPickUpPromptWidget->RemoveFromParent();
    }
    DrawnPickUpPromptWidget = nullptr;
    PickUpPromptWidgetSize = FVector2D::ZeroVector;
    PickUpStoneLocation = FVector::ZeroVector;
}
References CollectedStones, DrawnPickUpPromptWidget, PickUpPromptWidgetSize, and PickUpStoneLocation.
Referenced by EndAbility().
CollectStones()
void UDkHeroGameplayAbility_PickStones::CollectStones () protected
Performs multi box trace to detect and store collectible stones. If there's none, cancels the ability.
Multiple stones can be collected at once if they are within the trace area.
{
    CollectedStones.Empty(); // Refresh collected stones
    ADkHero* Hero{ GetHeroCharacterFromActorInfo() };
    FVector HeroDownVector{ -Hero->GetActorUpVector() };
    TArray<FHitResult> TraceHitResults;
    UKismetSystemLibrary::BoxTraceMultiForObjects(
        Hero,                                                                    // World Context Object
        Hero->GetActorLocation(),                                                // Start
        Hero->GetActorLocation() + HeroDownVector * CollectTraceDistance,        // End
        CollectTraceBoxSize / 2.f,                                               // Half Size
        HeroDownVector.ToOrientationRotator(),                                   // Orientation
        StoneTraceChannel,                                                       // Object Types
        false,                                                                   // bTraceComplex
        TArray<AActor*>(),                                                       // Actors to ignore
        bDrawDebugTraces ? EDrawDebugTrace::ForOneFrame : EDrawDebugTrace::None, // Draw Debug Type
        TraceHitResults,                                                         // Out Hit Results
        true                                                                     // bIgnoreSelf
    );
    for (const FHitResult& HitResult : TraceHitResults)
    {
        if (ADkPickUpStoneBase* PickUpStone{ Cast<ADkPickUpStoneBase>(HitResult.GetActor()) })
        {
            CollectedStones.AddUnique(PickUpStone);
        }
    }
    if (CollectedStones.IsEmpty())
    {
        CancelAbility(GetCurrentAbilitySpecHandle(), GetCurrentActorInfo(), GetCurrentActivationInfo(), true);
    }
}
References bDrawDebugTraces, CollectedStones, CollectTraceBoxSize, CollectTraceDistance, UDkHeroGameplayAbility::GetHeroCharacterFromActorInfo(), and StoneTraceChannel.
Referenced by OnPickUpStoneInteractedTick().
ConsumeStones()
void UDkHeroGameplayAbility_PickStones::ConsumeStones () protected
Called upon receiving the Player_Event_Consume_Stones tag.
{
    if (CollectedStones.IsEmpty())
    {
        CancelAbility(GetCurrentAbilitySpecHandle(), GetCurrentActorInfo(), GetCurrentActivationInfo(), true);
        return;
    }
    for (ADkPickUpStoneBase* Stone : CollectedStones)
    {
        if (Stone)
        {
            Stone->Consume(GetDkAbilitySystemComponentFromActorInfo(), GetAbilityLevel());
        }
    }
}
References CollectedStones, and UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo().
DrawPickUpPromptWidget()
void UDkHeroGameplayAbility_PickStones::DrawPickUpPromptWidget () private
Draws the pick-up prompt widget on the hero's HUD.
{
    if (DrawnPickUpPromptWidget)
    {
        // The ability is currently active, and the widget is already drawn
        return;
    }
    checkf(PickUpPromptWidgetClass, TEXT("Forgot to assign a valid PickUpPromptWidgetClass in %s 's Blueprint"), *GetName());
    DrawnPickUpPromptWidget = CreateWidget<UDkWidgetBase>(
        GetHeroControllerFromActorInfo(), // `ACharacter` cannot be the owning player
        PickUpPromptWidgetClass
    );
    checkf(DrawnPickUpPromptWidget, TEXT("Failed to create PickUp Prompt Widget in %s 's Blueprint"), *GetName());
    DrawnPickUpPromptWidget->AddToViewport();
}
References DrawnPickUpPromptWidget, UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), and PickUpPromptWidgetClass.
Referenced by ActivateAbility().
EndAbility()
void UDkHeroGameplayAbility_PickStones::EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override protected virtual
Called when an ability ends normally or abnormally.
Reimplemented from UDkGameplayAbility.
{
    GetHeroUIComponentFromActorInfo()->OnPickUpStoneInteracted.Broadcast(
        false,              // Hide input key prompt accordingly
        FVector::ZeroVector // No need location when hiding
    );
    CleanUp();
    Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
}
References CleanUp(), UDkHeroGameplayAbility::GetHeroUIComponentFromActorInfo(), and UDkHeroUIComponent::OnPickUpStoneInteracted.
OnPickUpStoneInteractedTick()
void UDkHeroGameplayAbility_PickStones::OnPickUpStoneInteractedTick () protected
Called every tick while the ability is active.
{
    CollectStones();
    SetPickUpPromptWidgetPosition();
}
References CollectStones(), and SetPickUpPromptWidgetPosition().
SetPickUpPromptWidgetPosition()
void UDkHeroGameplayAbility_PickStones::SetPickUpPromptWidgetPosition () private
Adjusts the pick-up prompt widget's position based on the current pick-up stone location.
If there are multiple stones being collected, the widget will be positioned based on the location of the first stone in CollectedStones, which is determined by the order of hits from the box trace in CollectStones().
Warning
This assumes that the root widget is a USizeBox
{
    if (!DrawnPickUpPromptWidget)
    {
        CancelPickUpStonesAbility();
        return;
    }
    FVector2D ScreenPosition{};
    UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(
        GetHeroControllerFromActorInfo(), // Player Controller
        PickUpStoneLocation,              // World Location
        ScreenPosition,                   // Out Screen Position
        true                              // bPlayerViewportRelative
    );
    if (PickUpPromptWidgetSize == FVector2D::ZeroVector) // Only need to do this once
    {
        DrawnPickUpPromptWidget->WidgetTree->ForEachWidget(
            [this](UWidget* InWidget)
            {
                if (USizeBox * FoundSizeBox{ Cast<USizeBox>(InWidget) })
                {
                    PickUpPromptWidgetSize.X = FoundSizeBox->GetWidthOverride();
                    PickUpPromptWidgetSize.Y = FoundSizeBox->GetHeightOverride();
                }
            }
        );
    }
    ScreenPosition -= (PickUpPromptWidgetSize / 2.f); // Center the widget on the target
    DrawnPickUpPromptWidget->SetPositionInViewport(
        ScreenPosition,
        false // already taken as viewport relative when passing `true` to `ProjectWorldLocationToWidgetPosition` above
    );
}
References CancelPickUpStonesAbility(), DrawnPickUpPromptWidget, UDkHeroGameplayAbility::GetHeroControllerFromActorInfo(), PickUpPromptWidgetSize, and PickUpStoneLocation.
Referenced by OnPickUpStoneInteractedTick().
Member Data Documentation
bDrawDebugTraces
bool UDkHeroGameplayAbility_PickStones::bDrawDebugTraces { } private
Whether to draw persistent debug traces for collecting stones.
{ };
Referenced by CollectStones().
CollectedStones
TArray<ADkPickUpStoneBase*> UDkHeroGameplayAbility_PickStones::CollectedStones private
Collected stones during ability activation.
Referenced by CleanUp(), CollectStones(), and ConsumeStones().
CollectTraceBoxSize
FVector UDkHeroGameplayAbility_PickStones::CollectTraceBoxSize { 100.f } private
Size of the box for box trace when collecting.
{ 100.f };
Referenced by CollectStones().
CollectTraceDistance
float UDkHeroGameplayAbility_PickStones::CollectTraceDistance { 50.f } private
Distance for box trace when collecting.
{ 50.f };
Referenced by CollectStones().
DrawnPickUpPromptWidget
TObjectPtr<UDkWidgetBase> UDkHeroGameplayAbility_PickStones::DrawnPickUpPromptWidget { } private
The instance of the drawn pick-up prompt widget.
{ };
Referenced by CleanUp(), DrawPickUpPromptWidget(), and SetPickUpPromptWidgetPosition().
PickUpPromptWidgetClass
TSubclassOf<UDkWidgetBase> UDkHeroGameplayAbility_PickStones::PickUpPromptWidgetClass private
The widget class used to display the pickup prompt UI.
Referenced by DrawPickUpPromptWidget().
PickUpPromptWidgetSize
FVector2D UDkHeroGameplayAbility_PickStones::PickUpPromptWidgetSize { FVector2D::ZeroVector } private
The size of the pick-up prompt widget, used to offset its position correctly when added to viewport.
{ FVector2D::ZeroVector };
Referenced by CleanUp(), and SetPickUpPromptWidgetPosition().
PickUpStoneLocation
FVector UDkHeroGameplayAbility_PickStones::PickUpStoneLocation private
Location of the pick-up stone interacted with.
This is passed from ADkPickUpStoneBase::OnPickUpSphereBeginOverlap to here via the optional payload of FGameplayEventData that triggers this ability.
Referenced by ActivateAbility(), CleanUp(), and SetPickUpPromptWidgetPosition().
StoneTraceChannel
TArray<TEnumAsByte<EObjectTypeQuery> > UDkHeroGameplayAbility_PickStones::StoneTraceChannel private
Trace channels to consider when collecting stones.
Referenced by CollectStones().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility_PickStones.h
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkHeroGameplayAbility_PickStones.cpp