DkRPG: UDkEnemyGameplayAbility Class Reference
UDkEnemyGameplayAbility Class Reference
Gameplay Ability class used for enemy-specific abilities.
#include <DkEnemyGameplayAbility.h>
Public Member Functions
ADkEnemy * GetEnemyCharacterFromActorInfo ()
Retrieves the enemy character from the actor info.
UDkEnemyCombatComponent * GetEnemyCombatComponentFromActorInfo ()
Retrieves the enemy combat component from the actor info.
FGameplayEffectSpecHandle MakeEnemyDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, const FScalableFloat &InDamageScalableFloat, EDkEnemyAttackStatus InEnemyAttackStatus)
Creates a gameplay effect spec handle for enemy damage effects.
Private Attributes
TWeakObjectPtr< ADkEnemy > CachedEnemyCharacter
Cached pointer to the enemy character.
Additional Inherited Members
Protected Member Functions inherited from UDkGameplayAbility
UDkPawnCombatComponent * GetPawnCombatComponentFromActorInfo () const
Retrieves the pawn's combat component from the actor info.
UDkAbilitySystemComponent * GetDkAbilitySystemComponentFromActorInfo () const
Retrieves the ASC from the actor info.
FActiveGameplayEffectHandle NativeApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle) const
Applies a gameplay effect spec handle to a target actor.
FActiveGameplayEffectHandle BP_ApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle, EDkSuccessType &SuccessType)
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
void ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle &InSpecHandle, const TArray< FHitResult > &InHitResults)
Applies a gameplay effect spec handle to multiple hit results.
void OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount)
Callback when a gameplay tag changes that may cancel this ability.
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
Called right after an ability is given to the ASC.
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData=nullptr) override
Called right before the ability is activated.
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
Called when the ability ends normally or abnormally.
Protected Attributes inherited from UDkGameplayAbility
EDkAbilityActivationPolicy AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered }
Defines the activation policy for this ability.
TMap< FGameplayTag, EDkAbilityCancelTrigger > CancelAbilityTriggers
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Detailed Description
Gameplay Ability class used for enemy-specific abilities.
Member Function Documentation
GetEnemyCharacterFromActorInfo()
ADkEnemy * UDkEnemyGameplayAbility::GetEnemyCharacterFromActorInfo ()
Retrieves the enemy character from the actor info.
{
    if (!CachedEnemyCharacter.IsValid())
    {
        CachedEnemyCharacter = Cast<ADkEnemy>(CurrentActorInfo->AvatarActor);
    }
    return CachedEnemyCharacter.IsValid() ? CachedEnemyCharacter.Get() : nullptr;
}
References CachedEnemyCharacter.
Referenced by GetEnemyCombatComponentFromActorInfo().
GetEnemyCombatComponentFromActorInfo()
UDkEnemyCombatComponent * UDkEnemyGameplayAbility::GetEnemyCombatComponentFromActorInfo ()
Retrieves the enemy combat component from the actor info.
{
    return GetEnemyCharacterFromActorInfo()->GetEnemyCombatComponent();
}
References GetEnemyCharacterFromActorInfo(), and ADkEnemy::GetEnemyCombatComponent().
MakeEnemyDamageEffectSpecHandle()
FGameplayEffectSpecHandle UDkEnemyGameplayAbility::MakeEnemyDamageEffectSpecHandle (TSubclassOf< UGameplayEffect > EffectClass, const FScalableFloat & InDamageScalableFloat, EDkEnemyAttackStatus InEnemyAttackStatus)
Creates a gameplay effect spec handle for enemy damage effects.
{
    checkf(EffectClass, TEXT("EffectClass must be valid when creating an enemy damage effect spec handle."));
    FGameplayEffectContextHandle CtxHandle{ GetDkAbilitySystemComponentFromActorInfo()->MakeEffectContext() };
    CtxHandle.SetAbility(this);
    CtxHandle.AddSourceObject(GetAvatarActorFromActorInfo());
    CtxHandle.AddInstigator(GetAvatarActorFromActorInfo(), GetAvatarActorFromActorInfo());
    FGameplayEffectSpecHandle EffectSpecHandle{
        GetDkAbilitySystemComponentFromActorInfo()->MakeOutgoingSpec(EffectClass, GetAbilityLevel(), CtxHandle)
    };
    // Pass information about Base Damage
    EffectSpecHandle.Data->SetSetByCallerMagnitude(
        DkGameplayTags::Shared_SetByCaller_BaseDamage,
        InDamageScalableFloat.GetValueAtLevel(GetAbilityLevel())
    );
    // Pass information about whether the target (Player character) is blocking
    if (InEnemyAttackStatus == EDkEnemyAttackStatus::BeingBlocked)
    {
        EffectSpecHandle.Data->SetSetByCallerMagnitude(
            DkGameplayTags::Enemy_SetByCaller_AttackStatus,
            static_cast<int>(EDkEnemyAttackStatus::BeingBlocked)
        );
    }
    else if (InEnemyAttackStatus == EDkEnemyAttackStatus::SuccessfullyBlocked)
    {
        EffectSpecHandle.Data->SetSetByCallerMagnitude(
            DkGameplayTags::Enemy_SetByCaller_AttackStatus,
            static_cast<int>(EDkEnemyAttackStatus::SuccessfullyBlocked)
        );
    }
    return EffectSpecHandle;
}
References BeingBlocked, UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo(), and SuccessfullyBlocked.
Member Data Documentation
CachedEnemyCharacter
TWeakObjectPtr<ADkEnemy> UDkEnemyGameplayAbility::CachedEnemyCharacter private
Cached pointer to the enemy character.
Referenced by GetEnemyCharacterFromActorInfo().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkEnemyGameplayAbility.h
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkEnemyGameplayAbility.cpp