DkRPG: ADkProjectile_Base Class Reference
ADkProjectile_Base Class Reference
Base class for all projectiles in the game, used by both player and enemy characters.
#include <DkProjectile_Base.h>
Public Member Functions
ADkProjectile_Base ()
Protected Member Functions
virtual void BeginPlay () override
virtual void OnProjectileHit (UPrimitiveComponent *HitComp, AActor *OtherActor, UPrimitiveComponent *OtherComp, FVector NormalImpulse, const FHitResult &Hit)
Callback when the projectile hits another actor.
virtual void OnProjectileBeginOverlap (UPrimitiveComponent *OverlappedComp, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
Callback when the projectile begins overlapping with another actor.
void BP_OnSpawnProjectileHitFX (const FVector &HitLocation)
Protected Attributes
TObjectPtr< UBoxComponent > ProjectileCollisionBox
Collision box for the projectile.
TObjectPtr< UNiagaraComponent > ProjectileNiagaraComponent
Visual representation of the projectile.
TObjectPtr< UProjectileMovementComponent > ProjectileMovementComponent
Movement component for handling projectile movement.
EProjectileDamagePolicy ProjectileDamagePolicy { EProjectileDamagePolicy::OnHit }
Damage policy for the projectile.
FGameplayEffectSpecHandle ProjectileDamageEffectSpecHandle
Gameplay effect spec handle for the projectile's damage effect.
Private Member Functions
void HandleApplyProjectileDamage (APawn *HitPawn, const FGameplayEventData &InPayload)
Applies projectile damage to the hit pawn via the ProjectileDamageEffectSpecHandle.
Private Attributes
TArray< AActor * > OverlappedActors
List of actors that have already been damaged by this projectile, avoids multiple damage applications on a same actor.
Detailed Description
Base class for all projectiles in the game, used by both player and enemy characters.
Note
Decide whether or not the projectile can pierce through multiple targets via ProjectileDamagePolicy:
EProjectileDamagePolicy::OnHit: explodes upon contacting 1st target
EProjectileDamagePolicy::OnBeginOverlap: persists through multiple targets
Constructor & Destructor Documentation
ADkProjectile_Base()
ADkProjectile_Base::ADkProjectile_Base ()
{
    PrimaryActorTick.bCanEverTick = false;
    ProjectileCollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("ProjectileCollisionBox"));
    SetRootComponent(ProjectileCollisionBox);
    ProjectileCollisionBox->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    ProjectileCollisionBox->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);
    ProjectileCollisionBox->SetCollisionResponseToChannel(ECC_WorldDynamic, ECR_Block);
    ProjectileCollisionBox->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Block);
    ProjectileCollisionBox->OnComponentHit.AddUniqueDynamic(this, &ADkProjectile_Base::OnProjectileHit);
    ProjectileCollisionBox->OnComponentBeginOverlap.AddDynamic(this, &ADkProjectile_Base::OnProjectileBeginOverlap);
    ProjectileNiagaraComponent = CreateDefaultSubobject<UNiagaraComponent>(TEXT("ProjectileNiagaraComponent"));
    ProjectileNiagaraComponent->SetupAttachment(GetRootComponent());
    ProjectileMovementComponent = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovementComponent"));
    ProjectileMovementComponent->InitialSpeed = 600.f;
    ProjectileMovementComponent->MaxSpeed = 600.f;
    ProjectileMovementComponent->Velocity = FVector{ 1.f,0.f,0.f };
    ProjectileMovementComponent->ProjectileGravityScale = 0.f; // No gravity
    InitialLifeSpan = 4.f;
}
References OnProjectileBeginOverlap(), OnProjectileHit(), ProjectileCollisionBox, ProjectileMovementComponent, and ProjectileNiagaraComponent.
Member Function Documentation
BeginPlay()
void ADkProjectile_Base::BeginPlay () override protected virtual
{
    Super::BeginPlay();
    if (ProjectileDamagePolicy == EProjectileDamagePolicy::OnBeginOverlap)
    {
        ProjectileCollisionBox->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap); // Allow OnBeginOverlap events with Pawns
    }
}
References OnBeginOverlap, ProjectileCollisionBox, and ProjectileDamagePolicy.
BP_OnSpawnProjectileHitFX()
void ADkProjectile_Base::BP_OnSpawnProjectileHitFX (const FVector & HitLocation) protected
References BP_OnSpawnProjectileHitFX(), and HandleApplyProjectileDamage().
Referenced by BP_OnSpawnProjectileHitFX(), and OnProjectileHit().
HandleApplyProjectileDamage()
void ADkProjectile_Base::HandleApplyProjectileDamage (APawn * HitPawn, const FGameplayEventData & InPayload) private
Applies projectile damage to the hit pawn via the ProjectileDamageEffectSpecHandle.
{
    checkf(ProjectileDamageEffectSpecHandle.IsValid(), TEXT("Forgot to assign ProjectileDamageEffectSpecHandle on %s!"), *GetActorNameOrLabel());
    const bool bWasApplied { UDkRPGFunctionLibrary::ApplyGameplayEffectSpecHandleToTargetActor(
        GetInstigator(), HitPawn, ProjectileDamageEffectSpecHandle)
    };
    if (bWasApplied &&
        ProjectileDamageEffectSpecHandle.Data->GetSetByCallerMagnitude(DkGameplayTags::Enemy_SetByCaller_AttackStatus)
        == static_cast<int>(EDkEnemyAttackStatus::DealtDamage))
    {
        UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(HitPawn, DkGameplayTags::Shared_Event_HitReact, InPayload);
    }
}
References UDkRPGFunctionLibrary::ApplyGameplayEffectSpecHandleToTargetActor(), DealtDamage, and ProjectileDamageEffectSpecHandle.
Referenced by BP_OnSpawnProjectileHitFX(), OnProjectileBeginOverlap(), and OnProjectileHit().
OnProjectileBeginOverlap()
void ADkProjectile_Base::OnProjectileBeginOverlap (UPrimitiveComponent * OverlappedComp, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) protected virtual
Callback when the projectile begins overlapping with another actor.
{
    if (OverlappedActors.Contains(OtherActor))
    {
        return; // Already damaged this actor
    }
    OverlappedActors.AddUnique(OtherActor);
    if (APawn * HitPawn{ Cast<APawn>(OtherActor) })
    {
        FGameplayEventData EventData;
        EventData.Instigator = GetInstigator();
        EventData.Target = HitPawn;
        if (UDkRPGFunctionLibrary::IsTargetPawnHostile(GetInstigator(), HitPawn))
        {
            HandleApplyProjectileDamage(HitPawn, EventData);
        }
    }
}
References HandleApplyProjectileDamage(), UDkRPGFunctionLibrary::IsTargetPawnHostile(), and OverlappedActors.
Referenced by ADkProjectile_Base().
OnProjectileHit()
void ADkProjectile_Base::OnProjectileHit (UPrimitiveComponent * HitComp, AActor * OtherActor, UPrimitiveComponent * OtherComp, FVector NormalImpulse, const FHitResult & Hit) protected virtual
Callback when the projectile hits another actor.
{
    BP_OnSpawnProjectileHitFX(Hit.ImpactPoint);
    APawn* HitPawn{ Cast<APawn>(OtherActor) };
    ADkCharacterBase* HitCharacter{ Cast<ADkCharacterBase>(OtherActor) };
    if (!HitPawn || !UDkRPGFunctionLibrary::IsTargetPawnHostile(GetInstigator(), HitPawn))
    {
        Destroy();
        return;
    }
    bool bIsValidBlock{};
    const bool bIsPlayerBlocking{ UDkRPGFunctionLibrary::NativeDoesActorHaveTag(HitPawn, DkGameplayTags::Player_Status_Blocking) };
    if (bIsPlayerBlocking)
    {
        bIsValidBlock = UDkRPGFunctionLibrary::IsValidBlock(this, HitPawn);
    }
    FGameplayEventData EventData;
    EventData.Instigator = this;
    EventData.Target = HitPawn;
    if (bIsValidBlock)
    {
        float PreGEAppliedHealth{ HitCharacter->GetDkAttributeSet()->GetCurrentHealth() };
        ProjectileDamageEffectSpecHandle.Data->SetSetByCallerMagnitude(
            DkGameplayTags::Enemy_SetByCaller_AttackStatus,
            static_cast<int>(EDkEnemyAttackStatus::BeingBlocked)
        );
        // After this GE application, target will either lose stamina if enough stamina to block
        // , or lose health if not enough stamina to block
        HandleApplyProjectileDamage(HitPawn, EventData);
        float PostGEAppliedHealth{ HitCharacter->GetDkAttributeSet()->GetCurrentHealth() };
        if (PostGEAppliedHealth < PreGEAppliedHealth) // Damage taken -> Unsuccessful block
        {
            ProjectileDamageEffectSpecHandle.Data->SetSetByCallerMagnitude(
                DkGameplayTags::Enemy_SetByCaller_AttackStatus,
                static_cast<int>(EDkEnemyAttackStatus::DealtDamage)
            );
            HandleApplyProjectileDamage(HitPawn, EventData);
        }
        else // No damage taken -> Successful block
        {
            ProjectileDamageEffectSpecHandle.Data->SetSetByCallerMagnitude(
                DkGameplayTags::Enemy_SetByCaller_AttackStatus,
                static_cast<int>(EDkEnemyAttackStatus::SuccessfullyBlocked)
            );
            // Pass the damage spec handle as additional payload. `GA_DkHero_Block` (currently only Hero can block)
            // requires this and is also responsible for applying this if the block isn't perfect (i.e. not a parry).
            UDkEnemyAttackSuccessfullyBlockedAddtionalInfo* AdditionalInfo{ NewObject<UDkEnemyAttackSuccessfullyBlockedAddtionalInfo>() };
            AdditionalInfo->SetEnemyDamageEffectSpecHandle(ProjectileDamageEffectSpecHandle);
            EventData.OptionalObject = AdditionalInfo;
            UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(HitPawn, DkGameplayTags::Player_Event_SuccessfulBlock, EventData);
        }
    }
    else
    {
        HandleApplyProjectileDamage(HitPawn, EventData);
    }
    Destroy();
}
References BeingBlocked, BP_OnSpawnProjectileHitFX(), DealtDamage, ADkCharacterBase::GetDkAttributeSet(), HandleApplyProjectileDamage(), UDkRPGFunctionLibrary::IsTargetPawnHostile(), UDkRPGFunctionLibrary::IsValidBlock(), UDkRPGFunctionLibrary::NativeDoesActorHaveTag(), ProjectileDamageEffectSpecHandle, UDkEnemyAttackSuccessfullyBlockedAddtionalInfo::SetEnemyDamageEffectSpecHandle(), and SuccessfullyBlocked.
Referenced by ADkProjectile_Base().
Member Data Documentation
OverlappedActors
TArray<AActor*> ADkProjectile_Base::OverlappedActors private
List of actors that have already been damaged by this projectile, avoids multiple damage applications on a same actor.
Referenced by OnProjectileBeginOverlap().
ProjectileCollisionBox
TObjectPtr<UBoxComponent> ADkProjectile_Base::ProjectileCollisionBox protected
Collision box for the projectile.
Referenced by ADkProjectile_Base(), and BeginPlay().
ProjectileDamageEffectSpecHandle
FGameplayEffectSpecHandle ADkProjectile_Base::ProjectileDamageEffectSpecHandle protected
Gameplay effect spec handle for the projectile's damage effect.
Assigned via Blueprint upon spawning the projectile.
Referenced by HandleApplyProjectileDamage(), and OnProjectileHit().
ProjectileDamagePolicy
EProjectileDamagePolicy ADkProjectile_Base::ProjectileDamagePolicy { EProjectileDamagePolicy::OnHit } protected
Damage policy for the projectile.
{ EProjectileDamagePolicy::OnHit };
Referenced by BeginPlay().
ProjectileMovementComponent
TObjectPtr<UProjectileMovementComponent> ADkProjectile_Base::ProjectileMovementComponent protected
Movement component for handling projectile movement.
Referenced by ADkProjectile_Base().
ProjectileNiagaraComponent
TObjectPtr<UNiagaraComponent> ADkProjectile_Base::ProjectileNiagaraComponent protected
Visual representation of the projectile.
Referenced by ADkProjectile_Base().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Items/Projectiles/DkProjectile_Base.h
D:/DkRPG/Source/DkRPG/Items/Projectiles/DkProjectile_Base.cpp