DkRPG: ADkSurvivalGameMode Class Reference
ADkSurvivalGameMode Class Reference
Class representing the survival game mode.
#include <DkSurvivalGameMode.h>
Public Member Functions
void RegisterSpawnedEnemy (const TArray< ADkEnemy * > &InEnemiesToRegister)
Registers spawned enemies to keep track of them, so the game mode knows when they are destroyed.
Public Member Functions inherited from ADkGameModeBase
ADkGameModeBase ()
FORCEINLINE EDkGameDifficultyLevel GetGameDifficultyLevel () const
Gets the current game difficulty level.
Protected Member Functions
virtual void BeginPlay () override
Called when the game starts or when spawned.
virtual void Tick (float DeltaSeconds) override
Handle state transitions based on the current game mode state.
virtual void InitGame (const FString &MapName, const FString &Options, FString &ErrorMessage) override
Initializes the game with the specified map and options.
Protected Member Functions inherited from ADkGameModeBase
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
Override to implement level music behavior when leaving the map.
Private Member Functions
void SetCurrentSurvivalGameModeState (EDkSurvivalGameModeState NewState)
Sets the current state of the survival game mode.
bool HasFinishedAllWaves () const
Checks if all waves have been completed.
void PreLoadNextWaveEnemies ()
Pre-loads the enemies for the next wave to ensure spawning on time.
FDkEnemyWaveSpawnerTableRow * GetCurrentWaveSpawnerTableRow () const
Retrieves the current wave spawner table row.
int32 TrySpawnWaveEnemies ()
Attempts to spawn enemies for the current wave.
bool ShouldKeepSpawningEnemiesThisWave () const
Determines if more enemies should be spawned in the current wave.
void OnEnemyDestroyed (AActor *DestroyedEnemy)
Callback function when an enemy is destroyed.
Private Attributes
EDkSurvivalGameModeState CurrentSurvivalGameModeState
Current state of the survival game mode.
FDkOnSurvivalGameModeStateChangedDelegate OnSurvivalGameModeStateChanged
Broadcasts when the survival game mode state changes.
TObjectPtr< UDataTable > EnemyWaveSpawnerDataTable
Data table containing enemy wave spawner definitions.
int32 TotalWaveToSpawn
Total number of waves to spawn in the survival game mode.
int32 CurrentWaveCount { 1 }
Current wave count.
int32 CurrentSpawnedEnemyCounter { }
Counter for the number of enemies spawned in the current wave.
int32 TotalSpawnedEnemyThisWaveCounter { }
Total number of enemies spawned in the current wave.
TArray< AActor * > TargetPointsForSpawning
Target points in the level where enemies can be spawned.
float TimePassedSinceStart { 0.f }
Time passed since the start of each state.
float SpawnNewWaveWaitTime { 5.f }
Countdown time before spawning a new wave.
float SpawnEnemyDelayTime { 2.f }
Countdown time between widget the new wave starts and the 1st enemy being spawned.
float WaveCompletedWaitTime { 3.f }
Countdown time between the old wave being completed and the new wave starting.
TMap< TSoftClassPtr< ADkEnemy >, UClass * > PreLoadedEnemyClassMap
Stores pre-loaded enemy classes for the next wave.
Additional Inherited Members
Protected Attributes inherited from ADkGameModeBase
EDkGameDifficultyLevel CurrentGameDifficultyLevel
The current game difficulty level.
FGameplayTag LevelMusicTag
The gameplay tag associated with the music to play for this level.
Detailed Description
Class representing the survival game mode.
Member Function Documentation
BeginPlay()
void ADkSurvivalGameMode::BeginPlay () override protected virtual
Called when the game starts or when spawned.
Reimplemented from ADkGameModeBase.
{
    Super::BeginPlay();
    checkf(EnemyWaveSpawnerDataTable, TEXT("EnemyWaveSpawnerTable is not assigned in the Survival Game Mode blueprint!"));
    SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::WaitingForNextWave);
    TotalWaveToSpawn = EnemyWaveSpawnerDataTable->GetRowNames().Num();
    PreLoadNextWaveEnemies();
}
References EnemyWaveSpawnerDataTable, PreLoadNextWaveEnemies(), SetCurrentSurvivalGameModeState(), TotalWaveToSpawn, and WaitingForNextWave.
GetCurrentWaveSpawnerTableRow()
FDkEnemyWaveSpawnerTableRow * ADkSurvivalGameMode::GetCurrentWaveSpawnerTableRow () const private
Retrieves the current wave spawner table row.
{
    FDkEnemyWaveSpawnerTableRow* FoundRow{ EnemyWaveSpawnerDataTable->FindRow<FDkEnemyWaveSpawnerTableRow>(
        FName{ TEXT("Wave") + FString::FromInt(CurrentWaveCount) }, // must match the naming convention "WaveX"
        FString{}                                                   // string to display on error, doesn't need anything here
    ) };
    checkf(FoundRow, TEXT("Could not find wave spawner table row for wave %d! Please ensure the row exists and follows the naming convention 'WaveX'."), CurrentWaveCount);
    return FoundRow;
}
References CurrentWaveCount, and EnemyWaveSpawnerDataTable.
Referenced by PreLoadNextWaveEnemies(), ShouldKeepSpawningEnemiesThisWave(), and TrySpawnWaveEnemies().
HasFinishedAllWaves()
bool ADkSurvivalGameMode::HasFinishedAllWaves () const private
Checks if all waves have been completed.
{
    return CurrentWaveCount > TotalWaveToSpawn;
}
References CurrentWaveCount, and TotalWaveToSpawn.
Referenced by PreLoadNextWaveEnemies(), and Tick().
InitGame()
void ADkSurvivalGameMode::InitGame (const FString & MapName, const FString & Options, FString & ErrorMessage) override protected virtual
Initializes the game with the specified map and options.
{
    Super::InitGame(MapName, Options, ErrorMessage);
    EDkGameDifficultyLevel SavedDifficultyLevel;
    if (UDkRPGFunctionLibrary::TryLoadCurrentGameDifficultyLevel(SavedDifficultyLevel))
    {
        CurrentGameDifficultyLevel = SavedDifficultyLevel;
    }
}
References ADkGameModeBase::CurrentGameDifficultyLevel, and UDkRPGFunctionLibrary::TryLoadCurrentGameDifficultyLevel().
OnEnemyDestroyed()
void ADkSurvivalGameMode::OnEnemyDestroyed (AActor * DestroyedEnemy) private
Callback function when an enemy is destroyed.
{
    --CurrentSpawnedEnemyCounter;
    if (ShouldKeepSpawningEnemiesThisWave())
    {
        CurrentSpawnedEnemyCounter += TrySpawnWaveEnemies();
    }
    else if (CurrentSpawnedEnemyCounter <= 0)
    {
        // All enemies for this wave have been spawned and defeated
        TotalSpawnedEnemyThisWaveCounter = 0; // Reset for next wave
        CurrentSpawnedEnemyCounter = 0;
        SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::WaveCompleted);
    }
}
References CurrentSpawnedEnemyCounter, SetCurrentSurvivalGameModeState(), ShouldKeepSpawningEnemiesThisWave(), TotalSpawnedEnemyThisWaveCounter, TrySpawnWaveEnemies(), and WaveCompleted.
Referenced by RegisterSpawnedEnemy(), and TrySpawnWaveEnemies().
PreLoadNextWaveEnemies()
void ADkSurvivalGameMode::PreLoadNextWaveEnemies () private
Pre-loads the enemies for the next wave to ensure spawning on time.
{
    if (HasFinishedAllWaves())
    {
        return;
    }
    PreLoadedEnemyClassMap.Empty(); // Clear previous pre-loaded classes
    for (const FDkEnemyWaveSpawnerInfo& SpawnerInfo : GetCurrentWaveSpawnerTableRow()->EnemyWaveSpawnerDefinitions)
    {
        if (SpawnerInfo.SoftEnemyClassToSpawn.IsNull())
        {
            continue;
        }
        UAssetManager::GetStreamableManager().RequestAsyncLoad(
            SpawnerInfo.SoftEnemyClassToSpawn.ToSoftObjectPath(),
            FStreamableDelegate::CreateLambda( // When loading is complete, this lambda will be executed
                [SpawnerInfo, this]()
                {
                    if (UClass* LoadedEnemyClass = SpawnerInfo.SoftEnemyClassToSpawn.Get())
                    {
                        PreLoadedEnemyClassMap.Emplace(SpawnerInfo.SoftEnemyClassToSpawn, LoadedEnemyClass);
                    }
                }
            )
        );
    }
}
References GetCurrentWaveSpawnerTableRow(), HasFinishedAllWaves(), and PreLoadedEnemyClassMap.
Referenced by BeginPlay(), and Tick().
RegisterSpawnedEnemy()
void ADkSurvivalGameMode::RegisterSpawnedEnemy (const TArray< ADkEnemy * > & InEnemiesToRegister)
Registers spawned enemies to keep track of them, so the game mode knows when they are destroyed.
Note
Enemies spawned by other enemies will also be counted towards the total spawned enemy count for the wave.
{
    for (ADkEnemy* SpawnedEnemy : InEnemiesToRegister)
    {
        if (SpawnedEnemy)
        {
            ++CurrentSpawnedEnemyCounter;
            SpawnedEnemy->OnDestroyed.AddUniqueDynamic(this, &ADkSurvivalGameMode::OnEnemyDestroyed);
        }
    }
}
References CurrentSpawnedEnemyCounter, and OnEnemyDestroyed().
SetCurrentSurvivalGameModeState()
void ADkSurvivalGameMode::SetCurrentSurvivalGameModeState (EDkSurvivalGameModeState NewState) private
Sets the current state of the survival game mode.
{
    CurrentSurvivalGameModeState = NewState;
    OnSurvivalGameModeStateChanged.Broadcast(CurrentSurvivalGameModeState);
}
References CurrentSurvivalGameModeState, and OnSurvivalGameModeStateChanged.
Referenced by BeginPlay(), OnEnemyDestroyed(), and Tick().
ShouldKeepSpawningEnemiesThisWave()
bool ADkSurvivalGameMode::ShouldKeepSpawningEnemiesThisWave () const private
Determines if more enemies should be spawned in the current wave.
{
    return TotalSpawnedEnemyThisWaveCounter < GetCurrentWaveSpawnerTableRow()->TotalEnemiesToSpawnThisWave;
}
References GetCurrentWaveSpawnerTableRow(), FDkEnemyWaveSpawnerTableRow::TotalEnemiesToSpawnThisWave, and TotalSpawnedEnemyThisWaveCounter.
Referenced by OnEnemyDestroyed(), and TrySpawnWaveEnemies().
Tick()
void ADkSurvivalGameMode::Tick (float DeltaSeconds) override protected virtual
Handle state transitions based on the current game mode state.
{
    Super::Tick(DeltaSeconds);
    if (CurrentSurvivalGameModeState == EDkSurvivalGameModeState::WaitingForNextWave)
    {
        TimePassedSinceStart += DeltaSeconds;
        if (TimePassedSinceStart >= SpawnNewWaveWaitTime)
        {
            TimePassedSinceStart = 0.f;
            SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::SpawningWave);
        }
    }
    if (CurrentSurvivalGameModeState == EDkSurvivalGameModeState::SpawningWave)
    {
        TimePassedSinceStart += DeltaSeconds;
        if (TimePassedSinceStart >= SpawnEnemyDelayTime)
        {
            CurrentSpawnedEnemyCounter += TrySpawnWaveEnemies();
            TimePassedSinceStart = 0.f;
            SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::WaveInProgress);
        }
    }
    if (CurrentSurvivalGameModeState == EDkSurvivalGameModeState::WaveCompleted)
    {
        TimePassedSinceStart += DeltaSeconds;
        if (TimePassedSinceStart >= WaveCompletedWaitTime)
        {
            TimePassedSinceStart = 0.f;
            ++CurrentWaveCount;
            if (HasFinishedAllWaves())
            {
                SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::AllWavesCompleted);
            }
            else
            {
                SetCurrentSurvivalGameModeState(EDkSurvivalGameModeState::WaitingForNextWave);
                PreLoadNextWaveEnemies();
            }
        }
    }
}
References AllWavesCompleted, CurrentSpawnedEnemyCounter, CurrentSurvivalGameModeState, CurrentWaveCount, HasFinishedAllWaves(), PreLoadNextWaveEnemies(), SetCurrentSurvivalGameModeState(), SpawnEnemyDelayTime, SpawningWave, SpawnNewWaveWaitTime, TimePassedSinceStart, TrySpawnWaveEnemies(), WaitingForNextWave, WaveCompleted, WaveCompletedWaitTime, and WaveInProgress.
TrySpawnWaveEnemies()
int32 ADkSurvivalGameMode::TrySpawnWaveEnemies () private
Attempts to spawn enemies for the current wave.
{
    // Retrieve all Target Points in the level for spawning enemies
    if (TargetPointsForSpawning.IsEmpty())
    {
        UGameplayStatics::GetAllActorsOfClass(
            this,                        // World context
            ATargetPoint::StaticClass(), // Actor class to find
            TargetPointsForSpawning      // Output array
        );
    }
    checkf(!TargetPointsForSpawning.IsEmpty(), TEXT("No Target Points found for spawning enemies in the level! Please add Target Points to the level."));
    uint32 EnemiesSpawnedThisTime{ 0 };
    FActorSpawnParameters SpawnParams;
    SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;
    for (const FDkEnemyWaveSpawnerInfo& SpawnerInfo : GetCurrentWaveSpawnerTableRow()->EnemyWaveSpawnerDefinitions)
    {
        if (SpawnerInfo.SoftEnemyClassToSpawn.IsNull())
        {
            continue;
        }
        const int32 EnemiesToSpawnCount{ FMath::RandRange(SpawnerInfo.MinPerSpawnCount, SpawnerInfo.MaxPerSpawnCount) };
        UClass* PreLoadedEnemyClass{ PreLoadedEnemyClassMap.FindChecked(SpawnerInfo.SoftEnemyClassToSpawn) };
        for (int32 i{}; i < EnemiesToSpawnCount; ++i)
        {
            const int32 RandomTargetPointIndex{ FMath::RandRange(0, TargetPointsForSpawning.Num() - 1) };
            const FVector SpawnOrigin{ TargetPointsForSpawning[RandomTargetPointIndex]->GetActorLocation() };
            const FRotator SpawnRotation{ TargetPointsForSpawning[RandomTargetPointIndex]->GetActorForwardVector().ToOrientationRotator() };
            FVector RandomLocation;
            UNavigationSystemV1::K2_GetRandomLocationInNavigableRadius(
                this,           // World context
                SpawnOrigin,    // Origin
                RandomLocation, // Out Random Location
                200.f           // Radius
            );
            RandomLocation += FVector{ 0.f, 0.f, 150.f }; // Slightly elevate spawn location to avoid ground clipping
            ADkEnemy* SpawnedEnemy{ GetWorld()->SpawnActor<ADkEnemy>(
                PreLoadedEnemyClass,    // Enemy class to spawn
                RandomLocation,         // Spawn location
                SpawnRotation,          // Spawn rotation
                SpawnParams             // Spawn parameters (collision handling, etc.)
            ) };
            if (SpawnedEnemy)
            {
                SpawnedEnemy->OnDestroyed.AddUniqueDynamic(this, &ADkSurvivalGameMode::OnEnemyDestroyed);
                ++EnemiesSpawnedThisTime;
                ++TotalSpawnedEnemyThisWaveCounter;
            }
            if (!ShouldKeepSpawningEnemiesThisWave())
            {
                return EnemiesSpawnedThisTime;
            }
        }
    }
    return EnemiesSpawnedThisTime;
}
References GetCurrentWaveSpawnerTableRow(), OnEnemyDestroyed(), PreLoadedEnemyClassMap, ShouldKeepSpawningEnemiesThisWave(), TargetPointsForSpawning, and TotalSpawnedEnemyThisWaveCounter.
Referenced by OnEnemyDestroyed(), and Tick().
Member Data Documentation
CurrentSpawnedEnemyCounter
int32 ADkSurvivalGameMode::CurrentSpawnedEnemyCounter { } private
Counter for the number of enemies spawned in the current wave.
{ };
Referenced by OnEnemyDestroyed(), RegisterSpawnedEnemy(), and Tick().
CurrentSurvivalGameModeState
EDkSurvivalGameModeState ADkSurvivalGameMode::CurrentSurvivalGameModeState private
Current state of the survival game mode.
Referenced by SetCurrentSurvivalGameModeState(), and Tick().
CurrentWaveCount
int32 ADkSurvivalGameMode::CurrentWaveCount { 1 } private
Current wave count.
{ 1 };
Referenced by GetCurrentWaveSpawnerTableRow(), HasFinishedAllWaves(), and Tick().
EnemyWaveSpawnerDataTable
TObjectPtr<UDataTable> ADkSurvivalGameMode::EnemyWaveSpawnerDataTable private
Data table containing enemy wave spawner definitions.
Note
Each row must follow the naming convention "WaveX" where X is the wave number (e.g., Wave1, Wave2, etc.)
Referenced by BeginPlay(), and GetCurrentWaveSpawnerTableRow().
OnSurvivalGameModeStateChanged
FDkOnSurvivalGameModeStateChangedDelegate ADkSurvivalGameMode::OnSurvivalGameModeStateChanged private
Broadcasts when the survival game mode state changes.
Referenced by SetCurrentSurvivalGameModeState().
PreLoadedEnemyClassMap
TMap<TSoftClassPtr<ADkEnemy>, UClass*> ADkSurvivalGameMode::PreLoadedEnemyClassMap private
Stores pre-loaded enemy classes for the next wave.
Referenced by PreLoadNextWaveEnemies(), and TrySpawnWaveEnemies().
SpawnEnemyDelayTime
float ADkSurvivalGameMode::SpawnEnemyDelayTime { 2.f } private
Countdown time between widget the new wave starts and the 1st enemy being spawned.
{ 2.f };
Referenced by Tick().
SpawnNewWaveWaitTime
float ADkSurvivalGameMode::SpawnNewWaveWaitTime { 5.f } private
Countdown time before spawning a new wave.
{ 5.f };
Referenced by Tick().
TargetPointsForSpawning
TArray<AActor*> ADkSurvivalGameMode::TargetPointsForSpawning private
Target points in the level where enemies can be spawned.
Referenced by TrySpawnWaveEnemies().
TimePassedSinceStart
float ADkSurvivalGameMode::TimePassedSinceStart { 0.f } private
Time passed since the start of each state.
{ 0.f };
Referenced by Tick().
TotalSpawnedEnemyThisWaveCounter
int32 ADkSurvivalGameMode::TotalSpawnedEnemyThisWaveCounter { } private
Total number of enemies spawned in the current wave.
{ };
Referenced by OnEnemyDestroyed(), ShouldKeepSpawningEnemiesThisWave(), and TrySpawnWaveEnemies().
TotalWaveToSpawn
int32 ADkSurvivalGameMode::TotalWaveToSpawn private
Total number of waves to spawn in the survival game mode.
Referenced by BeginPlay(), and HasFinishedAllWaves().
WaveCompletedWaitTime
float ADkSurvivalGameMode::WaveCompletedWaitTime { 3.f } private
Countdown time between the old wave being completed and the new wave starting.
{ 3.f };
Referenced by Tick().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/GameModes/DkSurvivalGameMode.h
D:/DkRPG/Source/DkRPG/GameModes/DkSurvivalGameMode.cpp