DkRPG: IDkPawnUIInterface Class Reference
IDkPawnUIInterface Class Reference abstract
Interface for pawns that expose UI-related functionality.
#include <DkPawnUIInterface.h>
Public Member Functions
virtual UDkPawnUIComponent * GetPawnUIComponent () const =0
Getter for the Pawn UI Component.
virtual UDkHeroUIComponent * GetHeroUIComponent () const
Getter for the Hero UI Component. Returns null if the pawn is not a Hero.
virtual UDkEnemyUIComponent * GetEnemyUIComponent () const
Getter for the Enemy UI Component. Returns null if the pawn is not an Enemy.
Detailed Description
Interface for pawns that expose UI-related functionality.
Member Function Documentation
GetEnemyUIComponent()
UDkEnemyUIComponent * IDkPawnUIInterface::GetEnemyUIComponent () const virtual
Getter for the Enemy UI Component. Returns null if the pawn is not an Enemy.
Reimplemented in ADkEnemy.
{
    return nullptr;
}
Referenced by GetPawnUIComponent().
GetHeroUIComponent()
UDkHeroUIComponent * IDkPawnUIInterface::GetHeroUIComponent () const virtual
Getter for the Hero UI Component. Returns null if the pawn is not a Hero.
Reimplemented in ADkHero.
{
    return nullptr;
}
Referenced by GetPawnUIComponent().
GetPawnUIComponent()
virtual UDkPawnUIComponent * IDkPawnUIInterface::GetPawnUIComponent () const pure virtual
Getter for the Pawn UI Component.
Implemented in ADkCharacterBase, ADkEnemy, and ADkHero.
References GetEnemyUIComponent(), and GetHeroUIComponent().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Interfaces/DkPawnUIInterface.h
D:/DkRPG/Source/DkRPG/Interfaces/DkPawnUIInterface.cpp