DkRPG: UDkGameplayAbility Class Reference
UDkGameplayAbility Class Reference
Base Gameplay Ability class providing common helper functionality.
#include <DkGameplayAbility.h>
Protected Member Functions
UDkPawnCombatComponent * GetPawnCombatComponentFromActorInfo () const
Retrieves the pawn's combat component from the actor info.
UDkAbilitySystemComponent * GetDkAbilitySystemComponentFromActorInfo () const
Retrieves the ASC from the actor info.
FActiveGameplayEffectHandle NativeApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle) const
Applies a gameplay effect spec handle to a target actor.
FActiveGameplayEffectHandle BP_ApplyEffectSpecHandleToTarget (AActor *TargetActor, const FGameplayEffectSpecHandle &InEffectSpecHandle, EDkSuccessType &SuccessType)
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
void ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle &InSpecHandle, const TArray< FHitResult > &InHitResults)
Applies a gameplay effect spec handle to multiple hit results.
void OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount)
Callback when a gameplay tag changes that may cancel this ability.
UGameplayAbility interface
virtual void OnGiveAbility (const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilitySpec &Spec) override
Called right after an ability is given to the ASC.
virtual void PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate *OnGameplayAbilityEndedDelegate, const FGameplayEventData *TriggerEventData=nullptr) override
Called right before the ability is activated.
virtual void EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo *ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override
Called when the ability ends normally or abnormally.
Protected Attributes
EDkAbilityActivationPolicy AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered }
Defines the activation policy for this ability.
TMap< FGameplayTag, EDkAbilityCancelTrigger > CancelAbilityTriggers
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Detailed Description
Base Gameplay Ability class providing common helper functionality.
Steps to configure a Gameplay ability
Create ability tag(s)
Subclass this class into a new Blueprint
Make corresponding Anim Montages(s)
Config Ability input actions
Grant the ability
Todo
Implement different slash damage and rage gain values between light and heavy attacks, better based on the amount of damage dealt.
Member Function Documentation
ApplyGameplayEffectSpecHandleToHitResults()
void UDkGameplayAbility::ApplyGameplayEffectSpecHandleToHitResults (const FGameplayEffectSpecHandle & InSpecHandle, const TArray< FHitResult > & InHitResults) protected
Applies a gameplay effect spec handle to multiple hit results.
{
    if (InHitResults.IsEmpty())
    {
        return;
    }
    APawn* OwningPawn{ CastChecked<APawn>(GetAvatarActorFromActorInfo()) };
    for (const FHitResult& HitResult : InHitResults)
    {
        if (APawn * HitPawn{ Cast<APawn>(HitResult.GetActor()) })
        {
            if (UDkRPGFunctionLibrary::IsTargetPawnHostile(OwningPawn, HitPawn))
            {
                FActiveGameplayEffectHandle ActiveEffectHandle{ NativeApplyEffectSpecHandleToTarget(HitPawn, InSpecHandle) };
                if (ActiveEffectHandle.WasSuccessfullyApplied())
                {
                    FGameplayEventData EventData;
                    EventData.Instigator = OwningPawn;
                    EventData.Target = HitPawn;
                    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(HitPawn, DkGameplayTags::Shared_Event_HitReact, EventData);
                }
            }
        }
    }
}
References UDkRPGFunctionLibrary::IsTargetPawnHostile(), and NativeApplyEffectSpecHandleToTarget().
BP_ApplyEffectSpecHandleToTarget()
FActiveGameplayEffectHandle UDkGameplayAbility::BP_ApplyEffectSpecHandleToTarget (AActor * TargetActor, const FGameplayEffectSpecHandle & InEffectSpecHandle, EDkSuccessType & SuccessType) protected
Blueprint wrapper of NativeApplyEffectSpecHandleToTarget.
{
    FActiveGameplayEffectHandle ActiveEffectHandle{ NativeApplyEffectSpecHandleToTarget(TargetActor, InEffectSpecHandle) };
    SuccessType = ActiveEffectHandle.WasSuccessfullyApplied() ? EDkSuccessType::Successful : EDkSuccessType::Failed;
    return ActiveEffectHandle;
}
References Failed, NativeApplyEffectSpecHandleToTarget(), and Successful.
EndAbility()
void UDkGameplayAbility::EndAbility (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, bool bReplicateEndAbility, bool bWasCancelled) override protected virtual
Called when the ability ends normally or abnormally.
Reimplemented in UDkHeroGameplayAbility_PickStones, and UDkHeroGameplayAbility_TargetLock.
{
    Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
    // Deactivate the abilities that are automatically activated when given
    if (AbilityActivationPolicy == EDkAbilityActivationPolicy::OnGiven)
    {
        if (ActorInfo)
        {
            ActorInfo->AbilitySystemComponent->ClearAbility(Handle);
        }
    }
    // Unregister those tags that can cancel this ability
    if (UAbilitySystemComponent * ASC{ Cast<UAbilitySystemComponent>(ActorInfo->AbilitySystemComponent) })
    {
        for (const TPair<FGameplayTag, EDkAbilityCancelTrigger>& Pair : CancelAbilityTriggers)
        {
            const FGameplayTag& TagToUnbind = Pair.Key;
            ASC->RegisterGameplayTagEvent(TagToUnbind, EGameplayTagEventType::AnyCountChange).RemoveAll(this);
        }
    }
}
References AbilityActivationPolicy, CancelAbilityTriggers, and OnGiven.
GetDkAbilitySystemComponentFromActorInfo()
UDkAbilitySystemComponent * UDkGameplayAbility::GetDkAbilitySystemComponentFromActorInfo () const protected
Retrieves the ASC from the actor info.
{
    return Cast<UDkAbilitySystemComponent>(CurrentActorInfo->AbilitySystemComponent);
}
Referenced by UDkHeroGameplayAbility_PickStones::ConsumeStones(), UDkHeroGameplayAbility::GetAbilityRemainingCooldownByTag(), UDkEnemyGameplayAbility::MakeEnemyDamageEffectSpecHandle(), UDkHeroGameplayAbility::MakeHeroDamageEffectSpecHandle(), UDkHeroGameplayAbility::MakeHeroWeaponAttackStaminaCostEffectSpecHandle(), and NativeApplyEffectSpecHandleToTarget().
GetPawnCombatComponentFromActorInfo()
UDkPawnCombatComponent * UDkGameplayAbility::GetPawnCombatComponentFromActorInfo () const protected
Retrieves the pawn's combat component from the actor info.
Warning
Assumes that the avatar actor has only one UDkPawnCombatComponent attached to it. If there are multiple such components, only the first one found will be returned, which may lead to unexpected behavior.
{
    return GetAvatarActorFromActorInfo()->FindComponentByClass<UDkPawnCombatComponent>();
}
NativeApplyEffectSpecHandleToTarget()
FActiveGameplayEffectHandle UDkGameplayAbility::NativeApplyEffectSpecHandleToTarget (AActor * TargetActor, const FGameplayEffectSpecHandle & InEffectSpecHandle) const protected
Applies a gameplay effect spec handle to a target actor.
{
    UAbilitySystemComponent* TargetASC{ UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(TargetActor) };
    checkf(TargetASC, TEXT("UDkGameplayAbility::NativeApplyEffectSpecHandleToTarget: TargetActor %s does not have an AbilitySystemComponent!"), *GetNameSafe(TargetActor));
    return GetDkAbilitySystemComponentFromActorInfo()->ApplyGameplayEffectSpecToTarget(*InEffectSpecHandle.Data.Get(), TargetASC);
}
References GetDkAbilitySystemComponentFromActorInfo().
Referenced by ApplyGameplayEffectSpecHandleToHitResults(), and BP_ApplyEffectSpecHandleToTarget().
OnGameplayTagChanged_CancelAbility()
void UDkGameplayAbility::OnGameplayTagChanged_CancelAbility (const FGameplayTag ChangedTag, int32 NewCount) protected
Callback when a gameplay tag changes that may cancel this ability.
{
    if (!CancelAbilityTriggers.Contains(ChangedTag))
    {
        return;
    }
    EDkAbilityCancelTrigger CancelTrigger{ CancelAbilityTriggers[ChangedTag] };
    bool bShouldCancel{ false };
    switch (CancelTrigger)
    {
        case EDkAbilityCancelTrigger::OnTagAdded:   bShouldCancel = (NewCount > 0);     break;
        case EDkAbilityCancelTrigger::OnTagRemoved: bShouldCancel = (NewCount == 0);    break;
        case EDkAbilityCancelTrigger::OnTagChanged: bShouldCancel = true;               break;
        default: break;
    }
    if (bShouldCancel)
    {
        CancelAbility(CurrentSpecHandle, CurrentActorInfo, CurrentActivationInfo, false);
    }
}
References CancelAbilityTriggers, OnTagAdded, OnTagChanged, and OnTagRemoved.
Referenced by PreActivate().
OnGiveAbility()
void UDkGameplayAbility::OnGiveAbility (const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilitySpec & Spec) override protected virtual
Called right after an ability is given to the ASC.
{
    Super::OnGiveAbility(ActorInfo, Spec);
    // Automatically activate the abilities whose activation policy is `OnGiven`
    if (AbilityActivationPolicy == EDkAbilityActivationPolicy::OnGiven)
    {
        if (ActorInfo && !Spec.IsActive())
        {
            ActorInfo->AbilitySystemComponent->TryActivateAbility(Spec.Handle);
        }
    }
}
References AbilityActivationPolicy, and OnGiven.
PreActivate()
void UDkGameplayAbility::PreActivate (const FGameplayAbilitySpecHandle Handle, const FGameplayAbilityActorInfo * ActorInfo, const FGameplayAbilityActivationInfo ActivationInfo, FOnGameplayAbilityEnded::FDelegate * OnGameplayAbilityEndedDelegate, const FGameplayEventData * TriggerEventData = nullptr) override protected virtual
Called right before the ability is activated.
{
    Super::PreActivate(Handle, ActorInfo, ActivationInfo, OnGameplayAbilityEndedDelegate, TriggerEventData);
    // Register those tags that can cancel this ability
    if (UAbilitySystemComponent * ASC{ Cast<UAbilitySystemComponent>(ActorInfo->AbilitySystemComponent) })
    {
        for (const TPair<FGameplayTag, EDkAbilityCancelTrigger>& Pair : CancelAbilityTriggers)
        {
            const FGameplayTag& TagToBind = Pair.Key;
            ASC->RegisterGameplayTagEvent(TagToBind, EGameplayTagEventType::AnyCountChange).AddUObject(this, &UDkGameplayAbility::OnGameplayTagChanged_CancelAbility);
        }
    }
}
References CancelAbilityTriggers, and OnGameplayTagChanged_CancelAbility().
Member Data Documentation
AbilityActivationPolicy
EDkAbilityActivationPolicy UDkGameplayAbility::AbilityActivationPolicy { EDkAbilityActivationPolicy::OnTriggered } protected
Defines the activation policy for this ability.
{ EDkAbilityActivationPolicy::OnTriggered };
Referenced by EndAbility(), and OnGiveAbility().
CancelAbilityTriggers
TMap<FGameplayTag, EDkAbilityCancelTrigger> UDkGameplayAbility::CancelAbilityTriggers protected
Map of gameplay tags and their corresponding triggers that can cancel this ability.
Referenced by EndAbility(), OnGameplayTagChanged_CancelAbility(), and PreActivate().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkGameplayAbility.h
D:/DkRPG/Source/DkRPG/AbilitySystem/Abilities/DkGameplayAbility.cpp