DkRPG: ADkHero Class Reference
ADkHero Class Reference
The main playable character class for the game.
#include <DkHero.h>
Public Member Functions
ADkHero ()
Initializes default values for this character's properties.
FORCEINLINE UDkHeroCombatComponent * GetHeroCombatComponent () const
Getter for the Combat component.
IDkPawnCombatInterface interface
virtual UDkPawnCombatComponent * GetPawnCombatComponent () const override
Getter for the Pawn Combat Component.
IDkPawnUIInterface interface
virtual UDkPawnUIComponent * GetPawnUIComponent () const override
Getter for the Pawn UI Component.
virtual UDkHeroUIComponent * GetHeroUIComponent () const override
Override to return the Hero UI Component.
Public Member Functions inherited from ADkCharacterBase
ADkCharacterBase ()
FORCEINLINE UDkAbilitySystemComponent * GetDkAbilitySystemComponent () const
Getter for the Ability System Component.
FORCEINLINE UDkAttributeSet * GetDkAttributeSet () const
Getter for the Attribute Set.
virtual UAbilitySystemComponent * GetAbilitySystemComponent () const override
Pure virtual function that must be overridden.
Public Member Functions inherited from IDkPawnUIInterface
virtual UDkEnemyUIComponent * GetEnemyUIComponent () const
Getter for the Enemy UI Component. Returns null if the pawn is not an Enemy.
Protected Member Functions
virtual void BeginPlay () override
Called when the game starts or when spawned.
virtual void SetupPlayerInputComponent (class UInputComponent *PlayerInputComponent) override
Binds callbacks to input actions.
APawn interface
virtual void PossessedBy (AController *NewController) override
Virtual function from ACharacter that must be overridden.
Protected Member Functions inherited from ADkCharacterBase
Private Member Functions
void Input_Move (const FInputActionValue &Value)
Callback to move the character on repsonse to input.
void Input_Look (const FInputActionValue &Value)
Callback to look around on response to input.
void Input_PickUp_Stones_Started (const FInputActionValue &Value)
Callback to handle stone pickup input when started.
void Input_SwitchTargetTriggered (const FInputActionValue &Value)
Callback to handle target switching input when triggered during target lock.
void Input_SwitchTargetCompleted (const FInputActionValue &Value)
Callback to handle target switching input when completed during target lock.
void Input_AbilityInputPressed (FGameplayTag InInputTag)
Callback to handle ability input pressed events.
void Input_AbilityInputReleased (FGameplayTag InInputTag)
Callback to handle ability input released events.
Private Attributes
TObjectPtr< USpringArmComponent > CameraBoom
Camera boom positioning the camera behind the character.
TObjectPtr< UCameraComponent > FollowCamera
Follow camera.
TObjectPtr< UDkHeroCombatComponent > HeroCombatComponent
Handles combat-related functionality.
TObjectPtr< UDkHeroUIComponent > HeroUIComponent
UI component for handling user interface interactions.
TObjectPtr< UDkDataAsset_InputConfig > InputConfigDataAsset
Input configuration data asset used to define character input mappings.
FVector2D SwitchTargetDirection { FVector2D::ZeroVector }
Cached direction for switching targets during target lock.
Additional Inherited Members
Protected Attributes inherited from ADkCharacterBase
TObjectPtr< UDkAbilitySystemComponent > DkAbilitySystemComponent
Ability System Component.
TObjectPtr< UDkAttributeSet > DkAttributeSet
Attribute Set.
TSoftObjectPtr< UDkDataAsset_StartUpDataBase > CharacterStartUpData
Startup data asset for both hero and enemies.
TObjectPtr< UMotionWarpingComponent > MotionWarpingComponent
Motion Warping Component.
Detailed Description
The main playable character class for the game.
Constructor & Destructor Documentation
ADkHero()
ADkHero::ADkHero ()
Initializes default values for this character's properties.
Note
Some properties are hard-coded (e.g. capsule size, movement settings) here.
{
    // Setup Capsule Component
    GetCapsuleComponent()->InitCapsuleSize(42.f, 96.0f);
    // Don't rotate when the controller rotates. Let that just affect the camera.
    bUseControllerRotationPitch = false;
    bUseControllerRotationYaw = false;
    bUseControllerRotationRoll = false;
    // Setup Camera Boom
    CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
    CameraBoom->SetupAttachment(GetRootComponent());
    CameraBoom->TargetArmLength = 300.0f;
    CameraBoom->SocketOffset = FVector{ 0.f, 55.f, 65.f };
    CameraBoom->bUsePawnControlRotation = true;
    // Setup Follow Camera
    FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
    FollowCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);
    FollowCamera->bUsePawnControlRotation = false;
    HeroCombatComponent = CreateDefaultSubobject<UDkHeroCombatComponent>(TEXT("HeroCombatComponent"));
    HeroUIComponent = CreateDefaultSubobject<UDkHeroUIComponent>(TEXT("HeroUIComponent"));
    // Configure character movement
    GetCharacterMovement()->bOrientRotationToMovement = true;
    GetCharacterMovement()->RotationRate = FRotator{ 0.f, 450.f, 0.f };
    GetCharacterMovement()->BrakingDecelerationWalking = 800.f;
}
References CameraBoom, FollowCamera, HeroCombatComponent, and HeroUIComponent.
Member Function Documentation
BeginPlay()
void ADkHero::BeginPlay () override protected virtual
Called when the game starts or when spawned.
{
    Super::BeginPlay();
}
GetHeroCombatComponent()
FORCEINLINE UDkHeroCombatComponent * ADkHero::GetHeroCombatComponent () const inline
Getter for the Combat component.
{ return HeroCombatComponent; }
References HeroCombatComponent.
Referenced by UDkHeroGameplayAbility::GetHeroCombatComponentFromActorInfo().
GetHeroUIComponent()
UDkHeroUIComponent * ADkHero::GetHeroUIComponent () const override virtual
Override to return the Hero UI Component.
Reimplemented from IDkPawnUIInterface.
{
    return HeroUIComponent;
}
References HeroUIComponent.
Referenced by UDkHeroGameplayAbility::GetHeroUIComponentFromActorInfo().
GetPawnCombatComponent()
UDkPawnCombatComponent * ADkHero::GetPawnCombatComponent () const override virtual
Getter for the Pawn Combat Component.
Reimplemented from ADkCharacterBase.
{
    return HeroCombatComponent;
}
References HeroCombatComponent.
GetPawnUIComponent()
UDkPawnUIComponent * ADkHero::GetPawnUIComponent () const override virtual
Getter for the Pawn UI Component.
Reimplemented from ADkCharacterBase.
{
    return HeroUIComponent;
}
References HeroUIComponent.
Input_AbilityInputPressed()
void ADkHero::Input_AbilityInputPressed (FGameplayTag InInputTag) private
Callback to handle ability input pressed events.
Simply passes the input tag to the ASC, which is responsible for activating abilities associated with that tag.
{
    DkAbilitySystemComponent->OnAbilityInputPressed(InInputTag);
}
References ADkCharacterBase::DkAbilitySystemComponent.
Referenced by SetupPlayerInputComponent().
Input_AbilityInputReleased()
void ADkHero::Input_AbilityInputReleased (FGameplayTag InInputTag) private
Callback to handle ability input released events.
Simply passes the input tag to the ASC, which is responsible for activating abilities associated with that tag.
{
    DkAbilitySystemComponent->OnAbilityInputReleased(InInputTag);
}
References ADkCharacterBase::DkAbilitySystemComponent.
Referenced by SetupPlayerInputComponent().
Input_Look()
void ADkHero::Input_Look (const FInputActionValue & Value) private
Callback to look around on response to input.
{
    const FVector2D LookAxisVector{ InputActionValue.Get<FVector2D>() };
    if (LookAxisVector.Y != 0.f)
    {
        AddControllerPitchInput(LookAxisVector.Y);
    }
    if (LookAxisVector.X != 0.f)
    {
        AddControllerYawInput(LookAxisVector.X);
    }
}
Referenced by SetupPlayerInputComponent().
Input_Move()
void ADkHero::Input_Move (const FInputActionValue & Value) private
Callback to move the character on repsonse to input.
{
    const FVector2D MovementVector{ InputActionValue.Get<FVector2D>() };
    const FRotator MovementRotation{ 0.f, Controller->GetControlRotation().Yaw, 0.f };
    if (MovementVector.Y != 0.f)
    {
        const FVector ForwardDirection{ MovementRotation.RotateVector(FVector::ForwardVector) };
        AddMovementInput(ForwardDirection, MovementVector.Y);
    }
    if (MovementVector.X != 0.f)
    {
        const FVector RightDirection{ MovementRotation.RotateVector(FVector::RightVector) };
        AddMovementInput(RightDirection, MovementVector.X);
    }
}
Referenced by SetupPlayerInputComponent().
Input_PickUp_Stones_Started()
void ADkHero::Input_PickUp_Stones_Started (const FInputActionValue & Value) private
Callback to handle stone pickup input when started.
{
    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
        this,
        DkGameplayTags::Player_Event_Consume_Stones,
        FGameplayEventData{}
    );
}
Referenced by SetupPlayerInputComponent().
Input_SwitchTargetCompleted()
void ADkHero::Input_SwitchTargetCompleted (const FInputActionValue & Value) private
Callback to handle target switching input when completed during target lock.
{
    UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
        this,
        SwitchTargetDirection.X > 0.f ? DkGameplayTags::Player_Event_SwitchTarget_Right : DkGameplayTags::Player_Event_SwitchTarget_Left,
        FGameplayEventData{}
    );
}
References SwitchTargetDirection.
Referenced by SetupPlayerInputComponent().
Input_SwitchTargetTriggered()
void ADkHero::Input_SwitchTargetTriggered (const FInputActionValue & Value) private
Callback to handle target switching input when triggered during target lock.
{
    SwitchTargetDirection = Value.Get<FVector2D>();
}
References SwitchTargetDirection.
Referenced by SetupPlayerInputComponent().
PossessedBy()
void ADkHero::PossessedBy (AController * NewController) override protected virtual
Virtual function from ACharacter that must be overridden.
Reimplemented from ADkCharacterBase.
{
    Super::PossessedBy(NewController);
    if (!CharacterStartUpData.IsNull()) // Don't use `IsValid()` here to allow soft object pointer loading
    {
        if (UDkDataAsset_StartUpDataBase * LoadedData{ CharacterStartUpData.LoadSynchronous() })
        {
            int32 AbilityApplyLevel{};
            if (ADkGameModeBase * BaseGameMode{ GetWorld()->GetAuthGameMode<ADkGameModeBase>() })
            {
                switch (BaseGameMode->GetGameDifficultyLevel())
                {
                    // The higher the difficulty, the lower the ability apply level (abilities less effective, attributes less generous)
                    case EDkGameDifficultyLevel::Easy:      AbilityApplyLevel = 4; break;
                    case EDkGameDifficultyLevel::Normal:    AbilityApplyLevel = 3; break;
                    case EDkGameDifficultyLevel::Hard:      AbilityApplyLevel = 2; break;
                    case EDkGameDifficultyLevel::Extreme:   AbilityApplyLevel = 1; break;
                    default: break;
                }
#if 0
                // Debug message for difficulty level
                switch(BaseGameMode->GetGameDifficultyLevel())
                {
                    case EDkGameDifficultyLevel::Easy:      Debug::Print(TEXT("Game Difficulty Level: Easy"), FColor::Green); break;
                    case EDkGameDifficultyLevel::Normal:    Debug::Print(TEXT("Game Difficulty Level: Normal"), FColor::Yellow); break;
                    case EDkGameDifficultyLevel::Hard:      Debug::Print(TEXT("Game Difficulty Level: Hard"), FColor::Orange); break;
                    case EDkGameDifficultyLevel::Extreme:   Debug::Print(TEXT("Game Difficulty Level: Extreme"), FColor::Red); break;
                    default: break;
                }
#endif
            }
            // Grant abilities and startup effects to the ASC
            LoadedData->GiveToAbilitySystemComponent(DkAbilitySystemComponent, AbilityApplyLevel);
            // Update movement speed based on `GroundSpeed` attributes
            GetCharacterMovement()->MaxWalkSpeed = DkAttributeSet->GetGroundSpeed();
        }
    }
}
References ADkCharacterBase::CharacterStartUpData, ADkCharacterBase::DkAbilitySystemComponent, ADkCharacterBase::DkAttributeSet, Easy, Extreme, Hard, Normal, and Debug::Print().
SetupPlayerInputComponent()
void ADkHero::SetupPlayerInputComponent (class UInputComponent * PlayerInputComponent) override protected virtual
Binds callbacks to input actions.
{
    checkf(InputConfigDataAsset, TEXT("InputConfigDataAsset is not assigned in %s"), *GetName());
    ULocalPlayer* LocalPlayer{ GetController<APlayerController>()->GetLocalPlayer() };
    UEnhancedInputLocalPlayerSubsystem* SubSystem{ ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(LocalPlayer) };
    checkf(SubSystem, TEXT("Enhanced Input Subsystem is missing from Local Player!"));
    // Add default mapping context with default priority.
    // Any Gameplay Ability that adds a mapping context will do so with a higher priority.
    SubSystem->AddMappingContext(InputConfigDataAsset->DefaultMappingContext, UDkRPGFunctionLibrary::GetHeroDefaultInputMappingContextPriority());
    UDkInputComponent* DkInputComponent{ CastChecked<UDkInputComponent>(PlayerInputComponent) };
    DkInputComponent->BindNativeInputAction(InputConfigDataAsset, DkGameplayTags::Input_Move, ETriggerEvent::Triggered, this, &ADkHero::Input_Move);
    DkInputComponent->BindNativeInputAction(InputConfigDataAsset, DkGameplayTags::Input_Look, ETriggerEvent::Triggered, this, &ADkHero::Input_Look);
    DkInputComponent->BindNativeInputAction(InputConfigDataAsset, DkGameplayTags::Input_SwitchTarget, ETriggerEvent::Triggered, this, &ADkHero::Input_SwitchTargetTriggered);
    DkInputComponent->BindNativeInputAction(InputConfigDataAsset, DkGameplayTags::Input_SwitchTarget, ETriggerEvent::Completed, this, &ADkHero::Input_SwitchTargetCompleted);
    DkInputComponent->BindNativeInputAction(InputConfigDataAsset, DkGameplayTags::Input_PickUp_Stones, ETriggerEvent::Started, this, &ADkHero::Input_PickUp_Stones_Started);
    DkInputComponent->BindAbilityInputAction(InputConfigDataAsset, this, &ADkHero::Input_AbilityInputPressed, &ADkHero::Input_AbilityInputReleased);
}
References UDkInputComponent::BindAbilityInputAction(), UDkInputComponent::BindNativeInputAction(), UDkRPGFunctionLibrary::GetHeroDefaultInputMappingContextPriority(), Input_AbilityInputPressed(), Input_AbilityInputReleased(), Input_Look(), Input_Move(), Input_PickUp_Stones_Started(), Input_SwitchTargetCompleted(), Input_SwitchTargetTriggered(), and InputConfigDataAsset.
Member Data Documentation
CameraBoom
TObjectPtr<USpringArmComponent> ADkHero::CameraBoom private
Camera boom positioning the camera behind the character.
Referenced by ADkHero().
FollowCamera
TObjectPtr<UCameraComponent> ADkHero::FollowCamera private
Follow camera.
Referenced by ADkHero().
HeroCombatComponent
TObjectPtr<UDkHeroCombatComponent> ADkHero::HeroCombatComponent private
Handles combat-related functionality.
Referenced by ADkHero(), GetHeroCombatComponent(), and GetPawnCombatComponent().
HeroUIComponent
TObjectPtr<UDkHeroUIComponent> ADkHero::HeroUIComponent private
UI component for handling user interface interactions.
Referenced by ADkHero(), GetHeroUIComponent(), and GetPawnUIComponent().
InputConfigDataAsset
TObjectPtr<UDkDataAsset_InputConfig> ADkHero::InputConfigDataAsset private
Input configuration data asset used to define character input mappings.
Referenced by SetupPlayerInputComponent().
SwitchTargetDirection
FVector2D ADkHero::SwitchTargetDirection { FVector2D::ZeroVector } private
Cached direction for switching targets during target lock.
{ FVector2D::ZeroVector };
Referenced by Input_SwitchTargetCompleted(), and Input_SwitchTargetTriggered().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Characters/DkHero.h
D:/DkRPG/Source/DkRPG/Characters/DkHero.cpp