DkRPG: UDkWidgetBase Class Reference
UDkWidgetBase Class Reference
Base widget class that binds to events from the owning Pawn UI component.
#include <DkWidgetBase.h>
Public Member Functions
void InitEnemyCreateWidget (AActor *OwningEnemyActor)
Calls the Blueprint version.
Protected Member Functions
virtual void NativeOnInitialized () override
Called once when the widget is initialized.
void BP_OnOwningHeroUIComponentInitialized (UDkHeroUIComponent *OwningHeroUIComponent)
To be overridden in Widget Blueprints.
void BP_OnOwningEnemyUIComponentInitialized (UDkEnemyUIComponent *OwningEnemyUIComponent)
To be overridden in Widget Blueprints.
Detailed Description
Base widget class that binds to events from the owning Pawn UI component.
Blueprint of this will bind to delegates/events from the owning Pawn UI Component when initialized.
Member Function Documentation
BP_OnOwningEnemyUIComponentInitialized()
void UDkWidgetBase::BP_OnOwningEnemyUIComponentInitialized (UDkEnemyUIComponent * OwningEnemyUIComponent) protected
To be overridden in Widget Blueprints.
References BP_OnOwningEnemyUIComponentInitialized(), and InitEnemyCreateWidget().
Referenced by BP_OnOwningEnemyUIComponentInitialized(), and InitEnemyCreateWidget().
BP_OnOwningHeroUIComponentInitialized()
void UDkWidgetBase::BP_OnOwningHeroUIComponentInitialized (UDkHeroUIComponent * OwningHeroUIComponent) protected
To be overridden in Widget Blueprints.
References BP_OnOwningHeroUIComponentInitialized().
Referenced by BP_OnOwningHeroUIComponentInitialized(), and NativeOnInitialized().
InitEnemyCreateWidget()
void UDkWidgetBase::InitEnemyCreateWidget (AActor * OwningEnemyActor)
Calls the Blueprint version.
{
    if (IDkPawnUIInterface * PawnUIInterface{ Cast<IDkPawnUIInterface>(OwningEnemyActor) })
    {
        UDkEnemyUIComponent* EnemyUIComponent{ PawnUIInterface->GetEnemyUIComponent() };
        checkf(EnemyUIComponent, TEXT("From %s 's UDkWidgetBase::InitEnemyCreateWidget : Invalid EnemyUIComponent!"), *OwningEnemyActor->GetActorNameOrLabel());
        BP_OnOwningEnemyUIComponentInitialized(EnemyUIComponent);
    }
}
References BP_OnOwningEnemyUIComponentInitialized().
Referenced by BP_OnOwningEnemyUIComponentInitialized().
NativeOnInitialized()
void UDkWidgetBase::NativeOnInitialized () override protected virtual
Called once when the widget is initialized.
{
    Super::NativeOnInitialized();
    if (IDkPawnUIInterface * PawnUIInterface{ Cast<IDkPawnUIInterface>(GetOwningPlayerPawn()) })
    {
        if (UDkHeroUIComponent * HeroUIComponent{ PawnUIInterface->GetHeroUIComponent() })
        {
            BP_OnOwningHeroUIComponentInitialized(HeroUIComponent);
        }
    }
}
References BP_OnOwningHeroUIComponentInitialized().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Widgets/DkWidgetBase.h
D:/DkRPG/Source/DkRPG/Widgets/DkWidgetBase.cpp