DkRPG: UDkAttributeSet Class Reference
UDkAttributeSet Class Reference
Attribute set containing gameplay attributes shared by heroes and enemies.
#include <DkAttributeSet.h>
Public Member Functions
virtual void PostGameplayEffectExecute (const struct FGameplayEffectModCallbackData &Data) override
Called just before a GameplayEffect is executed to modify the base value of an attribute. No more changes can be made.
Private Attributes
TWeakInterfacePtr< IDkPawnUIInterface > CachedPawnUIInterface
Cached pointer to the IDkPawnUIInterface of the owning pawn, for quick access.
Main Attributes
FGameplayAttributeData CurrentHealth
FGameplayAttributeData WitherHealth
FGameplayAttributeData MaxHealth
FGameplayAttributeData CurrentRage
FGameplayAttributeData MaxRage
FGameplayAttributeData CurrentStamina
FGameplayAttributeData MaxStamina
FGameplayAttributeData GroundSpeed
FGameplayAttributeData AttackPower
FGameplayAttributeData DefensePower
ATTRIBUTE_ACCESSORS (UDkAttributeSet, CurrentHealth)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, WitherHealth)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, MaxHealth)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, CurrentRage)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, MaxRage)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, CurrentStamina)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, MaxStamina)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, GroundSpeed)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, AttackPower)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, DefensePower)
Temporary Attributes
FGameplayAttributeData DamageTaken
Temporarily holds damage taken during a GEEC, from which both current and wither health will be subtracted.
FGameplayAttributeData DamageWithered
Temporarily holds damage blocked during a GEEC, from which current health will be subtracted.
FGameplayAttributeData DamageBlocked
Temporarily holds damage blocked during a GEEC, from which current stamina will be subtracted.
ATTRIBUTE_ACCESSORS (UDkAttributeSet, DamageTaken)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, DamageWithered)
ATTRIBUTE_ACCESSORS (UDkAttributeSet, DamageBlocked)
Detailed Description
Attribute set containing gameplay attributes shared by heroes and enemies.
Note
Every attribute is meant to be modified via Gameplay Effects and not directly.
Member Function Documentation
ATTRIBUTE_ACCESSORS() [1/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , AttackPower)
References AttackPower, and ATTRIBUTE_ACCESSORS().
ATTRIBUTE_ACCESSORS() [2/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , CurrentHealth)
References ATTRIBUTE_ACCESSORS(), and CurrentHealth.
Referenced by ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), ATTRIBUTE_ACCESSORS(), and ATTRIBUTE_ACCESSORS().
ATTRIBUTE_ACCESSORS() [3/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , CurrentRage)
References ATTRIBUTE_ACCESSORS(), and CurrentRage.
ATTRIBUTE_ACCESSORS() [4/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , CurrentStamina)
References ATTRIBUTE_ACCESSORS(), and CurrentStamina.
ATTRIBUTE_ACCESSORS() [5/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , DamageBlocked)
References ATTRIBUTE_ACCESSORS(), and DamageBlocked.
ATTRIBUTE_ACCESSORS() [6/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , DamageTaken)
References ATTRIBUTE_ACCESSORS(), and DamageTaken.
ATTRIBUTE_ACCESSORS() [7/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , DamageWithered)
References ATTRIBUTE_ACCESSORS(), and DamageWithered.
ATTRIBUTE_ACCESSORS() [8/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , DefensePower)
References ATTRIBUTE_ACCESSORS(), and DefensePower.
ATTRIBUTE_ACCESSORS() [9/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , GroundSpeed)
References ATTRIBUTE_ACCESSORS(), and GroundSpeed.
ATTRIBUTE_ACCESSORS() [10/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , MaxHealth)
References ATTRIBUTE_ACCESSORS(), and MaxHealth.
ATTRIBUTE_ACCESSORS() [11/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , MaxRage)
References ATTRIBUTE_ACCESSORS(), and MaxRage.
ATTRIBUTE_ACCESSORS() [12/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , MaxStamina)
References ATTRIBUTE_ACCESSORS(), and MaxStamina.
ATTRIBUTE_ACCESSORS() [13/13]
UDkAttributeSet::ATTRIBUTE_ACCESSORS (UDkAttributeSet , WitherHealth)
References ATTRIBUTE_ACCESSORS(), and WitherHealth.
PostGameplayEffectExecute()
void UDkAttributeSet::PostGameplayEffectExecute (const struct FGameplayEffectModCallbackData & Data) override virtual
Called just before a GameplayEffect is executed to modify the base value of an attribute. No more changes can be made.
Override to implement custom logic.
{
    // Retrieve Pawn UI Interface and Component to notify about attribute changes
    if (!CachedPawnUIInterface.IsValid())
    {
        CachedPawnUIInterface = TWeakInterfacePtr<IDkPawnUIInterface>(Data.Target.GetAvatarActor());
    }
    checkf(CachedPawnUIInterface.IsValid(),
        TEXT("In %s 's UDkAttributeSet::PostGameplayEffectExecute: CachedPawnUIInterface is invalid!"),
        *Data.Target.GetAvatarActor()->GetActorNameOrLabel());
    UDkPawnUIComponent* PawnUIComponent{ CachedPawnUIInterface->GetPawnUIComponent() };
    checkf(PawnUIComponent,
        TEXT("In %s 's UDkAttributeSet::PostGameplayEffectExecute: PawnUIComponent is null!"),
        *Data.Target.GetAvatarActor()->GetActorNameOrLabel());
    // Handle Health changes
    if (Data.EvaluatedData.Attribute == GetCurrentHealthAttribute())
    {
        const float NewCurrentHealth{ FMath::Clamp(GetCurrentHealth(),  0.f,  GetMaxHealth()) };
        SetCurrentHealth(NewCurrentHealth);
        PawnUIComponent->OnCurrentHealthChanged.Broadcast(NewCurrentHealth / GetMaxHealth());
    }
    // Handle Wither Health changes
    if (Data.EvaluatedData.Attribute == GetWitherHealthAttribute())
    {
        const float NewWitherHealth{ FMath::Clamp(GetWitherHealth(), 0.f, GetMaxHealth()) };
        SetWitherHealth(NewWitherHealth);
        if (UDkHeroUIComponent * HeroUIComponent{ Cast<UDkHeroUIComponent>(PawnUIComponent) })
        {
            HeroUIComponent->OnWitherHealthChanged.Broadcast(NewWitherHealth / GetMaxHealth());
        }
    }
    // Handle Rage changes
    if (Data.EvaluatedData.Attribute == GetCurrentRageAttribute())
    {
        const float NewCurrentRage{ FMath::Clamp(GetCurrentRage(), 0.f, GetMaxRage()) };
        SetCurrentRage(NewCurrentRage);
        // Update Rage status (full/empty) accordingly via tags
        if (NewCurrentRage == GetMaxRage())
        {
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Rage_Full);
        }
        else if (NewCurrentRage == 0.f)
        {
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Rage_Empty);
        }
        else
        {
            UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Rage_Full);
            UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Rage_Empty);
        }
        if (UDkHeroUIComponent * HeroUIComponent{ Cast<UDkHeroUIComponent>(PawnUIComponent) })
        {
            HeroUIComponent->OnCurrentRageChanged.Broadcast(NewCurrentRage / GetMaxRage());
        }
    }
    // Handle Stamina changes
    if (Data.EvaluatedData.Attribute == GetCurrentStaminaAttribute())
    {
        const float NewCurrentStamina{ FMath::Clamp(GetCurrentStamina(), 0.f, GetMaxStamina()) };
        SetCurrentStamina(NewCurrentStamina);
        // Update Stamina status (full/empty) accordingly via tags
        if (GetCurrentStamina() == GetMaxStamina())
        {
            UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Stamina_NotFull);
        }
        else if (GetCurrentStamina() == 0.f)
        {
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Stamina_Empty);
        }
        else
        {
            UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Stamina_Empty);
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Player_Status_Stamina_NotFull);
        }
        if (UDkHeroUIComponent * HeroUIComponent{ Cast<UDkHeroUIComponent>(PawnUIComponent) })
        {
            HeroUIComponent->OnCurrentStaminaChanged.Broadcast(GetCurrentStamina() / GetMaxStamina());
        }
    }
    // Handle Speed changes
    if (Data.EvaluatedData.Attribute == GetGroundSpeedAttribute())
    {
        if (ADkHero * Hero{ Cast<ADkHero>(GetOwningActor()) })
        {
            if (UCharacterMovementComponent * MovementComponent{ Hero->GetCharacterMovement() })
            {
                MovementComponent->MaxWalkSpeed = GetGroundSpeed();
            }
        }
    }
    // Handle Damage Taken
    if (Data.EvaluatedData.Attribute == GetDamageTakenAttribute())
    {
        const float NewCurrentHealth{ FMath::Clamp(GetCurrentHealth() - GetDamageTaken(),0.f,GetMaxHealth()) };
        SetCurrentHealth(NewCurrentHealth);
        SetWitherHealth(NewCurrentHealth); // Sync WitherHealth with CurrentHealth on damage taken
        PawnUIComponent->OnCurrentHealthChanged.Broadcast(NewCurrentHealth / GetMaxHealth());
        if (UDkHeroUIComponent * HeroUIComponent{ Cast<UDkHeroUIComponent>(PawnUIComponent) })
        {
            HeroUIComponent->OnWitherHealthChanged.Broadcast(NewCurrentHealth / GetMaxHealth());
        }
        if (GetCurrentHealth() == 0.f)
        {
            // Trigger death ability
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Shared_Status_Death);
        }
    }
    // Handle Recoverable Damage Taken
    if (Data.EvaluatedData.Attribute == GetDamageWitheredAttribute())
    {
        const float NewCurrentHealth{ FMath::Clamp(GetCurrentHealth() - GetDamageWithered(),0.f,GetWitherHealth()) };
        SetCurrentHealth(NewCurrentHealth);
        PawnUIComponent->OnCurrentHealthChanged.Broadcast(NewCurrentHealth / GetMaxHealth());
        if (GetCurrentHealth() == 0.f)
        {
            // Trigger death ability
            UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(Data.Target.GetAvatarActor(), DkGameplayTags::Shared_Status_Death);
        }
    }
    // Handle Damage Blocked
    if (Data.EvaluatedData.Attribute == GetDamageBlockedAttribute())
    {
        const float NewCurrentStamina{ FMath::Clamp(GetCurrentStamina() - GetDamageBlocked(),0.f,GetMaxStamina()) };
        SetCurrentStamina(NewCurrentStamina);
        if (UDkHeroUIComponent * HeroUIComponent{ Cast<UDkHeroUIComponent>(PawnUIComponent) })
        {
            HeroUIComponent->OnCurrentStaminaChanged.Broadcast(NewCurrentStamina / GetMaxStamina());
        }
    }
}
References UDkRPGFunctionLibrary::AddGameplayTagToActorIfNone(), CachedPawnUIInterface, UDkPawnUIComponent::OnCurrentHealthChanged, and UDkRPGFunctionLibrary::RemoveGameplayTagFromActorIfFound().
Member Data Documentation
AttackPower
FGameplayAttributeData UDkAttributeSet::AttackPower
Referenced by ATTRIBUTE_ACCESSORS().
CachedPawnUIInterface
TWeakInterfacePtr<IDkPawnUIInterface> UDkAttributeSet::CachedPawnUIInterface private
Cached pointer to the IDkPawnUIInterface of the owning pawn, for quick access.
Referenced by PostGameplayEffectExecute().
CurrentHealth
FGameplayAttributeData UDkAttributeSet::CurrentHealth
Referenced by ATTRIBUTE_ACCESSORS().
CurrentRage
FGameplayAttributeData UDkAttributeSet::CurrentRage
Referenced by ATTRIBUTE_ACCESSORS().
CurrentStamina
FGameplayAttributeData UDkAttributeSet::CurrentStamina
Referenced by ATTRIBUTE_ACCESSORS().
DamageBlocked
FGameplayAttributeData UDkAttributeSet::DamageBlocked
Temporarily holds damage blocked during a GEEC, from which current stamina will be subtracted.
Referenced by ATTRIBUTE_ACCESSORS().
DamageTaken
FGameplayAttributeData UDkAttributeSet::DamageTaken
Temporarily holds damage taken during a GEEC, from which both current and wither health will be subtracted.
Referenced by ATTRIBUTE_ACCESSORS().
DamageWithered
FGameplayAttributeData UDkAttributeSet::DamageWithered
Temporarily holds damage blocked during a GEEC, from which current health will be subtracted.
If positive, indicates amount of damage that was blocked and should be applied as wither health. If negative, indicates amount of wither health that should be recovered.
Referenced by ATTRIBUTE_ACCESSORS().
DefensePower
FGameplayAttributeData UDkAttributeSet::DefensePower
Referenced by ATTRIBUTE_ACCESSORS().
GroundSpeed
FGameplayAttributeData UDkAttributeSet::GroundSpeed
Referenced by ATTRIBUTE_ACCESSORS().
MaxHealth
FGameplayAttributeData UDkAttributeSet::MaxHealth
Referenced by ATTRIBUTE_ACCESSORS().
MaxRage
FGameplayAttributeData UDkAttributeSet::MaxRage
Referenced by ATTRIBUTE_ACCESSORS().
MaxStamina
FGameplayAttributeData UDkAttributeSet::MaxStamina
Referenced by ATTRIBUTE_ACCESSORS().
WitherHealth
FGameplayAttributeData UDkAttributeSet::WitherHealth
Referenced by ATTRIBUTE_ACCESSORS().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/DkAttributeSet.h
D:/DkRPG/Source/DkRPG/AbilitySystem/DkAttributeSet.cpp