DkRPG: ADkWeaponBase Class Reference
ADkWeaponBase Class Reference
Base class for all weapons, providing mesh, collision, and damage detection functionality.
#include <DkWeaponBase.h>
Public Member Functions
ADkWeaponBase ()
FORCEINLINE UStaticMeshComponent * GetWeaponMesh () const
Getter for the weapon mesh.
FORCEINLINE UBoxComponent * GetWeaponCollisionBox () const
Getter for the weapon collision box.
Public Attributes
FOnTargetInteractedAtLocationDelegate OnWeaponHitTarget
Delegate called on begin overlap.
FOnTargetInteractedDelegate OnWeaponPulledFromTarget
Delegate called on end overlap.
Protected Member Functions
virtual void OnCollisionBoxBeginOverlap (UPrimitiveComponent *OverlappedComponent, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
Callback when weapon collision box begins overlap with another actor/component.
virtual void OnCollisionBoxEndOverlap (UPrimitiveComponent *OverlappedComponent, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex)
Callback when weapon collision box ends overlap with another actor/component.
Protected Attributes
TObjectPtr< UStaticMeshComponent > WeaponMesh
Mesh component for the weapon.
TObjectPtr< UBoxComponent > WeaponCollisionBox
Collision box for the weapon.
Detailed Description
Base class for all weapons, providing mesh, collision, and damage detection functionality.
Note
All weapon-related task (e.g. spawning one, attaching to mesh, equip/unequip, etc.) are carried out via Gameplay abilities, each of which is a subclassed BP.
Constructor & Destructor Documentation
ADkWeaponBase()
ADkWeaponBase::ADkWeaponBase ()
{
    PrimaryActorTick.bCanEverTick = false;
    WeaponMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("WeaponMesh"));
    SetRootComponent(WeaponMesh);
    WeaponCollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("WeaponCollisionBox"));
    WeaponCollisionBox->SetupAttachment(GetRootComponent());
    WeaponCollisionBox->SetBoxExtent(FVector{ 20.f });
    WeaponCollisionBox->SetCollisionEnabled(ECollisionEnabled::NoCollision); // We'll enable collision upon damage detection
    WeaponCollisionBox->OnComponentBeginOverlap.AddUniqueDynamic(this, &ADkWeaponBase::OnCollisionBoxBeginOverlap);
    WeaponCollisionBox->OnComponentEndOverlap.AddUniqueDynamic(this, &ADkWeaponBase::OnCollisionBoxEndOverlap);
}
References OnCollisionBoxBeginOverlap(), OnCollisionBoxEndOverlap(), WeaponCollisionBox, and WeaponMesh.
Member Function Documentation
GetWeaponCollisionBox()
FORCEINLINE UBoxComponent * ADkWeaponBase::GetWeaponCollisionBox () const inline
Getter for the weapon collision box.
{ return WeaponCollisionBox; }
References WeaponCollisionBox.
Referenced by UDkPawnCombatComponent::ToggleCurrentEquippedWeaponCollision().
GetWeaponMesh()
FORCEINLINE UStaticMeshComponent * ADkWeaponBase::GetWeaponMesh () const inline
Getter for the weapon mesh.
{ return WeaponMesh; }
References GetWeaponMesh(), and WeaponMesh.
Referenced by GetWeaponMesh().
OnCollisionBoxBeginOverlap()
void ADkWeaponBase::OnCollisionBoxBeginOverlap (UPrimitiveComponent * OverlappedComponent, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) protected virtual
Callback when weapon collision box begins overlap with another actor/component.
Note
Overlaps are just volume intersections, not physical hits. SweepResult.bBlockingHit will be false, thus we will not be able to get an accurate hit location from the SweepResult. Thus, we will perform a line trace to get a more accurate hit location.
Warning
Currently we know both player and enemy characters are of Pawn type, but what if not?
{
    APawn* WeaponOwningPawn{ GetInstigator<APawn>() };
    checkf(WeaponOwningPawn, TEXT("Forgot to assign an instigator as the owning pawn of the weapon: %s."), *GetName());
    if (APawn * HitPawn{ Cast<APawn>(OtherActor) })
    {
        if (UDkRPGFunctionLibrary::IsTargetPawnHostile(WeaponOwningPawn, HitPawn))
        {
            if (SweepResult.bBlockingHit) // We won't proceed to here.
            {
                OnWeaponHitTarget.ExecuteIfBound(OtherActor, SweepResult.ImpactPoint);
            }
            else
            {
                // Perform a line trace from the weapon to the target pawn to get a more accurate hit location
                FCollisionObjectQueryParams ObjectQueryParams;
                ObjectQueryParams.AddObjectTypesToQuery(ECollisionChannel::ECC_Pawn);
                FCollisionQueryParams QueryParams;
                QueryParams.AddIgnoredActor(this); // Ignore this actor
                QueryParams.bTraceComplex = false; // Use simple collision
                FVector TraceStart{ OverlappedComponent->GetComponentLocation() };
                FVector TraceEnd{ OtherComp->GetComponentLocation() };
                FHitResult TracedHitResult;
                if (GetWorld()->LineTraceSingleByObjectType(
                    TracedHitResult, TraceStart, TraceEnd, ObjectQueryParams, QueryParams
                ))
                {
                    OnWeaponHitTarget.ExecuteIfBound(OtherActor, TracedHitResult.ImpactPoint);
                }
                else
                {
                    FVector FallbackLocation{ OtherComp->GetComponentLocation() };
                    OnWeaponHitTarget.ExecuteIfBound(OtherActor, FallbackLocation);
                }
            }
        }
    }
}
References UDkRPGFunctionLibrary::IsTargetPawnHostile(), and OnWeaponHitTarget.
Referenced by ADkWeaponBase().
OnCollisionBoxEndOverlap()
void ADkWeaponBase::OnCollisionBoxEndOverlap (UPrimitiveComponent * OverlappedComponent, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex) protected virtual
Callback when weapon collision box ends overlap with another actor/component.
{
    APawn* WeaponOwningPawn{ GetInstigator<APawn>() };
    checkf(WeaponOwningPawn, TEXT("Forgot to assign an instigator as the owning pawn of the weapon: %s."), *GetName());
    if (APawn * HitPawn{ Cast<APawn>(OtherActor) })
    {
        if (UDkRPGFunctionLibrary::IsTargetPawnHostile(WeaponOwningPawn, HitPawn))
        {
            OnWeaponPulledFromTarget.ExecuteIfBound(OtherActor);
        }
    }
}
References UDkRPGFunctionLibrary::IsTargetPawnHostile(), and OnWeaponPulledFromTarget.
Referenced by ADkWeaponBase().
Member Data Documentation
OnWeaponHitTarget
FOnTargetInteractedAtLocationDelegate ADkWeaponBase::OnWeaponHitTarget
Delegate called on begin overlap.
Referenced by OnCollisionBoxBeginOverlap(), and UDkPawnCombatComponent::RegisterSpawnedWeapon().
OnWeaponPulledFromTarget
FOnTargetInteractedDelegate ADkWeaponBase::OnWeaponPulledFromTarget
Delegate called on end overlap.
Referenced by OnCollisionBoxEndOverlap(), and UDkPawnCombatComponent::RegisterSpawnedWeapon().
WeaponCollisionBox
TObjectPtr<UBoxComponent> ADkWeaponBase::WeaponCollisionBox protected
Collision box for the weapon.
Referenced by ADkWeaponBase(), and GetWeaponCollisionBox().
WeaponMesh
TObjectPtr<UStaticMeshComponent> ADkWeaponBase::WeaponMesh protected
Mesh component for the weapon.
Referenced by ADkWeaponBase(), and GetWeaponMesh().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Items/Weapons/DkWeaponBase.h
D:/DkRPG/Source/DkRPG/Items/Weapons/DkWeaponBase.cpp