DkRPG: UDkPawnExtensionComponentBase Class Reference
UDkPawnExtensionComponentBase Class Reference
Component responsible for handling general combat-related functionalities only, no actual combat logic.
#include <DkPawnExtensionComponentBase.h>
Protected Member Functions
template<class T>
T * GetOwningPawn () const
Gets the owning Pawn cast to the specified type T.
APawn * GetOwningPawn () const
Gets the owning Pawn as an APawn.
template<class T>
T * GetOwningController () const
Gets the controller of the owning Pawn cast to the specified type T.
Detailed Description
Component responsible for handling general combat-related functionalities only, no actual combat logic.
Member Function Documentation
GetOwningController()
template<class T> T * UDkPawnExtensionComponentBase::GetOwningController () const inline protected
Gets the controller of the owning Pawn cast to the specified type T.
Template Parameters
T The type to cast the controller to. Must be derived from AController.
Returns
A pointer to the controller of the owning Pawn cast to type T.
    {
        static_assert(TPointerIsConvertibleFromTo<T, AController>::Value, "Template type T must be derived from AController"); // Ensure T is a Controller or derived from Controller
        return GetOwningPawn<APawn>()->GetController<T>();
    }
References GetOwningPawn().
GetOwningPawn() [1/2]
APawn * UDkPawnExtensionComponentBase::GetOwningPawn () const inline protected
Gets the owning Pawn as an APawn.
Returns
A pointer to the owning Pawn as an APawn.
    {
        return GetOwningPawn<APawn>();
    }
References GetOwningPawn().
GetOwningPawn() [2/2]
template<class T> T * UDkPawnExtensionComponentBase::GetOwningPawn () const inline protected
Gets the owning Pawn cast to the specified type T.
Template Parameters
T The type to cast the owning Pawn to. Must be derived from APawn.
Returns
A pointer to the owning Pawn cast to type T.
    {
        static_assert(TPointerIsConvertibleFromTo<T, APawn>::Value, "Template type T must be derived from APawn"); // Ensure T is a Pawn or derived from Pawn
        return CastChecked<T>(GetOwner());
    }
Referenced by GetOwningController(), GetOwningPawn(), UDkEnemyCombatComponent::OnHitTargetActor(), UDkHeroCombatComponent::OnHitTargetActor(), UDkHeroCombatComponent::OnWeaponPulledFromTargetActor(), and UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision().
The documentation for this class was generated from the following file:
D:/DkRPG/Source/DkRPG/Components/DkPawnExtensionComponentBase.h