DkRPG: ADkPickUpStoneBase Class Reference
ADkPickUpStoneBase Class Reference
Base class for pickable stones. Blueprint subclasses represent specific stone types.
#include <DkPickUpStoneBase.h>
Public Member Functions
void Consume (UDkAbilitySystemComponent *ASC, int32 ApplyLevel)
Applies the stone's gameplay effect to the given ASC.
Public Member Functions inherited from ADkPickUpBase
ADkPickUpBase ()
Protected Member Functions
virtual void OnPickUpSphereBeginOverlap (UPrimitiveComponent *OverlappedComp, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult) override
Callback for when another actor begins overlapping with the pick-up collision sphere.
void BP_OnStoneConsumed ()
Event called when the stone has been consumed, handles the SFX and VFX upon picked up.
Protected Attributes
TSubclassOf< UGameplayEffect > StoneGameplayEffectClass
Gameplay Effect class applied to the player when this stone is consumed.
Protected Attributes inherited from ADkPickUpBase
TObjectPtr< USphereComponent > PickUpCollisionSphere
Used to detect player proximity for pick-up interaction.
Detailed Description
Base class for pickable stones. Blueprint subclasses represent specific stone types.
Member Function Documentation
BP_OnStoneConsumed()
void ADkPickUpStoneBase::BP_OnStoneConsumed () protected
Event called when the stone has been consumed, handles the SFX and VFX upon picked up.
References BP_OnStoneConsumed().
Referenced by BP_OnStoneConsumed(), and Consume().
Consume()
void ADkPickUpStoneBase::Consume (UDkAbilitySystemComponent * ASC, int32 ApplyLevel)
Applies the stone's gameplay effect to the given ASC.
{
    checkf(StoneGameplayEffectClass, TEXT("StoneGameplayEffectClass is not set in %s"), *GetName());
    UGameplayEffect* EffectCDO{ StoneGameplayEffectClass.GetDefaultObject() };
    ASC->ApplyGameplayEffectToSelf(EffectCDO, ApplyLevel, ASC->MakeEffectContext());
    BP_OnStoneConsumed();
}
References BP_OnStoneConsumed(), and StoneGameplayEffectClass.
OnPickUpSphereBeginOverlap()
void ADkPickUpStoneBase::OnPickUpSphereBeginOverlap (UPrimitiveComponent * OverlappedComp, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) override protected virtual
Callback for when another actor begins overlapping with the pick-up collision sphere.
Reimplemented from ADkPickUpBase.
{
    if (ADkHero * OverlappedHero{ Cast<ADkHero>(OtherActor) }) // Stones shall interact with Hero character only
    {
        UDkPickUpItemInteractedAdditionalInfo* AdditionalInfo{ NewObject<UDkPickUpItemInteractedAdditionalInfo>() };
        AdditionalInfo->SetPickUpItemLocation(GetActorLocation()); // Pass additional info about the pick-up item location
        FGameplayEventData EventData;
        EventData.OptionalObject = AdditionalInfo;
        UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(
            OverlappedHero,
            DkGameplayTags::Player_Ability_PickUp_Stones,
            EventData
        );
    }
}
References UDkPickUpItemInteractedAdditionalInfo::SetPickUpItemLocation().
Member Data Documentation
StoneGameplayEffectClass
TSubclassOf<UGameplayEffect> ADkPickUpStoneBase::StoneGameplayEffectClass protected
Gameplay Effect class applied to the player when this stone is consumed.
Referenced by Consume().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Items/PickUps/DkPickUpStoneBase.h
D:/DkRPG/Source/DkRPG/Items/PickUps/DkPickUpStoneBase.cpp