DkRPG: UDkGEEC_DamageTaken Class Reference
UDkGEEC_DamageTaken Class Reference
Implements calculation logic related to damage taken by both the player and enemy characters.
#include <DkGEEC_DamageTaken.h>
Public Member Functions
UDkGEEC_DamageTaken ()
Captures necessary attributes and tags for damage calculation.
virtual void Execute_Implementation (const FGameplayEffectCustomExecutionParameters &ExecutionParams, FGameplayEffectCustomExecutionOutput &OutExecutionOutput) const override
Called when the GE using this execution is applied to a target.
Private Member Functions
float CalculateDamage (int SourceLightAttackComboCount, int SourceHeavyAttackComboCount, float SourceBaseDamage, float SourceAttackPower, float TargetDefensePower) const
Implements logic for damage calculation.
float CalculateStaminaDeduction (float BlockedDamageAmount) const
Calculates the amount of stamina to deduct based on the amount of damage blocked.
float CalculateHealthWithered (float BlockedDamageAmount) const
Calculates the amount of wither health based on the amount of damage blocked.
float CalculateHealthRecovered (float DamageDealtAmount) const
Calculates the amount of wither health to recover based on the amount of damage dealt.
Detailed Description
Implements calculation logic related to damage taken by both the player and enemy characters.
Four calculations are implemented within this class:
CalculateDamage() How much damage to deal, based on attacker's base damage, attack power, target's defense power and combo multipliers
CalculateStaminaDeduction() How much stamina to deduct when blocking an attack, based on the amount of damage blocked
CalculateHealthWithered() How much wither health to apply when blocking an attack, based on the amount of damage blocked
CalculateHealthRecovered() How much wither health to recover when dealing damage, based on the amount of damage dealt
Note
When applying damage to Player Character, this class is executed twice:
When the damage GE is applied to the player character, this class applies health reduction if the attack is not being blocked or if the player doesn't have enough stamina to block the attack
When the player character's blocking GA receives the event that the attack is successfully blocked, this class applies stamina reduction & health withering if it is not a perfect block (i.e. a parry).
When applying damage to Enemy Characters, this class is executed twice:
When the damage GE is applied to an enemy character, this class applies health reduction
Then, apply on the player character to recover wither health based on the damage dealt
Constructor & Destructor Documentation
UDkGEEC_DamageTaken()
UDkGEEC_DamageTaken::UDkGEEC_DamageTaken ()
Captures necessary attributes and tags for damage calculation.
{
    RelevantAttributesToCapture.Add(GetDkDamageCapture().AttackPowerDef);
    RelevantAttributesToCapture.Add(GetDkDamageCapture().DefensePowerDef);
    RelevantAttributesToCapture.Add(GetDkDamageCapture().CurrentStaminaDef);
}
References GetDkDamageCapture().
Member Function Documentation
CalculateDamage()
float UDkGEEC_DamageTaken::CalculateDamage (int SourceLightAttackComboCount, int SourceHeavyAttackComboCount, float SourceBaseDamage, float SourceAttackPower, float TargetDefensePower) const private
Implements logic for damage calculation.
{
    if (SourceLightAttackComboCount > 0)
    {
        // Increase damage by 5% per light attack in the combo
        SourceBaseDamage *= (1.0f + 0.05f * SourceLightAttackComboCount);
    }
    if (SourceHeavyAttackComboCount > 0)
    {
        // Increase damage by 10% per heavy attack in the combo
        SourceBaseDamage *= (1.0f + 0.10f * SourceHeavyAttackComboCount);
    }
    return SourceBaseDamage * SourceAttackPower / TargetDefensePower;
}
Referenced by Execute_Implementation().
CalculateHealthRecovered()
float UDkGEEC_DamageTaken::CalculateHealthRecovered (float DamageDealtAmount) const private
Calculates the amount of wither health to recover based on the amount of damage dealt.
When the player deals damage to an enemy, they recover wither health based on the damage dealt.
Note
For now, simply returns with ratio 1:1. More complex formulas can be implemented here.
{
    return DamageDealtAmount;
}
Referenced by Execute_Implementation().
CalculateHealthWithered()
float UDkGEEC_DamageTaken::CalculateHealthWithered (float BlockedDamageAmount) const private
Calculates the amount of wither health based on the amount of damage blocked.
When the player takes damage while blocking, their health is "withered" instead of reduced, given they have enough stamina to block the attack.
Note
For now, simply returns with ratio 1:1. More complex formulas can be implemented here.
{
    return BlockedDamageAmount;
}
Referenced by Execute_Implementation().
CalculateStaminaDeduction()
float UDkGEEC_DamageTaken::CalculateStaminaDeduction (float BlockedDamageAmount) const private
Calculates the amount of stamina to deduct based on the amount of damage blocked.
When the player takes damage while blocking, they lose stamina instead of health, given they have enough stamina to block the attack.
Note
For now, simply returns with ratio 1:1. More complex formulas can be implemented here.
{
    return BlockedDamageAmount;
}
Referenced by Execute_Implementation().
Execute_Implementation()
void UDkGEEC_DamageTaken::Execute_Implementation (const FGameplayEffectCustomExecutionParameters & ExecutionParams, FGameplayEffectCustomExecutionOutput & OutExecutionOutput) const override virtual
Called when the GE using this execution is applied to a target.
{
    const FGameplayEffectSpec& EffectSpec = ExecutionParams.GetOwningSpec();
    FAggregatorEvaluateParameters EvaluateParams;
    EvaluateParams.SourceTags = EffectSpec.CapturedSourceTags.GetAggregatedTags(); // Tags from the source (the attacker)
    EvaluateParams.TargetTags = EffectSpec.CapturedTargetTags.GetAggregatedTags(); // Tags from the target (the one being attacked)
    // Attributes to capture
    float SourceAttackPower{}, TargetDefensePower{}, TargetCurrentStamina{}, BaseDamage{};
    int32 LightAttackComboCount{}, HeavyAttackComboCount{};
    bool  bIsAttackBeingBlocked{}, bIsAttackSuccessfullyBlocked{}, bRecoverWitherHealth{};
    // Capture the attacker's Attack Power
    ExecutionParams.AttemptCalculateCapturedAttributeMagnitude(
        GetDkDamageCapture().AttackPowerDef,
        EvaluateParams,
        SourceAttackPower
    );
    // Capture the target's Defense Power
    ExecutionParams.AttemptCalculateCapturedAttributeMagnitude(
        GetDkDamageCapture().DefensePowerDef,
        EvaluateParams,
        TargetDefensePower
    );
    // Capture the target's Current Stamina
    ExecutionParams.AttemptCalculateCapturedAttributeMagnitude(
        GetDkDamageCapture().CurrentStaminaDef,
        EvaluateParams,
        TargetCurrentStamina
    );
    for (const TPair<FGameplayTag, float>& TagMagnitude : EffectSpec.SetByCallerTagMagnitudes)
    {
        if (TagMagnitude.Key.MatchesTagExact(DkGameplayTags::Shared_SetByCaller_BaseDamage))
        {
            BaseDamage = TagMagnitude.Value; // Capture the base damage
        }
        if (TagMagnitude.Key.MatchesTagExact(DkGameplayTags::Player_SetByCaller_AttackType_Light))
        {
            LightAttackComboCount = TagMagnitude.Value; // Capture the light attack combo count
        }
        if (TagMagnitude.Key.MatchesTagExact(DkGameplayTags::Player_SetByCaller_AttackType_Heavy))
        {
            HeavyAttackComboCount = TagMagnitude.Value; // Capture the heavy attack combo count
        }
        if (TagMagnitude.Key.MatchesTagExact(DkGameplayTags::Enemy_SetByCaller_AttackStatus))
        {
            if (TagMagnitude.Value == static_cast<int>(EDkEnemyAttackStatus::BeingBlocked))
            {
                bIsAttackBeingBlocked = true; // Capture whether the attack is being blocked
            }
            else if (TagMagnitude.Value == static_cast<int>(EDkEnemyAttackStatus::SuccessfullyBlocked))
            {
                bIsAttackSuccessfullyBlocked = true; // Capture whether the attack is successfully blocked
            }
        }
        if (TagMagnitude.Key.MatchesTagExact(DkGameplayTags::Player_Event_RecoverWitherHealth))
        {
            bRecoverWitherHealth = true; // Capture whether the player should recover wither health
        }
    }
    const float FinalDamage{
        CalculateDamage(LightAttackComboCount, HeavyAttackComboCount, BaseDamage, SourceAttackPower, TargetDefensePower)
    };
#if 0
    Debug::Print("  Source Attack Power: ", SourceAttackPower);
    Debug::Print("  Target Defense Power: ", TargetDefensePower);
    Debug::Print("  Base Damage: ", BaseDamage);
    Debug::Print("  Light Attack Combo Count: ", LightAttackComboCount);
    Debug::Print("  Heavy Attack Combo Count: ", HeavyAttackComboCount);
    Debug::Print("  Final Damage to Apply: ", FinalDamage);
#endif
    if (FinalDamage <= 0.f)
    {
        return; // No damage to apply
    }
    const float StaminaDeducted{ CalculateStaminaDeduction(FinalDamage) };
    const float HealthWithered{ CalculateHealthWithered(FinalDamage) };
    const float WitherHealthRecovered{ CalculateHealthRecovered(FinalDamage) };
    const bool  bIsStaminaSufficientToBlock{ TargetCurrentStamina >= StaminaDeducted };
    if (bRecoverWitherHealth)
    {
        OutExecutionOutput.AddOutputModifier(
            FGameplayModifierEvaluatedData{ GetDkDamageCapture().DamageWitheredProperty,EGameplayModOp::Override, -WitherHealthRecovered }
        ); // Apply health recovery from withered damage
    }
    else if (bIsStaminaSufficientToBlock && bIsAttackBeingBlocked)
    {
        // The attack can be and is being blocked, we don't apply anything yet.
    }
    else if (bIsStaminaSufficientToBlock && bIsAttackSuccessfullyBlocked)
    {
        OutExecutionOutput.AddOutputModifier(
            FGameplayModifierEvaluatedData{ GetDkDamageCapture().DamageBlockedProperty,EGameplayModOp::Override,StaminaDeducted }
        ); // Apply stamina deduction
        OutExecutionOutput.AddOutputModifier(
            FGameplayModifierEvaluatedData{ GetDkDamageCapture().DamageWitheredProperty,EGameplayModOp::Override,HealthWithered }
        ); // Apply withered damage to health
    }
    else
    {
        OutExecutionOutput.AddOutputModifier(
            FGameplayModifierEvaluatedData{ GetDkDamageCapture().DamageTakenProperty,EGameplayModOp::Override,FinalDamage }
        ); // Apply damage to health
    }
}
References BeingBlocked, CalculateDamage(), CalculateHealthRecovered(), CalculateHealthWithered(), CalculateStaminaDeduction(), GetDkDamageCapture(), Debug::Print(), and SuccessfullyBlocked.
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AbilitySystem/GEEC/DkGEEC_DamageTaken.h
D:/DkRPG/Source/DkRPG/AbilitySystem/GEEC/DkGEEC_DamageTaken.cpp