DkRPG: UDkBTTask_RotateToFaceTarget Class Reference
UDkBTTask_RotateToFaceTarget Class Reference
Rotates the AI-controlled character to face a specified target actor.
#include <DkBTTask_RotateToFaceTarget.h>
Private Member Functions
UDkBTTask_RotateToFaceTarget ()
Initializes values and configures the task node.
virtual EBTNodeResult::Type ExecuteTask (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory) override
Called at the start of this task.
virtual void TickTask (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, float DeltaSeconds) override
Called every tick while this task is running.
bool HasReachedAnglePrecision (APawn *QueryPawn, AActor *TargetActor) const
UBTNode interface
virtual void InitializeFromAsset (UBehaviorTree &Asset) override
Initializes the task from the behavior tree asset.
virtual uint16 GetInstanceMemorySize () const override
Returns the size of the instance memory struct that stores the states of this task.
virtual FString GetStaticDescription () const override
Displays a description of the task in the editor.
Private Attributes
float AnglePrecision
The threshold angle (in degrees) within which the rotation is considered complete.
float RotationInterpSpeed
The speed at which the character rotates towards the target.
FBlackboardKeySelector InTargetActorToFaceKey
Blackboard key selector for the target actor to face.
Detailed Description
Rotates the AI-controlled character to face a specified target actor.
Note
The default BTTask RotateToFaceBBEntry requires the AI character to have
bUseControllerDesiredRotation = true;
bOrientRotationToMovement = false;
which is exactly the opposite of our settings for character movement, hence this custom task.
Constructor & Destructor Documentation
UDkBTTask_RotateToFaceTarget()
UDkBTTask_RotateToFaceTarget::UDkBTTask_RotateToFaceTarget () private
Initializes values and configures the task node.
{
    NodeName = TEXT("Native Rotate to Face Target Actor");
    AnglePrecision = 10.f;
    RotationInterpSpeed = 5.f;
    bNotifyTick = true;
    bNotifyTaskFinished = true;
    bCreateNodeInstance = false; // States are stored in instance memory struct
    INIT_TASK_NODE_NOTIFY_FLAGS();
    InTargetActorToFaceKey.AddObjectFilter(
        this,
        GET_MEMBER_NAME_CHECKED(UDkBTTask_RotateToFaceTarget, InTargetActorToFaceKey),
        AActor::StaticClass() // Only accept keys of type `AActor`
    );
}
References AnglePrecision, InTargetActorToFaceKey, RotationInterpSpeed, and UDkBTTask_RotateToFaceTarget().
Referenced by UDkBTTask_RotateToFaceTarget().
Member Function Documentation
ExecuteTask()
EBTNodeResult::Type UDkBTTask_RotateToFaceTarget::ExecuteTask (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory) override private virtual
Called at the start of this task.
{
    UObject* ActorObject{ OwnerComp.GetBlackboardComponent()->GetValueAsObject(InTargetActorToFaceKey.SelectedKeyName) };
    AActor* TargetActor{ Cast<AActor>(ActorObject) };
    APawn* OwningPawn{ OwnerComp.GetAIOwner()->GetPawn() };
    FRotateToFaceTargetTaskMemory* Memory{ CastInstanceNodeMemory<FRotateToFaceTargetTaskMemory>(NodeMemory) };
    checkf(Memory, TEXT("Failed to cast instance memory to FRotateToFaceTargetTaskMemory"));
    // Store the states into the task memory
    Memory->OwningPawn = OwningPawn;
    Memory->TargetActor = TargetActor;
    if (!Memory->IsValid())
    {
        return EBTNodeResult::Failed;
    }
    if (HasReachedAnglePrecision(OwningPawn, TargetActor))
    {
        Memory->Reset();
        return EBTNodeResult::Succeeded;
    }
    return EBTNodeResult::InProgress; // continue in `TickTask`
}
References HasReachedAnglePrecision(), InTargetActorToFaceKey, FRotateToFaceTargetTaskMemory::IsValid(), FRotateToFaceTargetTaskMemory::OwningPawn, FRotateToFaceTargetTaskMemory::Reset(), and FRotateToFaceTargetTaskMemory::TargetActor.
GetInstanceMemorySize()
uint16 UDkBTTask_RotateToFaceTarget::GetInstanceMemorySize () const override private virtual
Returns the size of the instance memory struct that stores the states of this task.
{
    return sizeof(FRotateToFaceTargetTaskMemory);
}
GetStaticDescription()
FString UDkBTTask_RotateToFaceTarget::GetStaticDescription () const override private virtual
Displays a description of the task in the editor.
{
    const FString KeyDescription{ InTargetActorToFaceKey.SelectedKeyName.ToString() };
    return FString::Printf(TEXT("%s\nTarget Actor Key: %s\nAngle Precision: %.2f\nRotation Interp Speed: %.2f"),
        *Super::GetStaticDescription(),
        *KeyDescription,
        AnglePrecision,
        RotationInterpSpeed);
}
References AnglePrecision, InTargetActorToFaceKey, and RotationInterpSpeed.
HasReachedAnglePrecision()
bool UDkBTTask_RotateToFaceTarget::HasReachedAnglePrecision (APawn * QueryPawn, AActor * TargetActor) const private
{
    const FVector OwnerForward{ QueryPawn->GetActorForwardVector() };
    const FVector OwnerToTargetNormalized{ (TargetActor->GetActorLocation() - QueryPawn->GetActorLocation()).GetSafeNormal() };
    const double DotProduct{ FVector::DotProduct(OwnerForward, OwnerToTargetNormalized) }; // [-1, 1]
    const double AngleDegrees{ UKismetMathLibrary::DegAcos(DotProduct) };
    return AngleDegrees <= AnglePrecision;
}
References AnglePrecision.
Referenced by ExecuteTask(), and TickTask().
InitializeFromAsset()
void UDkBTTask_RotateToFaceTarget::InitializeFromAsset (UBehaviorTree & Asset) override private virtual
Initializes the task from the behavior tree asset.
{
    Super::InitializeFromAsset(Asset);
    if (UBlackboardData* BBAsset{ GetBlackboardAsset() })
    {
        InTargetActorToFaceKey.ResolveSelectedKey(*BBAsset);
    }
}
References InTargetActorToFaceKey.
TickTask()
void UDkBTTask_RotateToFaceTarget::TickTask (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, float DeltaSeconds) override private virtual
Called every tick while this task is running.
{
    FRotateToFaceTargetTaskMemory* Memory{ CastInstanceNodeMemory<FRotateToFaceTargetTaskMemory>(NodeMemory) };
    if (!Memory->IsValid())
    {
        FinishLatentTask(OwnerComp, EBTNodeResult::Failed);
    }
    if (HasReachedAnglePrecision(Memory->OwningPawn.Get(), Memory->TargetActor.Get()))
    {
        Memory->Reset();
        FinishLatentTask(OwnerComp, EBTNodeResult::Succeeded);
    }
    else // Rotate towards target
    {
        const FRotator LookAtRot{ UKismetMathLibrary::FindLookAtRotation(Memory->OwningPawn->GetActorLocation(), Memory->TargetActor->GetActorLocation()) };
        const FRotator TargetRot{ FMath::RInterpTo(Memory->OwningPawn->GetActorRotation(),LookAtRot, DeltaSeconds, RotationInterpSpeed) };
        Memory->OwningPawn->SetActorRotation(TargetRot);
    }
}
References HasReachedAnglePrecision(), FRotateToFaceTargetTaskMemory::IsValid(), FRotateToFaceTargetTaskMemory::OwningPawn, FRotateToFaceTargetTaskMemory::Reset(), RotationInterpSpeed, and FRotateToFaceTargetTaskMemory::TargetActor.
Member Data Documentation
AnglePrecision
float UDkBTTask_RotateToFaceTarget::AnglePrecision private
The threshold angle (in degrees) within which the rotation is considered complete.
Referenced by GetStaticDescription(), HasReachedAnglePrecision(), and UDkBTTask_RotateToFaceTarget().
InTargetActorToFaceKey
FBlackboardKeySelector UDkBTTask_RotateToFaceTarget::InTargetActorToFaceKey private
Blackboard key selector for the target actor to face.
Referenced by ExecuteTask(), GetStaticDescription(), InitializeFromAsset(), and UDkBTTask_RotateToFaceTarget().
RotationInterpSpeed
float UDkBTTask_RotateToFaceTarget::RotationInterpSpeed private
The speed at which the character rotates towards the target.
Referenced by GetStaticDescription(), TickTask(), and UDkBTTask_RotateToFaceTarget().
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/AI/DkBTTask_RotateToFaceTarget.h
D:/DkRPG/Source/DkRPG/AI/DkBTTask_RotateToFaceTarget.cpp