DkRPG: UDkEnemyCombatComponent Class Reference
UDkEnemyCombatComponent Class Reference
Combat component implementing enemy-specific combat behavior.
#include <DkEnemyCombatComponent.h>
Public Member Functions
virtual void OnHitTargetActor (AActor *HitActor, FVector HitLocation) override
Overrides with actual implementation.
virtual void OnWeaponPulledFromTargetActor (AActor *InteractedActor) override
Override with actual implementation.
Public Member Functions inherited from UDkPawnCombatComponent
void RegisterSpawnedWeapon (FGameplayTag WeaponTag, ADkWeaponBase *SpawnedWeapon, bool bRegisterAsEquippedWeapon=false)
Registers a spawned weapon to the character's carried weapon map and binds hit delegates.
ADkWeaponBase * GetCharacterCarriedWeaponByTag (FGameplayTag WeaponTag) const
Retrieves the weapon currently carried by the character associated with the provided gameplay tag.
ADkWeaponBase * GetCharacterCurrentEquippedWeapon () const
Retrieves the character's currently equipped weapon.
void ToggleWeaponCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType=EDkToggleDamageType::CurrentEquippedWeapon)
Enables or disables weapon collision. Clears OverlappedActors when disabling collision.
Protected Member Functions
virtual void ToggleBodyCollisionBoxCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType) override
Enables or disables (and clear OverlappedActors) collision for the enemy's body collision boxes (e.g., hands).
Protected Member Functions inherited from UDkPawnCombatComponent
virtual void ToggleCurrentEquippedWeaponCollision (bool bShouldEnableCollision)
Enables or disables collision for the character's currently equipped weapon.
Protected Member Functions inherited from UDkPawnExtensionComponentBase
template<class T>
T * GetOwningPawn () const
Gets the owning Pawn cast to the specified type T.
APawn * GetOwningPawn () const
Gets the owning Pawn as an APawn.
template<class T>
T * GetOwningController () const
Gets the controller of the owning Pawn cast to the specified type T.
Additional Inherited Members
Public Attributes inherited from UDkPawnCombatComponent
FGameplayTag CurrentEquippedWeaponTag
Automatically set for enemies, but must be set manually for the Hero in blueprint upon equipping/unequipping weapons.
Protected Attributes inherited from UDkPawnCombatComponent
TArray< AActor * > OverlappedActors
Array of actors currently being hit by the character's weapon, to make sure damage is only applied once per attack.
Detailed Description
Combat component implementing enemy-specific combat behavior.
Member Function Documentation
OnHitTargetActor()
void UDkEnemyCombatComponent::OnHitTargetActor (AActor * HitActor, FVector HitLocation) override virtual
Overrides with actual implementation.
Reimplemented from UDkPawnCombatComponent.
{
    if (OverlappedActors.Contains(HitActor))
    {
        return;
    }
    OverlappedActors.AddUnique(HitActor);
    bool bIsValidBlock{};
    const bool bIsPlayerBlocking{ UDkRPGFunctionLibrary::NativeDoesActorHaveTag(HitActor, DkGameplayTags::Player_Status_Blocking) };
    const bool bIsMyAttackUnblockable{ UDkRPGFunctionLibrary::NativeDoesActorHaveTag(GetOwningPawn(), DkGameplayTags::Enemy_Status_Unblockable) };
    if (bIsPlayerBlocking && !bIsMyAttackUnblockable)
    {
        bIsValidBlock = UDkRPGFunctionLibrary::IsValidBlock(GetOwningPawn(), HitActor);
    }
    UDkWeaponHitAdditionalInfo* AdditionalHitInfo{ NewObject<UDkWeaponHitAdditionalInfo>() };
    AdditionalHitInfo->SetHitLocation(HitLocation);
    FGameplayEventData EventData;
    EventData.Instigator = GetOwningPawn();
    EventData.Target = HitActor;
    EventData.OptionalObject = AdditionalHitInfo;
    if (bIsValidBlock)
    {
        UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetOwningPawn(), DkGameplayTags::Shared_Event_MeleeBlocked, EventData);
    }
    else
    {
        UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetOwningPawn(), DkGameplayTags::Shared_Event_MeleeHit, EventData);
    }
}
References UDkPawnExtensionComponentBase::GetOwningPawn(), UDkRPGFunctionLibrary::IsValidBlock(), UDkRPGFunctionLibrary::NativeDoesActorHaveTag(), UDkPawnCombatComponent::OverlappedActors, and UDkWeaponHitAdditionalInfo::SetHitLocation().
OnWeaponPulledFromTargetActor()
void UDkEnemyCombatComponent::OnWeaponPulledFromTargetActor (AActor * InteractedActor) override virtual
Override with actual implementation.
Reimplemented from UDkPawnCombatComponent.
{
}
ToggleBodyCollisionBoxCollision()
void UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision (bool bShouldEnableCollision, EDkToggleDamageType ToggleDamageType) override protected virtual
Enables or disables (and clear OverlappedActors) collision for the enemy's body collision boxes (e.g., hands).
Currently, our Hero character does not use body collision boxes for melee attacks, only enemies do. So we implement this function here instead of in the base UDkPawnCombatComponent.
Reimplemented from UDkPawnCombatComponent.
{
    ADkEnemy* OwningEnemyCharacter{ Cast<ADkEnemy>(GetOwningPawn()) };
    checkf(OwningEnemyCharacter, TEXT("UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision called but owning pawn is not of type ADkEnemy!"));
    UBoxComponent* LeftHandCollisionBox{ OwningEnemyCharacter->GetLeftHandCollisionBox() };
    UBoxComponent* RightHandCollisionBox{ OwningEnemyCharacter->GetRightHandCollisionBox() };
    checkf(LeftHandCollisionBox && RightHandCollisionBox, TEXT("UDkEnemyCombatComponent::ToggleBodyCollisionBoxCollision called but owning ADkEnemy is missing hand collision boxes!"));
    switch (ToggleDamageType)
    {
    case EDkToggleDamageType::LeftHand:
        LeftHandCollisionBox->SetCollisionEnabled(bShouldEnableCollision ? ECollisionEnabled::QueryOnly : ECollisionEnabled::NoCollision);
        break;
    case EDkToggleDamageType::RightHand:
        RightHandCollisionBox->SetCollisionEnabled(bShouldEnableCollision ? ECollisionEnabled::QueryOnly : ECollisionEnabled::NoCollision);
        break;
    default:
        break;
    }
    if (!bShouldEnableCollision)
    {
        OverlappedActors.Empty();
    }
}
References ADkEnemy::GetLeftHandCollisionBox(), UDkPawnExtensionComponentBase::GetOwningPawn(), ADkEnemy::GetRightHandCollisionBox(), LeftHand, UDkPawnCombatComponent::OverlappedActors, and RightHand.
The documentation for this class was generated from the following files:
D:/DkRPG/Source/DkRPG/Components/Combat/DkEnemyCombatComponent.h
D:/DkRPG/Source/DkRPG/Components/Combat/DkEnemyCombatComponent.cpp