DkRPG: Debug Namespace Reference
Debug Namespace Reference
Utility functions for debugging purposes inside the editor and during gameplay.
Functions
static void Print (const FString &Message, const FColor &Color=FColor::White, int32 InKey=-1, float Duration=5.0f)
Prints a debug message to the screen and the output log.
static void Print (const FString &FloatTitle, float ValueToPrint, const FColor &Color=FColor::White, int32 InKey=-1, float Duration=5.0f)
Detailed Description
Utility functions for debugging purposes inside the editor and during gameplay.
Function Documentation
Print() [1/2]
void Debug::Print (const FString & FloatTitle, float ValueToPrint, const FColor & Color = FColor::White, int32 InKey = -1, float Duration = 5.0f) static
    {
        if (GEngine)
        {
            FString Message = FString::Printf(TEXT("%s --> %f"), *FloatTitle, ValueToPrint);
            GEngine->AddOnScreenDebugMessage(InKey, Duration, Color, Message);
            UE_LOG(LogTemp, Warning, TEXT("%s"), *Message);
        }
    }
Print() [2/2]
void Debug::Print (const FString & Message, const FColor & Color = FColor::White, int32 InKey = -1, float Duration = 5.0f) static
Prints a debug message to the screen and the output log.
    {
        if (GEngine)
        {
            GEngine->AddOnScreenDebugMessage(InKey, Duration, Color, Message);
            UE_LOG(LogTemp, Warning, TEXT("%s"), *Message);
        }
    }
Referenced by ADkAIController::BeginPlay(), UDkGEEC_DamageTaken::Execute_Implementation(), UDkGameplayAbility::OnGameplayTagChanged_CancelAbility(), and ADkHero::PossessedBy().