DkRPG: FDkInputActionConfig Struct Reference
FDkInputActionConfig Struct Reference
Data structure defining the mapping between a gameplay tag and an input action.
#include <DkDataAsset_InputConfig.h>
Public Member Functions
bool IsValid () const
true when both InputTag and InputAction are valid
Public Attributes
FGameplayTag InputTag
Gameplay tag used to identify this input action.
TObjectPtr< UInputAction > InputAction
Input Action associated with the specified Gameplay Tag.
Detailed Description
Data structure defining the mapping between a gameplay tag and an input action.
Used to look up input actions by tag instead of hard references.
Member Function Documentation
IsValid()
bool FDkInputActionConfig::IsValid () const inline
true when both InputTag and InputAction are valid
    {
        return InputTag.IsValid() && InputAction;
    }
References InputAction, InputTag, and IsValid().
Referenced by UDkInputComponent::BindAbilityInputAction(), and IsValid().
Member Data Documentation
InputAction
TObjectPtr<UInputAction> FDkInputActionConfig::InputAction
Input Action associated with the specified Gameplay Tag.
Referenced by UDkInputComponent::BindAbilityInputAction(), and IsValid().
InputTag
FGameplayTag FDkInputActionConfig::InputTag
Gameplay tag used to identify this input action.
Referenced by UDkInputComponent::BindAbilityInputAction(), and IsValid().
The documentation for this struct was generated from the following file:
D:/DkRPG/Source/DkRPG/DataAssets/Input/DkDataAsset_InputConfig.h