DkRPG: FRotateToFaceTargetTaskMemory Struct Reference
FRotateToFaceTargetTaskMemory Struct Reference
Memory structure storing runtime state for the non-instanced RotateToFaceTarget behavior tree task.
#include <DkBTTask_RotateToFaceTarget.h>
Public Member Functions
bool IsValid () const
Checks if both the owning pawn and target actor are valid.
void Reset ()
Resets the stored pointers.
Public Attributes
TWeakObjectPtr< APawn > OwningPawn
The pawn that owns this task.
TWeakObjectPtr< AActor > TargetActor
The target actor to face.
Detailed Description
Memory structure storing runtime state for the non-instanced RotateToFaceTarget behavior tree task.
Member Function Documentation
IsValid()
bool FRotateToFaceTargetTaskMemory::IsValid () const inline
Checks if both the owning pawn and target actor are valid.
    {
        return OwningPawn.IsValid() && TargetActor.IsValid();
    }
References OwningPawn, and TargetActor.
Referenced by UDkBTTask_RotateToFaceTarget::ExecuteTask(), and UDkBTTask_RotateToFaceTarget::TickTask().
Reset()
void FRotateToFaceTargetTaskMemory::Reset () inline
Resets the stored pointers.
    {
        OwningPawn.Reset();
        TargetActor.Reset();
    }
References OwningPawn, and TargetActor.
Referenced by UDkBTTask_RotateToFaceTarget::ExecuteTask(), and UDkBTTask_RotateToFaceTarget::TickTask().
Member Data Documentation
OwningPawn
TWeakObjectPtr<APawn> FRotateToFaceTargetTaskMemory::OwningPawn
The pawn that owns this task.
Referenced by UDkBTTask_RotateToFaceTarget::ExecuteTask(), IsValid(), Reset(), and UDkBTTask_RotateToFaceTarget::TickTask().
TargetActor
TWeakObjectPtr<AActor> FRotateToFaceTargetTaskMemory::TargetActor
The target actor to face.
Referenced by UDkBTTask_RotateToFaceTarget::ExecuteTask(), IsValid(), Reset(), and UDkBTTask_RotateToFaceTarget::TickTask().
The documentation for this struct was generated from the following file:
D:/DkRPG/Source/DkRPG/AI/DkBTTask_RotateToFaceTarget.h